### ISSUE TITLE
blank statuspage , `api/status-page/monitor-list `endpoint only returns `[]`

### ISSUE THREAD

**Issue by benchonaut** [louislam/uptime-kuma#1168]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Docker Setup ,  `api/status-page/monitor-list `endpoint only returns `[]`

### 👟 Reproduction steps

Setup uptime-kuma bhind nginx, verfy websockets work , check browser console 

### 👀 Expected behavior

show monitors

### 😓 Actual Behavior

shows none die to empty api/status-page/monitor-list

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

docker

### 🌐 Browser

FF 94

### 🐋 Docker Version

20.10.X

### 🟩 NodeJS Version

unknown

### 📝 Relevant log output

```shell
TypeError: right-hand side of 'in' should be an object, got undefined
```

**Comment by louislam** [comment]
Sounds like it is not a bug. I convert it to "help".

If you think it is a bug of Uptime Kuma, please reproduce in https://demo.uptime.kuma.pet

![image](https://user-images.githubusercontent.com/1336778/149109014-aec1106a-dbc5-44f7-b86d-0ba421c39f01.png)

**Comment by MostHated** [comment]
You have to go to /status, hit "Edit status page" then add the server and save it, then it shows up.

**Comment by benchonaut** [comment]
> You have to go to /status, hit "Edit status page" then add the server and save it, then it shows up when you query the api.

^^ would have done so , but page is emtpy

FTW: have the same setup running on x86 pretty well since ~6 months , on arm64 the statuspage is just empty

**Comment by benchonaut** [comment]
@louislam -> i guess your demo does not run on arm64 ?

**Comment by louislam** [comment]
> @louislam -> i guess your demo does not run on arm64 ?

It works fine on my Oracle arm64 vm. Which arm64 device are you using?

**Comment by fabriziogaliano** [comment]
i'm using kuma on x86 server, inside a container, everything was working correctly for about 2 month, starting from this morning the dashboard doesn't show no more monitors, randomly.

docker version: 20.10.17 CE
kuma version: 1.17.1-debian
monitor configured: 112
feature used: microsoft team integration
errors:
[2022-09-02 04:38:49] KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:305:26)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:259:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.findOne (/app/node_modules/redbean-node/dist/redbean-node.js:515:19)
    at async beat (/app/server/model/monitor.js:191:32)
    at async safeBeat (/app/server/model/monitor.js:561:17) {
  sql: undefined,
  bindings: undefined
}
[2022-09-02 04:58:35] Error: aborted
    at PendingOperation.abort (/app/node_modules/tarn/dist/PendingOperation.js:25:21)
    at /app/node_modules/tarn/dist/Pool.js:208:25
    at Array.map (<anonymous>)
    at /app/node_modules/tarn/dist/Pool.js:207:53
    at async Client_SQLite3.destroy (/app/node_modules/knex/lib/client.js:331:9)
