### ISSUE TITLE
Need to help to run in replit

### ISSUE THREAD

**Issue by AIGaming01** [louislam/uptime-kuma#1181]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hey, I am new to uptime-kuma.I liked the project a lot and tried to run it by my own in repl.it.But its not starting and i am not sure which informations do i have to provide in order to run uptime-kuma.I'm using replit nodejs v12.22.6.I will be a lot helpful if someone could help me to run this in replit! Thanks

### 🐻 Uptime-Kuma Version

1.1 (latest one)

### 💻 Operating System and Arch

Repl.it 

### 🌐 Browser

Google Chrome

### 🟩 NodeJS Version

v12.22.6

**Comment by AIGaming01** [comment]
The error im facing:


 node server/server.js
Welcome to Uptime Kuma
Node Env: production
Importing Node libraries
Importing 3rd-party libraries
Importing this project modules
/home/runner/uptime-kuma/server/model/monitor.js:193
                    if (this.getUrl()?.protocol === "https:") {
                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/uptime-kuma/server/server.js:42:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10

**Comment by louislam** [comment]
💪🏻 Non-Docker
Required Tools: Node.js >= 14, git and pm2.

**Comment by AIGaming01** [comment]
> 💪🏻 Non-Docker Required Tools: Node.js >= 14, git and pm2.

but can't i host it in replit? and how do i get this things in replit? i know about node v14 but what about git and pm2?
