### ISSUE TITLE
Self signed certificate Rocketchat notifications

### ISSUE THREAD

**Issue by Paulpatou** [louislam/uptime-kuma#1344]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Is it possible to add a self-signed certificate for notifications with Rocketchat ?

I currently have an alert about this ![Self_signed cleaned](https://user-images.githubusercontent.com/33478981/155946640-89848113-ae6c-4315-9abe-4cc370e0f11c.png)

Debug log in docker =>

![error_selfsigned cleaned](https://user-images.githubusercontent.com/33478981/155946665-fac4b36d-2a7c-4783-a8e0-bd35689a835f.png)
 

### ✔️ Solution

I tried `NODE_TLS_REJECT_UNAUTHORIZED: 0` as indicated here #19 but it doesn't work

**Comment by jkoppen89** [comment]
Hi,

I've got the same error but using with Gotify.

`Error: Error: AxiosError: Request failed with status code 404`
`    at Gotify.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:38:15)`
`    at Gotify.send (/app/server/notification-providers/gotify.js:23:18)`
`    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`
`    at async Socket.<anonymous> (/app/server/server.js:1304:27)`

**Comment by demaniak** [comment]
I managed to get a SmallStep-CA selfhosted cert working by adding a env variable like so:
```
- NODE_EXTRA_CA_CERTS=/app/data/docker-tls/root_ca.crt
```

Where "/app/data/docker-tls" is a patch, that in my case, is being bind mounted into the container from an external source.

The "root_ca.crt" is the root certificate generated by smallstep-ca 

Could something like that maybe help with your selfsigned situation @Paulpatou ?
