### ISSUE TITLE
when restart 

### ISSUE THREAD

**Issue by ShadowGaming100** [louislam/uptime-kuma#1516]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

i updated the uptime-kim’s and then is to restart and i restarted 

### 👟 Reproduction steps

npm restart

### 👀 Expected behavior

to restart the website 

### 😓 Actual Behavior

it didn’t restart

### 🐻 Uptime-Kuma Version

1.14.0

### 💻 Operating System and Arch

how to check in replit i don’t know

### 🌐 Browser

Google Chrome

### 🟩 NodeJS Version

latest

### 📝 Relevant log output

```shell
[2022-04-18 12:12:45] TypeError: Cannot read property 'kill' of undefined
    at CloudflaredTunnel.stop (/home/runner/Uptime/node_modules/node-cloudflared-tunnel/cloudflared-tunnel.js:115:27)
    at module.exports.stop (/home/runner/Uptime/server/socket-handlers/cloudflared-socket-handler.js:89:17)
    at shutdownFunction (/home/runner/Uptime/server/server.js:1632:11)
    at async Server.<anonymous> (/home/runner/Uptime/server/server.js:1438:9)
[2022-04-18 12:13:03] TypeError: Cannot read property 'kill' of undefined
    at CloudflaredTunnel.stop (/home/runner/Uptime/node_modules/node-cloudflared-tunnel/cloudflared-tunnel.js:115:27)
    at module.exports.stop (/home/runner/Uptime/server/socket-handlers/cloudflared-socket-handler.js:89:17)
    at shutdownFunction (/home/runner/Uptime/server/server.js:1632:11)
    at async Server.<anonymous> (/home/runner/Uptime/server/server.js:1438:9)
[2022-04-18 12:13:22] TypeError: Cannot read property 'kill' of undefined
    at CloudflaredTunnel.stop (/home/runner/Uptime/node_modules/node-cloudflared-tunnel/cloudflared-tunnel.js:115:27)
    at module.exports.stop (/home/runner/Uptime/server/socket-handlers/cloudflared-socket-handler.js:89:17)
    at shutdownFunction (/home/runner/Uptime/server/server.js:1632:11)
    at async Server.<anonymous> (/home/runner/Uptime/server/server.js:1438:9)
[2022-04-18 12:15:07] TypeError: Cannot read property 'kill' of undefined
    at CloudflaredTunnel.stop (/home/runner/Uptime/node_modules/node-cloudflared-tunnel/cloudflared-tunnel.js:115:27)
    at module.exports.stop (/home/runner/Uptime/server/socket-handlers/cloudflared-socket-handler.js:89:17)
    at shutdownFunction (/home/runner/Uptime/server/server.js:1632:11)
    at async Server.<anonymous> (/home/runner/Uptime/server/server.js:1438:9)
```

**Comment by louislam** [comment]
`npm restart` is not supported. Please use pm2.

**Comment by ShadowGaming100** [comment]
> `npm restart` is not supported. Please use pm2.

I tried with pm2 is invalid

**Comment by ShadowGaming100** [comment]
> > > `npm restart` is not supported. Please use pm2.
> > 
> > 
> > I tried with pm2 is invalid
> 
> If you mean by invalid the command wasn't found, you need to install pm2 with `npm install -g pm2`

I did same I am using replit
But I will try again

**Comment by louislam** [comment]
Please noted that Uptime Kuma is never officially supported on Replit. I had seen some Replit users reported strange issue here before.

Btw, where did you know that you could run Uptime Kuma on Replit?

**Comment by ShadowGaming100** [comment]
> Please noted that Uptime Kuma is never officially supported on Replit. I had seen some Replit users reported strange issues here before.
> 
> Btw, where did you know that you could run Uptime Kuma on Replit?

I didn't know I tried my self by following the steps

But where can you run uptime-kuma is there any online website

**Comment by louislam** [comment]
Free: Oracle Cloud
5usd/mo: Digital Ocean or Linode

**Comment by ShadowGaming100** [comment]
I know this is not about uptime

18,000 GB hours per month

What does it mean

> Free: Oracle Cloud 5usd/mo: Digital Ocean or Linode

I know this is not about uptime-kuma but what does it mean

18,000 GB hours per month
