### ISSUE TITLE
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

### ISSUE THREAD

**Issue by gruessung** [louislam/uptime-kuma#1661]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

```Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?


    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:305:26)


    at runMicrotasks (<anonymous>)


    at runNextTicks (node:internal/process/task_queues:61:5)


    at listOnTimeout (node:internal/timers:528:9)


    at processTimers (node:internal/timers:502:7)


    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:259:28)


    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)


    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:570:22)


    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:556:22)


    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:591:19) {


  sql: 'SELECT `value` FROM setting WHERE `key` = ?  limit ?',


  bindings: [ 'primaryBaseURL', 1 ]


}


    at process.<anonymous> (/app/server/server.js:1696:13)


    at process.emit (node:events:527:28)


    at emit (node:internal/process/promises:140:20)


    at processPromiseRejections (node:internal/process/promises:274:27)


    at processTicksAndRejections (node:internal/process/task_queues:97:32)


    at runNextTicks (node:internal/process/task_queues:65:3)


    at listOnTimeout (node:internal/timers:528:9)


    at processTimers (node:internal/timers:502:7)


If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues


Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?


    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:305:26)


    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:259:28)


    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)


    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:570:22)


    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:556:22)


    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:591:19)


    at async exports.setting (/app/server/util-server.js:212:17)


    at async Namespace.<anonymous> (/app/server/server.js:1430:13) {


  sql: 'SELECT `value` FROM setting WHERE `key` = ?  limit ?',


  bindings: [ 'disableAuth', 1 ]


}``

### 👟 Reproduction steps

I added a new dashboard, delete an old monitor and rename an existing monitor during one minute. 

### 👀 Expected behavior

No errors :) 

### 😓 Actual Behavior

Uptime does not work anymore.

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

Debian Server 

### 🌐 Browser

Chrome

### 🐋 Docker Version

_No response_

### 🟩 NodeJS Version

_No response_

### 📝 Relevant log output

_No response_

**Comment by chakflying** [comment]
Deleting an old monitor may take a long time. Did you wait for it to complete before doing other operations?

**Comment by louislam** [comment]
Usually due to bad performance of read/write, also make sure it is not a network drive.

Please see this for more hints and focus on one post. https://github.com/louislam/uptime-kuma/issues/1397
