### ISSUE TITLE
[smtp] Office 365 authentication

### ISSUE THREAD

**Issue by Drynael** [louislam/uptime-kuma#1713]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Upon creating a Mail Notification and using Office 365 i run in following Error:

`Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the request did not meet the criteria to be authenticated successfully. Contact your administrator. [AM6P193CA0093.EURP193.PROD.OUTLOOK.COM]
    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1536:34)
    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1490:18)
    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)
    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
    at TLSSocket.SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10) {
  code: 'EAUTH',
  response: '535 5.7.139 Authentication unsuccessful, the request did not meet the criteria to be authenticated successfully. Contact your administrator. [AM6P193CA0093.EURP193.PROD.OUTLOOK.COM]',
  responseCode: 535,
  command: 'AUTH LOGIN'
}`

![image](https://user-images.githubusercontent.com/15029013/171468788-bcaa32d9-d3b0-438b-8919-07b3de06c5ca.png)

### 👟 Reproduction steps

Create New Notification
Enter Office 365 Credentials
Test

### 👀 Expected behavior

Sending a E-Mail

### 😓 Actual Behavior

Runs in an authentication error

### 🐻 Uptime-Kuma Version

1.16.1

### 💻 Operating System and Arch

linux x86_64 Debian GNU/Linux 11 (bullseye)

### 🌐 Browser

Google Chrome Version 102.0.5005.62

### 🐋 Docker Version

20.10.12 (API: 1.41)

### 📝 Relevant log output

```shell
Error: Invalid login: 535 5.7.139 Authentication unsuccessful, the request did not meet the criteria to be authenticated successfully. Contact your administrator. [AM6P193CA0093.EURP193.PROD.OUTLOOK.COM]
    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1536:34)
    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1490:18)
    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)
    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
    at TLSSocket.SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10) {
  code: 'EAUTH',
  response: '535 5.7.139 Authentication unsuccessful, the request did not meet the criteria to be authenticated successfully. Contact your administrator. [AM6P193CA0093.EURP193.PROD.OUTLOOK.COM]',
  responseCode: 535,
  command: 'AUTH LOGIN'
}
```

**Comment by Computroniks** [comment]
Ahh ok, so we would need to support a new method of authentication for microsoft email servers such as OAuth2. In which case, would it be possible to change this issue from a bug to a feature request for support for this. Anoyingly, OAuth will be more complicated to implement as it requires that we register the app with Azure Active directory. Microsoft have provided details on how to go about implementing this feature here, https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth. Due to the deadline of October 1, 2022 this should probably be fairly high priority as it will probably take a while to get the registration with Azure.

@louislam Sorry to ping you, as this requires registering with an external service, I think that that might be something that you would need to do. I could probably get the rest of it done this weekend or next weekend because I plan to finish off #1550 tomorrow (02/06/22)

Link to docs for nodemailer:
https://nodemailer.com/smtp/oauth2/

**Comment by louislam** [comment]
> Ahh ok, so we would need to support a new method of authentication for microsoft email servers such as OAuth2. In which case, would it be possible to change this issue from a bug to a feature request for support for this. Anoyingly, OAuth will be more complicated to implement as it requires that we register the app with Azure Active directory. Microsoft have provided details on how to go about implementing this feature here, https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth. Due to the deadline of October 1, 2022 this should probably be fairly high priority as it will probably take a while to get the registration with Azure.
> 
> @louislam Sorry to ping you, as this requires registering with an external service, I think that that might be something that you would need to do. I could probably get the rest of it done this weekend or next weekend because I plan to finish off #1550 tomorrow (02/06/22)
> 
> Link to docs for nodemailer: https://nodemailer.com/smtp/oauth2/

Thanks. I suggested that it could be a notification type maybe called `Office 365 SMTP OAuth`. So ideally, users just need to hit the Microsoft Login button and done.

Is that mean all existing office 365 smtp with basic auth will be closed on October 1? If yes, it will be a big disaster to the world. I don't think every applications could upgrade to the oauth peacefully.

**Comment by Computroniks** [comment]
Sounds good. I think the 1st of October deadline is when they start to turn it off which means after that support will vary between accounts which would likely cause Chaos. I should have finished the JSDoc pr by mid day today so I will start to take a crack at this then.

**Comment by Computroniks** [comment]
Well, not sure what happened to my comment. It looked like it duplicated but hadn't 

Original comment(ish)

Sounds good, I will finish off the JSDoc pr today and start on this one with it being done either this weekend or next weekend hopefully

**Comment by Computroniks** [comment]
@louislam There doesn't actually seem to be a need for this as it is already accomodated for with Apprise. Instead, I will add a PR to the wiki documenting this.
https://github.com/caronc/apprise/wiki/Notify_office365

**Comment by louislam** [comment]
> @louislam There doesn't actually seem to be a need for this as it is already accomodated for with Apprise. ~Instead, I will add a PR to the wiki documenting this.~ Have added a comment to #284 https://github.com/caronc/apprise/wiki/Notify_office365

Thanks, just checked their guide, it is quite a lot of steps and difficult in order to get all IDs. I think Microsoft really make a big mistake for this, people will just quit and use other smtp providers.

**Comment by athornfam2** [comment]
Bumping this request again @louislam

**Comment by CommanderStorm** [comment]
@athornfam2 

Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing **what needs to be done how by whom**.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc), as always: [Pull Requests](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) welcome.

As mentioned above:
> I suggested that it could be a new notification type maybe called Office 365 SMTP OAuth

PRs for Notification providers are encouraged, see https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

**Comment by adoyle-h** [comment]
It still not supported since 2022. Three years have passed.

**Comment by msgwing** [comment]
`535 5.7.139` isn't something uptime-kuma can work around from inside a Mail Notification form — it means SMTP AUTH with a username and password is switched off on the Microsoft 365 side, so the notification never gets a chance to authenticate no matter what's typed into the fields here.

The reason this feature request has sat for three years is that the real fix is OAuth 2.0, which needs a registered application, a browser consent flow and refreshable tokens — a different shape of integration than a notification type, and a lot of surface area for a project this size to maintain and keep secure indefinitely.

Two things that don't require waiting on that:

1. **Ask whoever administers the Microsoft 365 tenant to re-enable SMTP AUTH** for the mailbox in question, if that's available to them (Microsoft's own docs cover how). This keeps everything as-is with no workaround needed.
2. **Point the Mail Notification at any SMTP server that still accepts a username and password.** uptime-kuma doesn't care whose server it is — it just needs a host, a port and a login that works.

[Removed Ads]
