### ISSUE TITLE
Error  node server/server.js  ../uptime-kuma/server/server.js:648 

### ISSUE THREAD

**Issue by Jujubalandia** [louislam/uptime-kuma#1760]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

First congrat for this project, very nice UI, documentation and github structure

I'm running for the first time and receiving this error message

~/dev/uptime-kuma$ node server/server.js
/home/bera/dev/uptime-kuma/server/server.js:648
                server.monitorList[monitor.id]?.prometheus()?.remove();
                                               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

### 👟 Reproduction steps

~/dev/uptime-kuma$ node server/server.js

### 👀 Expected behavior

http://localhost:3001/

### 😓 Actual Behavior

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

### 🐻 Uptime-Kuma Version

1.16.1

### 💻 Operating System and Arch

Raspberry Pi /Arm

### 🌐 Browser

Chrome

### 🟩 NodeJS Version

v12.21.0

### 📝 Relevant log output

```shell
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by louislam** [comment]
Node.js > 14

**Comment by asdfok** [comment]
Hi, I am using kuma in docker. I got this notification in the docker log.

==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Your Node.js version: 16
2022-07-24T06:00:55.661Z [SERVER] INFO: Welcome to Uptime Kuma
2022-07-24T06:00:55.662Z [SERVER] INFO: Node Env: production
2022-07-24T06:00:55.662Z [SERVER] INFO: Importing Node libraries
2022-07-24T06:00:55.665Z [SERVER] INFO: Importing 3rd-party libraries
2022-07-24T06:00:59.129Z [SERVER] INFO: Creating express and socket.io instance
2022-07-24T06:00:59.135Z [SERVER] INFO: Server Type: HTTP
2022-07-24T06:00:59.148Z [SERVER] INFO: Importing this project modules
2022-07-24T06:00:59.533Z [NOTIFICATION] INFO: Prepare Notification Providers
/app/node_modules/yup/lib/util/reach.js:5
});
  ^
SyntaxError: Unexpected token ';'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/node_modules/yup/lib/schema.js:22:14)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)

How to fix this
![Screenshot - 7_24_2022 , 1_07_42 PM](https://user-images.githubusercontent.com/20973422/180634674-59efce67-3443-414d-b401-167343e36502.png)
?

**Comment by louislam** [comment]
@asdfok 

It is very strange. How did you install?

**Comment by asdfok** [comment]
> @asdfok
> 
> It is very strange. How did you install?

I installed it in docker, using the stack as below.

version: '2'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    volumes:
      - ./uptime-kuma:/app/data
    ports:
      - 3001:3001

**Comment by coookiemonsterm** [comment]
Hi there,
Using this without docker and getting this error
