### ISSUE TITLE
Stalling in docker

### ISSUE THREAD

**Issue by IrishOfficial** [louislam/uptime-kuma#2208]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/home/container/node_modules/knex/lib/client.js:305:26)
    at async Runner.ensureConnection (/home/container/node_modules/knex/lib/execution/runner.js:259:28)
    at async Runner.run (/home/container/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/home/container/node_modules/redbean-node/dist/redbean-node.js:588:22)
    at async RedBeanNode.getRow (/home/container/node_modules/redbean-node/dist/redbean-node.js:574:22)
    at async Function.calcUptime (/home/container/server/model/monitor.js:826:22)
    at async Function.sendUptime (/home/container/server/model/monitor.js:889:24)
    at async Function.sendStats (/home/container/server/model/monitor.js:767:13) {
  sql: '\n' +
    '            SELECT\n' +
    '               -- SUM all duration, also trim off the beat out of time window\n' +
    '                SUM(\n' +
    '                    CASE\n' +
    '                        WHEN (JULIANDAY(`time`) - JULIANDAY(?)) * 86400 < duration\n' +
    '                        THEN (JULIANDAY(`time`) - JULIANDAY(?)) * 86400\n' +
    '                        ELSE duration\n' +
    '                    END\n' +
    '                ) AS total_duration,\n' +
    '\n' +
    '               -- SUM all uptime duration, also trim off the beat out of time window\n' +
    '                SUM(\n' +
    '                    CASE\n' +
    '                        WHEN (status = 1)\n' +
    '                        THEN\n' +
    '                            CASE\n' +
    '                                WHEN (JULIANDAY(`time`) - JULIANDAY(?)) * 86400 < duration\n' +
    '                                    THEN (JULIANDAY(`time`) - JULIANDAY(?)) * 86400\n' +
    '                                ELSE duration\n' +
    '                            END\n' +
    '                        END\n' +
    '                ) AS uptime_duration\n' +
    '            FROM heartbeat\n' +
    '            WHERE time > ?\n' +
    '            AND monitor_id = ?\n' +
    '        ',
  bindings: [
    '2022-10-08 17:14:31',
    '2022-10-08 17:14:31',
    '2022-10-08 17:14:31',
    '2022-10-08 17:14:31',
    '2022-10-08 17:14:31',
    11
  ]
}
    at process.<anonymous> (/home/container/server/server.js:1728:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues

### 👟 Reproduction steps

Happens on multiple different container services and starts about a day after fully setting up system.

Stalls the system out and everything becomes uneditable.

### 👀 Expected behavior

To not stall

### 😓 Actual Behavior

Stalls

### 🐻 Uptime-Kuma Version

1.18.3

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome

### 🐋 Docker Version

20.10.9

### 🟩 NodeJS Version

14.18

### 📝 Relevant log output

```shell
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/home/container/node_modules/knex/lib/client.js:305:26)
    at async Runner.ensureConnection (/home/container/node_modules/knex/lib/execution/runner.js:259:28)
    at async Runner.run (/home/container/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/home/container/node_modules/redbean-node/dist/redbean-node.js:588:22)
    at async RedBeanNode.getRow (/home/container/node_modules/redbean-node/dist/redbean-node.js:574:22)
    at async Function.calcUptime (/home/container/server/model/monitor.js:826:22)
    at async Function.sendUptime (/home/container/server/model/monitor.js:889:24)
    at async Function.sendStats (/home/container/server/model/monitor.js:767:13) {
  sql: '\n' +
    '            SELECT\n' +
    '               -- SUM all duration, also trim off the beat out of time window\n' +
    '                SUM(\n' +
    '                    CASE\n' +
    '                        WHEN (JULIANDAY(`time`) - JULIANDAY(?)) * 86400 < duration\n' +
    '                        THEN (JULIANDAY(`time`) - JULIANDAY(?)) * 86400\n' +
    '                        ELSE duration\n' +
    '                    END\n' +
    '                ) AS total_duration,\n' +
    '\n' +
    '               -- SUM all uptime duration, also trim off the beat out of time window\n' +
    '                SUM(\n' +
    '                    CASE\n' +
    '                        WHEN (status = 1)\n' +
    '                        THEN\n' +
    '                            CASE\n' +
    '                                WHEN (JULIANDAY(`time`) - JULIANDAY(?)) * 86400 < duration\n' +
    '                                    THEN (JULIANDAY(`time`) - JULIANDAY(?)) * 86400\n' +
    '                                ELSE duration\n' +
    '                            END\n' +
    '                        END\n' +
    '                ) AS uptime_duration\n' +
    '            FROM heartbeat\n' +
    '            WHERE time > ?\n' +
    '            AND monitor_id = ?\n' +
    '        ',
  bindings: [
    '2022-10-08 17:14:31',
    '2022-10-08 17:14:31',
    '2022-10-08 17:14:31',
    '2022-10-08 17:14:31',
    '2022-10-08 17:14:31',
    11
  ]
}
    at process.<anonymous> (/home/container/server/server.js:1728:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
```

**Comment by louislam** [comment]
Duplicate of #1397
