### ISSUE TITLE
Unable to deploy it on Azure web app using docker

### ISSUE THREAD

**Issue by devopshelper4u** [louislam/uptime-kuma#2246]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Am trying to setup application on Azure Web App using docker.

But trying to do so, am getting error.
2022-10-19T17:08:45.444255094Z 2022-10-19T17:08:45.444Z [NOTIFICATION] INFO: Prepare Notification Providers
2022-10-19T17:08:45.695753612Z 2022-10-19T17:08:45.695Z [SERVER] INFO: Version: 1.18.5
2022-10-19T17:08:46.166167200Z 2022-10-19T17:08:46.165Z [DB] INFO: Data Dir: ./data/
2022-10-19T17:08:46.170528508Z 2022-10-19T17:08:46.170Z [SERVER] INFO: Copying Database
2022-10-19T17:08:46.208334743Z 2022-10-19T17:08:46.208Z [SERVER] INFO: Connecting to the Database
2022-10-19T17:08:47.733044220Z Trace: [Error: PRAGMA journal_mode = WAL - SQLITE_BUSY: database is locked] {
2022-10-19T17:08:47.733086324Z   errno: 5,
2022-10-19T17:08:47.733092324Z   code: 'SQLITE_BUSY'
2022-10-19T17:08:47.733096824Z }
2022-10-19T17:08:47.733101225Z     at process.<anonymous> (/app/server/server.js:1728:13)
2022-10-19T17:08:47.733106125Z     at process.emit (node:events:513:28)
2022-10-19T17:08:47.733110426Z     at emit (node:internal/process/promises:140:20)
2022-10-19T17:08:47.733114726Z     at processPromiseRejections (node:internal/process/promises:274:27)
2022-10-19T17:08:47.733119027Z     at processTicksAndRejections (node:internal/process/task_queues:97:32)
2022-10-19T17:08:47.745408376Z If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues

![image](https://user-images.githubusercontent.com/107870128/196760348-2da3f6ea-d6bc-4a09-ba2d-5a1a6f771d37.png)

### 👟 Reproduction steps

1. Create Azure web app with docker option
2. Provide below details in config
3. version: "3.7"
services:
  myapp:
    image: louislam/uptime-kuma:1
    volumes:
    - monitordata:/app/data
    ports:
    - 3001:3001
4. Also in Configuration section, add volume (File Share)
5. Enable logging
6. Check logs

### 👀 Expected behavior

Initial setup should work fine

### 😓 Actual Behavior

Error in SQLLite setup

### 🐻 Uptime-Kuma Version

louislam/uptime-kuma:1

### 💻 Operating System and Arch

Linux

### 🌐 Browser

Chrome

### 🐋 Docker Version

louislam/uptime-kuma:1

### 📝 Relevant log output

```shell
2022-10-19T17:08:45.444255094Z 2022-10-19T17:08:45.444Z [NOTIFICATION] INFO: Prepare Notification Providers
2022-10-19T17:08:45.695753612Z 2022-10-19T17:08:45.695Z [SERVER] INFO: Version: 1.18.5
2022-10-19T17:08:46.166167200Z 2022-10-19T17:08:46.165Z [DB] INFO: Data Dir: ./data/
2022-10-19T17:08:46.170528508Z 2022-10-19T17:08:46.170Z [SERVER] INFO: Copying Database
2022-10-19T17:08:46.208334743Z 2022-10-19T17:08:46.208Z [SERVER] INFO: Connecting to the Database
2022-10-19T17:08:47.733044220Z Trace: [Error: PRAGMA journal_mode = WAL - SQLITE_BUSY: database is locked] {
2022-10-19T17:08:47.733086324Z   errno: 5,
2022-10-19T17:08:47.733092324Z   code: 'SQLITE_BUSY'
2022-10-19T17:08:47.733096824Z }
2022-10-19T17:08:47.733101225Z     at process.<anonymous> (/app/server/server.js:1728:13)
2022-10-19T17:08:47.733106125Z     at process.emit (node:events:513:28)
2022-10-19T17:08:47.733110426Z     at emit (node:internal/process/promises:140:20)
2022-10-19T17:08:47.733114726Z     at processPromiseRejections (node:internal/process/promises:274:27)
2022-10-19T17:08:47.733119027Z     at processTicksAndRejections (node:internal/process/task_queues:97:32)
2022-10-19T17:08:47.745408376Z If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
```

**Comment by rezzorix** [comment]
Just a suspicion; but have you checked the (Folder)Permissions for `monitordata`?

**Comment by devopshelper4u** [comment]
> Just a suspicion; but have you checked the (Folder)Permissions for `monitordata`?

not a permission issue. I tried setting up another docker with volume and that works perfectly fine

**Comment by rezzorix** [comment]
> 4\. Also in Configuration section, add volume **(File Share)**

Could this be the issue?

> [How to Install](https://github.com/louislam/uptime-kuma#-how-to-install)
> 🐳 Docker
> ⚠️ Please use a local volume only. Other types such as NFS are not supported.
>

**Comment by devopshelper4u** [comment]
> > 4. Also in Configuration section, add volume **(File Share)**
> 
> Could this be the issue?
> 
> > [How to Install](https://github.com/louislam/uptime-kuma#-how-to-install)
> > 🐳 Docker
> > ⚠️ Please use a local volume only. Other types such as NFS are not supported.

Still no luck. Followed end-to-end doc but still same error.

**Comment by anatter** [comment]
I'm currently having the same issue when using Azure App Services Container. Have you found a workaround?

**Comment by louislam** [comment]
No chance. Please use a normal VPS.

> ⚠️ Please use a local volume only. Other types such as NFS are not supported.

**Comment by devopshelper4u** [comment]
> I'm currently having the same issue when using Azure App Services Container. Have you found a workaround?

No. no luck. Still having same issue. Looks like we cant have this app on Azure. Havent tried terraform script which doc. provides to setup app on Azure
