### ISSUE TITLE
SQLITE_BUSY: database is locked

### ISSUE THREAD

**Issue by aSilentSniper** [louislam/uptime-kuma#2302]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

After some time my uptime-kuma instance crashes with the Following Error message.

### 👟 Reproduction steps

Not really i dont do anything when the error occurs.

### 👀 Expected behavior

The expected behavior is that the Container runs without crashing

### 😓 Actual Behavior

The container ist crashing

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Ubuntu 18.04.6 LTS

### 🌐 Browser

Arc Version 0.75.0 (35563) Chromium Engine Version 107.0.5304.63

### 🐋 Docker Version

Docker version 20.10.21, build baeda1

### 🟩 NodeJS Version

14.17.4

### 📝 Relevant log output

```shell
SQLITE_BUSY: database is locked
Trace: [Error: insert into `heartbeat` (`down_count`, `duration`, `important`, `monitor_id`, `msg`, `ping`, `status`, `time`) values (0, 60, false, 11, '200 - OK', 344, 1, '2022-11-04 03:14:09.298') - SQLITE_BUSY: database is locked] {
  errno: 5,
  code: 'SQLITE_BUSY'
}
    at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:660:25)
2022-11-04T03:14:27.759Z [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: read ENOTCONN
    at tryReadStart (node:net:638:20)
    at Socket._read (node:net:649:5)
    at Socket.Readable.read (node:internal/streams/readable:487:10)
    at Socket.read (node:net:705:39)
    at new Socket (node:net:425:12)
    at Object.Socket (node:net:295:41)
    at createSocket (node:internal/child_process:328:14)
    at ChildProcess.spawn (node:internal/child_process:445:23)
    at spawn (node:child_process:713:9)
    at Ping.send (/app/server/ping-lite.js:108:18)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7) {
  errno: -107,
  code: 'ENOTCONN',
  syscall: 'read'
```

**Comment by louislam** [comment]
Please search first.
