### ISSUE TITLE
cloudflared issue

### ISSUE THREAD

**Issue by ZIODIOZIO** [louislam/uptime-kuma#2304]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Stop cloudflared
Trace: TypeError: Cannot read properties of undefined (reading 'kill')
    at CloudflaredTunnel.stop (/root/uptime-kuma/node_modules/node-cloudflared-t                       unnel/cloudflared-tunnel.js:115:27)
    at module.exports.stop (/root/uptime-kuma/server/socket-handlers/cloudflared                       -socket-handler.js:112:21)
    at shutdownFunction (/root/uptime-kuma/server/server.js:1709:11)
    at async Server.<anonymous> (/root/uptime-kuma/server/server.js:1475:9)
    at process.<anonymous> (/root/uptime-kuma/server/server.js:1728:13)
    at process.emit (node:events:513:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:3                       2)

### 👟 Reproduction steps

node server/server.js

### 👀 Expected behavior

Starting

### 😓 Actual Behavior

Stop cloudflared
Trace: TypeError: Cannot read properties of undefined (reading 'kill')
    at CloudflaredTunnel.stop (/root/uptime-kuma/node_modules/node-cloudflared-t                       unnel/cloudflared-tunnel.js:115:27)
    at module.exports.stop (/root/uptime-kuma/server/socket-handlers/cloudflared                       -socket-handler.js:112:21)
    at shutdownFunction (/root/uptime-kuma/server/server.js:1709:11)
    at async Server.<anonymous> (/root/uptime-kuma/server/server.js:1475:9)
    at process.<anonymous> (/root/uptime-kuma/server/server.js:1728:13)
    at process.emit (node:events:513:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:3                       2)

### 🐻 Uptime-Kuma Version

last

### 💻 Operating System and Arch

ubuntu 20

### 🌐 Browser

/

### 🐋 Docker Version

/

### 🟩 NodeJS Version

v10.19.0

### 📝 Relevant log output

```shell
Stop cloudflared
Trace: TypeError: Cannot read properties of undefined (reading 'kill')
    at CloudflaredTunnel.stop (/root/uptime-kuma/node_modules/node-cloudflared-t                       unnel/cloudflared-tunnel.js:115:27)
    at module.exports.stop (/root/uptime-kuma/server/socket-handlers/cloudflared                       -socket-handler.js:112:21)
    at shutdownFunction (/root/uptime-kuma/server/server.js:1709:11)
    at async Server.<anonymous> (/root/uptime-kuma/server/server.js:1475:9)
    at process.<anonymous> (/root/uptime-kuma/server/server.js:1728:13)
    at process.emit (node:events:513:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:3                       2)
```

**Comment by louislam** [comment]
> 👟 Reproduction steps

node server/server.js

Need detailed reproduction steps

**Comment by ZIODIOZIO** [comment]
> > 👟 Reproduction steps
> > node server/server.js
> 
> Need detailed reproduction steps

Did my explain my self:

``Dear,

I am simply starting it from
cd dir and then node server/server.js but any starting command doesn’t work``

**Comment by louislam** [comment]
> 🟩 NodeJS Version  v10.19.0

It is not a supported version, please check the minimum requirements in the README.md.
