### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by KingPin** [louislam/uptime-kuma#24]
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

installing manually not docker.

```
$ npm run setup

> uptime-kuma@ setup /code/uptime-kuma
> git checkout 1.0.0 && npm install && npm run build

Previous HEAD position was 0176857 add ability to change the listening port and hostname
HEAD is now at a1adfb9 minor fix
npm WARN vue-confirm-dialog@1.0.2 requires a peer of vue@^2.6.10 but none is installed. You must install peer dependencies yourself.
npm WARN uptime-kuma@1.0.0 No repository field.
npm WARN uptime-kuma@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

removed 1 package and audited 457 packages in 7.619s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


> uptime-kuma@1.0.0 build /code/uptime-kuma
> vite build

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/code/uptime-kuma/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:23:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uptime-kuma@1.0.0 build: `vite build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uptime-kuma@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2021-07-12T13_47_45_765Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uptime-kuma@ setup: `git checkout 1.0.0 && npm install && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uptime-kuma@ setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2021-07-12T13_47_45_782Z-debug.log
```

checking the debug log gives me :

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'setup' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle uptime-kuma@~presetup: uptime-kuma@
6 info lifecycle uptime-kuma@~setup: uptime-kuma@
7 verbose lifecycle uptime-kuma@~setup: unsafe-perm in lifecycle true
8 verbose lifecycle uptime-kuma@~setup: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/code/uptime-kuma/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle uptime-kuma@~setup: CWD: /code/uptime-kuma
10 silly lifecycle uptime-kuma@~setup: Args: [ '-c', 'git checkout 1.0.0 && npm install && npm run build' ]
11 silly lifecycle uptime-kuma@~setup: Returned: code: 1  signal: null
12 info lifecycle uptime-kuma@~setup: Failed to exec setup script
13 verbose stack Error: uptime-kuma@ setup: `git checkout 1.0.0 && npm install && npm run build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid uptime-kuma@
15 verbose cwd /code/uptime-kuma
16 verbose Linux 5.8.0-1031-oracle
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "setup"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error uptime-kuma@ setup: `git checkout 1.0.0 && npm install && npm run build`
22 error Exit status 1
23 error Failed at the uptime-kuma@ setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by TheGuyDanish** [comment]
`18 verbose node v10.19.0`

Uptime-Kuma requires node.js 14 or above.
