### ISSUE TITLE
Shrinking databse/Blocking database opreations Give False Downtime

### ISSUE THREAD

**Issue by JacksonChen666** [louislam/uptime-kuma#2470]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

One of my monitors said it was down because: `Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`

I was deleting a monitor, probably with a lot of data (i had history set for 365 previously. insane, i know), so deleting took a long time, which then caused the monitor being down.

The issue can also be caused by a manually triggered shrink database operation.

[Related](https://github.com/louislam/uptime-kuma/issues/2345)

### 👟 Reproduction steps

1. Have some monitors (any should be fine, just fast enough like at most 20 seconds)
2. Have a large database (say >512MB)
3. Shrink database (Settings > Monitor History > Shrink database)
4. Experience behavior

### 👀 Expected behavior

The monitors will continue as "up" and saving the correct data later (if needed).

### 😓 Actual Behavior

The monitors are considered "down" because a blocking database operation is happening.

### 🐻 Uptime-Kuma Version

1.19.0

### 💻 Operating System and Arch

macOS 13.1

### 🌐 Browser

LibreWolf 108.0.1-1

### 🟩 NodeJS Version

v16.18.1

### 📝 Relevant log output

```shell
Dec 25 12:36:43 laptop-server npm[1618271]: 2022-12-25T11:36:43Z [RATE-LIMIT] INFO: remaining requests: 20
Dec 25 12:37:06 laptop-server npm[1618271]: 2022-12-25T11:37:06Z [MONITOR] WARN: Monitor #6 'mastodon/mcrblgng (micro.)': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
| Max retries: 12 | Retry: 1 | Retry Interval: 60 seconds | Type: keyword
Dec 25 12:37:10 laptop-server npm[1618271]: 2022-12-25T11:37:10Z [MONITOR] WARN: Monitor #7 'peertube (videos.)': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max re
tries: 12 | Retry: 1 | Retry Interval: 30 seconds | Type: keyword
Dec 25 12:37:10 laptop-server npm[1618271]: 2022-12-25T11:37:10Z [MONITOR] WARN: Monitor #40 'conduit (conduit.hazmat.)': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
| Max retries: 15 | Retry: 1 | Retry Interval: 60 seconds | Type: keyword
Dec 25 12:37:11 laptop-server npm[1618271]: 2022-12-25T11:37:11Z [MONITOR] WARN: Monitor #36 'unbound DNS server (telemetry)': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) c
all? | Max retries: 2 | Retry: 1 | Retry Interval: 30 seconds | Type: keyword
Dec 25 12:37:12 laptop-server npm[1618271]: Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
Dec 25 12:37:12 laptop-server npm[1618271]:     at Client_SQLite3.acquireConnection (/home/uptime/uptime-kuma/node_modules/knex/lib/client.js:305:26)
Dec 25 12:37:12 laptop-server npm[1618271]:     at async Runner.ensureConnection (/home/uptime/uptime-kuma/node_modules/knex/lib/execution/runner.js:259:28)
Dec 25 12:37:12 laptop-server npm[1618271]:     at async Runner.run (/home/uptime/uptime-kuma/node_modules/knex/lib/execution/runner.js:30:19)
Dec 25 12:37:12 laptop-server npm[1618271]:     at async RedBeanNode.findOne (/home/uptime/uptime-kuma/node_modules/redbean-node/dist/redbean-node.js:515:19)
Dec 25 12:37:12 laptop-server npm[1618271]:     at async Function.handleStatusPageResponse (/home/uptime/uptime-kuma/server/model/status_page.js:23:26)
Dec 25 12:37:12 laptop-server npm[1618271]:     at async /home/uptime/uptime-kuma/server/routers/status-page-router.js:16:5 {
Dec 25 12:37:12 laptop-server npm[1618271]:   sql: undefined,
Dec 25 12:37:12 laptop-server npm[1618271]:   bindings: undefined
Dec 25 12:37:12 laptop-server npm[1618271]: }
Dec 25 12:37:12 laptop-server npm[1618271]:     at process.<anonymous> (/home/uptime/uptime-kuma/server/server.js:1779:13)
Dec 25 12:37:12 laptop-server npm[1618271]:     at process.emit (node:events:513:28)
Dec 25 12:37:12 laptop-server npm[1618271]:     at emit (node:internal/process/promises:140:20)
Dec 25 12:37:12 laptop-server npm[1618271]:     at processPromiseRejections (node:internal/process/promises:274:27)
Dec 25 12:37:12 laptop-server npm[1618271]:     at processTicksAndRejections (node:internal/process/task_queues:97:32)
Dec 25 12:37:13 laptop-server npm[1618271]: If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Dec 25 12:37:13 laptop-server npm[1618271]: 2022-12-25T11:37:13Z [MONITOR] WARN: Monitor #44 'prometheus (prometheus.)': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? |
 Max retries: 12 | Retry: 1 | Retry Interval: 60 seconds | Type: keyword
Dec 25 12:37:14 laptop-server npm[1618271]: 2022-12-25T11:37:14Z [AUTH] INFO: Successfully logged in user jackson. IP=176.241.52.131
Dec 25 12:37:15 laptop-server npm[1618271]: 2022-12-25T11:37:15Z [RATE-LIMIT] INFO: remaining requests: 20
Dec 25 12:37:19 laptop-server npm[1618271]: 2022-12-25T11:37:19Z [MONITOR] WARN: Monitor #34 'ntfy localhost': Failing: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Interval:
 20 seconds | Type: http | Down Count: 0 | Resend Interval: 15
Dec 25 12:37:43 laptop-server npm[1618271]: 2022-12-25T11:37:43Z [RATE-LIMIT] INFO: remaining requests: 20
```

**Comment by louislam** [comment]
Due to the limitation of SQLite, it may be a unsolvable bug.

Maybe I will change to MySQL in 2.0.0.

**Comment by JacksonChen666** [comment]
@louislam if you're considering supporting other databases, i would personally suggest considering postgresql and mysql and the pros/cons

i don't have mysql on my server, because nothing uses it. pretty much everything i run (peertube, mastodon, synapse (matrix homeserver)) are using postgres.

anyways, here's some already existing issues/comments:
- https://github.com/louislam/uptime-kuma/issues/1397#issuecomment-1336401894
- https://github.com/louislam/uptime-kuma/issues/959
- https://github.com/louislam/uptime-kuma/issues/953

**Comment by NeckBeardPrince** [comment]
Allowing an external database would be a great addition.

**Comment by kosssi** [comment]
I'm in the same configuration as @JacksonChen666.
I really hope that Uptime Kuma 2.0 will not be limited to MySQL and will be compatible with Postgres.
But given the ideas for version 2 on [your dashboard](https://github.com/users/louislam/projects/4/views/1), I'm afraid that's not the case.
Did you make a decision on it @louislam and if so could you explain why?

PS: Thank you very much for the creation and maintenance of this tool, I deploy it within the framework of [CHATONS](https://www.chatons.org/) in France.

**Comment by manuelkamp** [comment]
Is there an update on that issue? Or any workaround, for me after some months of flawless usage, it is now unusable, because for every action a lot of monitors shows wrong thins error as down.

**Comment by CommanderStorm** [comment]
@JacksonChen666 This will be resolved in the [`1.23`-release](https://github.com/louislam/uptime-kuma/milestone/34) given that https://github.com/louislam/uptime-kuma/pull/2800 and https://github.com/louislam/uptime-kuma/pull/3380 were merged.

**Comment by harryzcy** [comment]
MariaDB support is merged already. And I submitted Postgres support in #3748

**Comment by cypa** [comment]
maybe splitting out data over several db files would help to solve this?

as I see the big table is `heartbeat` and it's index `monitor_important_time_index` - it is the best way to store timeseries in sqlite? could we optimize the schema?
```
sqlite> .schema heartbeat
CREATE TABLE [heartbeat](
 [id] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
 [important] BOOLEAN NOT NULL DEFAULT 0,
 [monitor_id] INTEGER NOT NULL REFERENCES [monitor]([id]) ON DELETE CASCADE ON UPDATE CASCADE,
 [status] SMALLINT NOT NULL,
 [msg] TEXT,
 [time] DATETIME NOT NULL,
 [ping] INTEGER,
 [duration] INTEGER NOT NULL DEFAULT 0, down_count INTEGER default 0 not null);
CREATE INDEX [monitor_id] ON [heartbeat]([monitor_id]);
CREATE INDEX [important] ON [heartbeat]([important]);
CREATE INDEX monitor_time_index ON heartbeat (monitor_id, time);
CREATE INDEX monitor_important_time_index ON heartbeat (monitor_id, important,time);
sqlite> 
```

**Comment by CommanderStorm** [comment]
Please see the performance changes we are doing in `v2.0` => see https://github.com/louislam/uptime-kuma/issues/4500.
While optimising the indexies might also be a way, we have chosen to do aggregation instead.
The relevant PR here is https://github.com/louislam/uptime-kuma/pull/2750

=> deleting in smaller batches (i.e. allowing for other operations to sneak in) would be the way to resolve this issue.

**Comment by CommanderStorm** [comment]
Nevermind, I think this is already resolved in the [`1.23`-release](https://github.com/louislam/uptime-kuma/milestone/34) given that https://github.com/louislam/uptime-kuma/pull/2800 and https://github.com/louislam/uptime-kuma/pull/3380 were merged.

**Comment by Saibamen** [comment]
> I think this is already resolved in the [`1.23`-release](https://github.com/louislam/uptime-kuma/milestone/34) given that #2800 and #3380 were merged

@CommanderStorm: No. Today I read your comment here and click on Shrink database button. After few *minutes* I was able to see frontend page without backend-connection bug, list of monitors was still loading 2-4 minutes (I only have 53 Monitors) and after this, our Slack was spammed by DOWN messages for all Monitors. My Customer almost got **heart attack** because of this...

DB size before shrink: 860 MB
DB size after shrink: 838.4 MB
History data retention: 30 days (I changed it today from 90)
Kuma Version: 1.23.11

**Comment by CommanderStorm** [comment]
Yea, indeed shrinking is not the same as deleting monitors. Should have read more carefully, sorry about that

**Comment by Saibamen** [comment]
FYI: Today, after `clear-old-data` job (reminder: I was changed history retention from 90 to 30 days), my DB size changed from ~838.4 MB to 780.6 MB

And I wonder if this text is correct:
```
Trigger database VACUUM for SQLite. If your database is created after 1.10.0, AUTO_VACUUM is already enabled and this action is not needed.
```

But I checked changes in 1.10.0 ([here](https://github.com/louislam/uptime-kuma/releases/tag/1.10.0)), and `await R.exec("PRAGMA auto_vacuum = FULL");` was added in PR #794 for `connect()` function [here](https://github.com/louislam/uptime-kuma/blob/a9e319517a1b0737a5256ea6724a89b6cfb7c7b6/server/database.js#L117), so I think recreating database from scratch is not needed, because `AUTO_VACUUM` will be added right after starting backend (or after every Kuma version update).

Please correct me if I'm wrong

**Comment by chakflying** [comment]
The description is not entirely accurate, I don't remember exactly but there is some slight difference between a manually triggered `VACUUM` and `AUTO_VACUUM`. But I also don't know how to write a better description so it is how it is.

**Comment by Saibamen** [comment]
I've just checked database -> `PRAGMA auto_vacuum;` returns `2`, so this is set to `INCREMENTAL`, no need to recreate database file as you may think after reading this description under `Shrink Database` button.

**Comment by Saibamen** [comment]
> But I also don't know how to write a better description so it is how it is.

Maybe just this for now:

> Trigger database VACUUM for SQLite. AUTO_VACUUM is already enabled and this action is not needed in most cases.

----

OK, in documentation (https://www.sqlite.org/pragma.html#pragma_auto_vacuum) we have this:

> Auto-vacuum does not defragment the database nor repack individual database pages the way that the [VACUUM](https://www.sqlite.org/lang_vacuum.html) command does. In fact, because it moves pages around within the file, auto-vacuum can actually make fragmentation worse.

IMO, we can write:

> Trigger VACUUM for SQLite to defragment and repack database. Remember, AUTO_VACUUM is already enabled, but this does not defragment the database nor repack individual database pages.

or just:

> Trigger database VACUUM for SQLite. AUTO_VACUUM is already enabled but this does not defragment the database nor repack individual database pages the way that the VACUUM command does.

**Comment by Saibamen** [comment]
OK, I will create PR to change en.js for this - this night or tomorrow

**Comment by Saibamen** [comment]
Done in https://github.com/louislam/uptime-kuma/pull/4508

**Comment by jinnabaalu** [comment]
I also faced the same issue. This is because the max connections is hardcoded. 

**ERROR** 
```error
2025-11-27T13:02:39+05:30 [MONITOR] INFO: Try to restart the monitor
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_MySQL2.acquireConnection (/app/node_modules/knex/lib/client.js:332:26)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:545:9)
    at process.processTimers (node:internal/timers:519:7)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:305:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.findOne (/app/node_modules/redbean-node/dist/redbean-node.js:499:19)
    at async UptimeCalculator.getDailyStatBean (/app/server/uptime-calculator.js:380:20)
    at async UptimeCalculator.update (/app/server/uptime-calculator.js:296:29)
    at async beat (/app/server/model/monitor.js:979:32) {
  sql: undefined,
  bindings: undefined
}
    at safeBeat (/app/server/model/monitor.js:1021:25)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:545:9)
    at process.processTimers (node:internal/timers:519:7)
```

Fix is to update the dynamic variables :

```js
        const poolMin = parseInt(process.env.DB_CONNECTION_POOL_MIN) || 0;
        const poolMax = parseInt(process.env.DB_CONNECTION_POOL_MAX) || 10;
        const poolIdleTimeout = parseInt(process.env.DB_CONNECTION_POOL_IDLE_TIMEOUT) || 30000;
        const poolAcquireTimeout = parseInt(process.env.DB_CONNECTION_POOL_ACQUIRE_TIMEOUT) || acquireConnectionTimeout;

        let mariadbPoolConfig = {
            min: poolMin,
            max: poolMax,
            idleTimeoutMillis: poolIdleTimeout,
            acquireTimeoutMillis: poolAcquireTimeout,
            createTimeoutMillis: 30000,
            destroyTimeoutMillis: 5000,
            reapIntervalMillis: 1000,
            createRetryIntervalMillis: 200,
        };

        log.info("db", `MariaDB Pool Config - Min: ${poolMin}, Max: ${poolMax}, IdleTimeout: ${poolIdleTimeout}ms, AcquireTimeout: ${poolAcquireTimeout}ms`);
```

Need to merge this with 

```js
if (dbConfig.type.endsWith("mariadb")) {
            config.pool = {
                ...mariadbPoolConfig,
                afterCreate(conn, done) {
...........
````

This will resolve the issues, we can dynamically manage the max connections.
