### ISSUE TITLE
Connection to upstream failed: connection failure / RangeError: Invalid time zone specified: :/etc/localtime

### ISSUE THREAD

**Issue by dgtn-va** [louislam/uptime-kuma#2623]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

First period:
App installed according official procedure (see Reproduction steps) and working perfectly during 2 months with only one update. The described problem under Actual Behavior appeared after 2 months, without my or hoster intervention on the environment, so without update or params mod.

Second period:
After many tentatives of restore app with updates (I've been stuck for 20 days with this problem), I go to new clean install as detailed below. Always same problem even after, mods of NodeJS version, reloads,  new update of app, reinstalls...

### 👟 Reproduction steps

npm install npm -g
git clone https://github.com/louislam/uptime-kuma.git
cd uptime-kuma
npm run setup
(npm install pm2 -g)
pm2 start server/server.js --name uptime-kuma

### 👀 Expected behavior

Just that normaly works!

### 😓 Actual Behavior

Can't access to:
- / (old or new install)
- /dashboard/ (old or new install)
- /dashboard/<n> (old install)
- /status/my_public_page (old install)
- and all other routes tested...

Error: ![Front](https://zupimages.net/up/23/03/hknx.png)
My hoster say that not due at mod/issue of env, but that's a bug of the app...

![](https://zupimages.net/up/23/03/jfgn.png)
![](https://zupimages.net/up/23/03/z1xq.png)

### 🐻 Uptime-Kuma Version

1.19.4

### 💻 Operating System and Arch

Debian 10 x64

### 🌐 Browser

MFF 108.0.2 / Chromium 109.0.5414.88

### 🟩 NodeJS Version

Actually 16.19.0 (and many others tested: under v16 and v14)

### 📝 Relevant log output

```shell
RangeError: Invalid time zone specified: :/etc/localtime
    at new DateTimeFormat (<anonymous>)
    at /home/user/uptime-kuma/server/modules/dayjs/plugin/timezone.js:31:34
    at a (/home/user/uptime-kuma/server/modules/dayjs/plugin/timezone.js:42:14)
    at u (/home/user/uptime-kuma/server/modules/dayjs/plugin/timezone.js:46:21)
    at Function.o.tz (/home/user/uptime-kuma/server/modules/dayjs/plugin/timezone.js:92:21)
    at Logger.log (/home/user/uptime-kuma/src/util.js:111:25)
    at Logger.debug (/home/user/uptime-kuma/src/util.js:165:14)
    at Timeout._onTimeout (/home/user/uptime-kuma/server/settings.js:36:21)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
RangeError: Invalid time zone specified: :/etc/localtime
    at new DateTimeFormat (<anonymous>)
    at /home/user/uptime-kuma/server/modules/dayjs/plugin/timezone.js:31:34
    at a (/home/user/uptime-kuma/server/modules/dayjs/plugin/timezone.js:42:14)
    at u (/home/user/uptime-kuma/server/modules/dayjs/plugin/timezone.js:46:21)
    at Function.o.tz (/home/user/uptime-kuma/server/modules/dayjs/plugin/timezone.js:92:21)
    at Logger.log (/home/user/uptime-kuma/src/util.js:111:25)
    at Logger.debug (/home/user/uptime-kuma/src/util.js:165:14)
    at UptimeKumaServer.initAfterDatabaseReady (/home/user/uptime-kuma/server/uptime-kuma-server.js:94:13)
    at async /home/user/uptime-kuma/server/server.js:168:5
Trace: RangeError: Invalid time zone specified: :/etc/localtime
    at new DateTimeFormat (<anonymous>)
    at /home/user/uptime-kuma/server/modules/dayjs/plugin/timezone.js:31:34
    at a (/home/user/uptime-kuma/server/modules/dayjs/plugin/timezone.js:42:14)
    at u (/home/user/uptime-kuma/server/modules/dayjs/plugin/timezone.js:46:21)
    at Function.o.tz (/home/user/uptime-kuma/server/modules/dayjs/plugin/timezone.js:92:21)
    at Logger.log (/home/user/uptime-kuma/src/util.js:111:25)
    at Logger.debug (/home/user/uptime-kuma/src/util.js:165:14)
    at UptimeKumaServer.initAfterDatabaseReady (/home/user/uptime-kuma/server/uptime-kuma-server.js:94:13)
    at async /home/user/uptime-kuma/server/server.js:168:5
    at process.<anonymous> (/home/user/uptime-kuma/server/server.js:1780:13)
    at process.emit (node:events:525:35)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
```

**Comment by louislam** [comment]
> Invalid time zone specified: :/etc/localtime

You should check this file.

**Comment by louislam** [comment]
Wait, I think you put a wrong value into the `TZ`, it should be the name of timezone or you don't need to set.
`:/etc/localtime` is a wrong value.

**Comment by dgtn-va** [comment]
> 

First, thank you for quick answer :)
And yes, I identified this first. I thinked that's strange value and I talk about to my hoster. Its answer is: 

> The TZ environment variable is defined by tzset and must either take as its value the definition of a timezone, or be explicitly prefixed with : and followed by a filename. This is indeed the default value on our systems, and this value has not changed for years. If your app reads this environment variable expecting a timezone to be set, this is a bug.

Can change directly this env TZ variable with "Europe/Paris" or ":Europe/Paris" value? I don't really understand how to do this at read this https://man7.org/linux/man-pages/man3/tzset.3.html :(

Thank you.

**Comment by louislam** [comment]
> sudo timedatectl set-timezone America/New_York

If you want to set for Uptime Kuma, you could set in pm2:
https://pm2.keymetrics.io/docs/usage/environment/

**Comment by mymmrac** [comment]
@louislam Hi seems like a similar issue, but on the alpine image (v1.20.1), on standard image error does not occure

```
Trace: RangeError: Invalid time zone specified: Europe/Kyiv
    at new DateTimeFormat (<anonymous>)
    at /app/server/modules/dayjs/plugin/timezone.js:31:34
    at a (/app/server/modules/dayjs/plugin/timezone.js:42:14)
    at u (/app/server/modules/dayjs/plugin/timezone.js:46:21)
    at Function.o.tz (/app/server/modules/dayjs/plugin/timezone.js:92:21)
    at Logger.log (/app/src/util.js:111:25)
    at Logger.debug (/app/src/util.js:165:14)
    at UptimeKumaServer.initAfterDatabaseReady (/app/server/uptime-kuma-server.js:110:13)
    at async /app/server/server.js:172:5
    at process.<anonymous> (/app/server/server.js:1794:13)
    at process.emit (node:events:390:28)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
/app/server/modules/dayjs/plugin/timezone.js:31
                return r || (r = new Intl.DateTimeFormat("en-US", {
                                 ^

RangeError: Invalid time zone specified: Europe/Kyiv
    at new DateTimeFormat (<anonymous>)
    at /app/server/modules/dayjs/plugin/timezone.js:31:34
    at a (/app/server/modules/dayjs/plugin/timezone.js:42:14)
    at u (/app/server/modules/dayjs/plugin/timezone.js:46:21)
    at Function.o.tz (/app/server/modules/dayjs/plugin/timezone.js:92:21)
    at Logger.log (/app/src/util.js:111:25)
    at Logger.debug (/app/src/util.js:165:14)
    at Timeout._onTimeout (/app/server/settings.js:36:21)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

```

**Comment by louislam** [comment]
@mymmrac Should be `Europe/Kiev` instead of `Kyiv`?

**Comment by mymmrac** [comment]
Actually no, `Kyiv` is the correct one, this was changed last year (ref https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#KYIV). Most software now should treat `Europe/Kiev` as alias to `Europe/Kyiv` and `Europe/Kyiv`  as default time zone in Ukraine.

ICANN reference (`Rename Europe/Kiev to Europe/Kyiv.`): https://mm.icann.org/pipermail/tz-announce/2022-August/000071.html

Note: Kiev is russian pronunciation of Ukrainian city Kyiv

**Comment by louislam** [comment]
My guess is Alpine 3.12 is end-of-life and no longer updated. 

https://endoflife.date/alpine

As Alpine >= 3.13 is not able to run on Pi4, I can't update. The best way should be sticking to Debian based Uptime Kuma.

**Comment by mymmrac** [comment]
Yep, this what I did, thanks for investigation

**Comment by ahmedhosnypro** [comment]
# RangeError: Invalid Time Zone Specified (Etc/Unknown) - JavaScript Timezone Detection Failure

## Problem
This error occurs when JavaScript fails to automatically detect the browser's timezone.

## Error Message
```
RangeError: Invalid time zone specified: Etc/Unknown
    at Date.toLocaleString (<anonymous>)
```

## Common Causes
- Misconfigured system timezone
- Incomplete browser timezone database
- Virtual machine or containerized environment limitations

## Solution

### System Timezone Configuration
```bash
sudo ln -sf /usr/share/zoneinfo/Africa/Cairo /etc/localtime
```

### Verify Current Timezone
```bash
date
timedatectl
```

## Timezone Examples
- `Africa/Cairo`
- `Asia/Riyadh`
- `Europe/London`
- `America/New_York`
- `UTC`

## JavaScript Debugging
```javascript
// Detect and log current timezone
try {
  const userTimezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  console.log('Detected Timezone:', userTimezone);
} catch (error) {
  console.warn('Timezone detection failed');
}
```

## Recommended Steps
1. Check system timezone settings
2. Ensure browser's regional settings are correct
3. Use a timezone selection dropdown in your application
4. Consider using robust timezone libraries like `moment-timezone`
