### ISSUE TITLE
Mikrotik container. KnexTimeoutError: Knex: Timeout acquiring a connection.

### ISSUE THREAD

**Issue by evgn88** [louislam/uptime-kuma#2640]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

```
[2023-01-11 03:41:05] KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:305:26)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:259:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.find (/app/node_modules/redbean-node/dist/redbean-node.js:483:24)
    at async Timeout.generateMaintenanceTimeslots [as _onTimeout] (/app/server/uptime-kuma-server.js:229:20) {
  sql: undefined,
  bindings: undefined
}
[2023-01-11 03:42:09] KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:305:26)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:259:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:588:22)
    at async Function.getNotificationList (/app/server/model/monitor.js:1113:32)
    at async Function.sendNotification (/app/server/model/monitor.js:1079:38)
    at async beat (/app/server/model/monitor.js:660:21) {
  sql: 'SELECT notification.* FROM notification, monitor_notification WHERE monitor_id = ? AND monitor_notification.notification_id = notification.id ',
  bindings: [ 7 ]
```

### 👟 Reproduction steps

the application stops working at about 03:00-04:00 AM local time. The previous version had the same problem.

### 👀 Expected behavior

to work without errors?

### 😓 Actual Behavior

to work without errors?

### 🐻 Uptime-Kuma Version

1.19.5

### 💻 Operating System and Arch

RouterOS v7.7 arm32

### 🌐 Browser

Vivaldi	5.6.2867.58

### 🐋 Docker Version

unquestionably

### 🟩 NodeJS Version

16.19.0

### 📝 Relevant log output

```shell
[2023-01-11 03:41:05] KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:305:26)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:259:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.find (/app/node_modules/redbean-node/dist/redbean-node.js:483:24)
    at async Timeout.generateMaintenanceTimeslots [as _onTimeout] (/app/server/uptime-kuma-server.js:229:20) {
  sql: undefined,
  bindings: undefined
}
[2023-01-11 03:42:09] KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:305:26)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:259:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:588:22)
    at async Function.getNotificationList (/app/server/model/monitor.js:1113:32)
    at async Function.sendNotification (/app/server/model/monitor.js:1079:38)
    at async beat (/app/server/model/monitor.js:660:21) {
  sql: 'SELECT notification.* FROM notification, monitor_notification WHERE monitor_id = ? AND monitor_notification.notification_id = notification.id ',
  bindings: [ 7 ]
```

**Comment by louislam** [comment]
Duplicate of #2346
