### ISSUE TITLE
Errors after using NCU to update dependencies

### ISSUE THREAD

**Issue by simone80an** [louislam/uptime-kuma#2683]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello, i used ncu (npm-check-updates) to upgrade uptime-kuma package.json dependencies to the latest versions.
All went fine but when i restarted the app using pm2 i checked the logs and i have these errors:

```
3|uptime-kuma-test  | Welcome to Uptime Kuma
3|uptime-kuma-test  | Your Node.js version: 16
3|uptime-kuma-test  | 2023-01-26T11:57:15+01:00 [SERVER] INFO: Welcome to Uptime Kuma
3|uptime-kuma-test  | 2023-01-26T11:57:15+01:00 [SERVER] INFO: Node Env: production
3|uptime-kuma-test  | 2023-01-26T11:57:15+01:00 [SERVER] INFO: Importing Node libraries
3|uptime-kuma-test  | 2023-01-26T11:57:15+01:00 [SERVER] INFO: Importing 3rd-party libraries
3|uptime-kuma-test  | Error [ERR_REQUIRE_ESM]: require() of ES Module C:\uptime-kuma-test\node_modules\cacheable-lookup\source\index.js from C:\uptime-kuma-test\server\cacheable-dns-http-agent.js not supported.
3|uptime-kuma-test  | Instead change the require of index.js in C:\uptime-kuma-test\server\cacheable-dns-http-agent.js to a dynamic import() which is available in all CommonJS modules.
3|uptime-kuma-test  |     at Module.Hook._require.Module.require (C:\ProgramData\npm\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:101:39)
3|uptime-kuma-test  |     at Object.<anonymous> (C:\uptime-kuma-test\server\cacheable-dns-http-agent.js:3:25)
3|uptime-kuma-test  |     at Module.Hook._require.Module.require (C:\ProgramData\npm\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:101:39)
3|uptime-kuma-test  |     at Object.<anonymous> (C:\uptime-kuma-test\server\uptime-kuma-server.js:10:35)
3|uptime-kuma-test  |     at Module.Hook._require.Module.require (C:\ProgramData\npm\npm\node_modules\pm2\node_modules\require-in-the-middle\index.js:101:39)
3|uptime-kuma-test  |     at Object.<anonymous> (C:\uptime-kuma-test\server\server.js:62:30)
3|uptime-kuma-test  |     at Object.<anonymous> (C:\ProgramData\npm\npm\node_modules\pm2\lib\ProcessContainerFork.js:33:23) {
3|uptime-kuma-test  |   code: 'ERR_REQUIRE_ESM'
3|uptime-kuma-test  | }
PM2                 | App [uptime-kuma-test:3] exited with code [1] via signal [SIGINT]
PM2                 | App [uptime-kuma-test:3] starting in -fork mode-
PM2                 | App [uptime-kuma-test:3] online
```

How can i fix it?
Thanks.

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

Windows Server 2019

### 🌐 Browser

Google Chrome 108.0.5359.125

### 🟩 NodeJS Version

16.14.2

**Comment by louislam** [comment]
> i used ncu (npm-check-updates) 

Don't use ncu, it is not for end users.

You should backup the `./data` directory and follow the readme or wiki here to install/update.
