### ISSUE TITLE
Slowness with 100% CPU utilization

### ISSUE THREAD

**Issue by AyhamZz** [louislam/uptime-kuma#2889]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

I noticed a huge slowness on my Uptime Kuma monitor and noticed that the CPU utilization is 100%, after increasing the CPU cores it still hits 100%, check the following screenshots:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/127086952/223050035-04d9b482-df57-47e6-8b0e-3f15a1dcf445.png">

and found the following Docker logs

<img width="599" alt="image" src="https://user-images.githubusercontent.com/127086952/223050141-9b7eba04-9b5d-407a-9ec8-a37fed69cbf3.png">

am using Ubuntu 22.04 LTS
<img width="245" alt="image" src="https://user-images.githubusercontent.com/127086952/223050567-e21181f3-bf15-48b8-825d-df983612693d.png">

with the following docker version
 
<img width="314" alt="image" src="https://user-images.githubusercontent.com/127086952/223050670-5fa17a91-f43c-4b4d-8aea-eff070d2dd92.png">

Uptime kuma is on the latest version and i tried restarting both docker and server
<img width="174" alt="image" src="https://user-images.githubusercontent.com/127086952/223050980-91346d70-ec0a-4176-b4ae-e46ca34e0488.png">

### 👀 Expected behavior

CPU utilization caused by "node" might be the main reason of the slowness.

### 😓 Actual Behavior

Slowness

### 🐻 Uptime-Kuma Version

1.20.2

### 💻 Operating System and Arch

Ubunto 22.04 LTS

### 🌐 Browser

Google Chrome Version 110.0.5481.178

### 🐋 Docker Version

20.10.12

### 📝 Relevant log output

```shell
Trace: Error: aborted
    at PendingOperation.abort (/app/node_modules/tarn/dist/PendingOperation.js:25:21)
    at /app/node_modules/tarn/dist/Pool.js:208:25
    at Array.map (<anonymous>)
    at /app/node_modules/tarn/dist/Pool.js:207:53
    at async Client_SQLite3.destroy (/app/node_modules/knex/lib/client.js:338:9)
    at async RedBeanNode.close (/app/node_modules/redbean-node/dist/redbean-node.js:375:9)
    at async Function.close (/app/server/database.js:435:13)
    at async Object.shutdownFunction [as onShutdown] (/app/server/server.js:1771:5)
    at process.<anonymous> (/app/server/server.js:1794:13)
    at process.emit (node:events:525:35)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: Error: aborted
    at PendingOperation.abort (/app/node_modules/tarn/dist/PendingOperation.js:25:21)
    at /app/node_modules/tarn/dist/Pool.js:208:25
    at Array.map (<anonymous>)
    at /app/node_modules/tarn/dist/Pool.js:207:53
    at async Client_SQLite3.destroy (/app/node_modules/knex/lib/client.js:338:9)
    at async RedBeanNode.close (/app/node_modules/redbean-node/dist/redbean-node.js:375:9)
    at async Function.close (/app/server/database.js:435:13)
    at async Object.shutdownFunction [as onShutdown] (/app/server/server.js:1771:5)
    at process.<anonymous> (/app/server/server.js:1794:13)
    at process.emit (node:events:525:35)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: Error: aborted
    at PendingOperation.abort (/app/node_modules/tarn/dist/PendingOperation.js:25:21)
    at /app/node_modules/tarn/dist/Pool.js:208:25
    at Array.map (<anonymous>)
    at /app/node_modules/tarn/dist/Pool.js:207:53
    at async Client_SQLite3.destroy (/app/node_modules/knex/lib/client.js:338:9)
    at async RedBeanNode.close (/app/node_modules/redbean-node/dist/redbean-node.js:375:9)
    at async Function.close (/app/server/database.js:435:13)
    at async Object.shutdownFunction [as onShutdown] (/app/server/server.js:1771:5)
    at process.<anonymous> (/app/server/server.js:1794:13)
    at process.emit (node:events:525:35)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: Error: aborted
    at PendingOperation.abort (/app/node_modules/tarn/dist/PendingOperation.js:25:21)
    at /app/node_modules/tarn/dist/Pool.js:208:25
    at Array.map (<anonymous>)
    at /app/node_modules/tarn/dist/Pool.js:207:53
    at async Client_SQLite3.destroy (/app/node_modules/knex/lib/client.js:338:9)
    at async RedBeanNode.close (/app/node_modules/redbean-node/dist/redbean-node.js:375:9)
    at async Function.close (/app/server/database.js:435:13)
    at async Object.shutdownFunction [as onShutdown] (/app/server/server.js:1771:5)
    at process.<anonymous> (/app/server/server.js:1794:13)
    at process.emit (node:events:525:35)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: Error: aborted
    at PendingOperation.abort (/app/node_modules/tarn/dist/PendingOperation.js:25:21)
    at /app/node_modules/tarn/dist/Pool.js:208:25
    at Array.map (<anonymous>)
    at /app/node_modules/tarn/dist/Pool.js:207:53
    at async Client_SQLite3.destroy (/app/node_modules/knex/lib/client.js:338:9)
    at async RedBeanNode.close (/app/node_modules/redbean-node/dist/redbean-node.js:375:9)
    at async Function.close (/app/server/database.js:435:13)
    at async Object.shutdownFunction [as onShutdown] (/app/server/server.js:1771:5)
    at process.<anonymous> (/app/server/server.js:1794:13)
    at process.emit (node:events:525:35)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: Error: aborted
    at PendingOperation.abort (/app/node_modules/tarn/dist/PendingOperation.js:25:21)
    at /app/node_modules/tarn/dist/Pool.js:208:25
    at Array.map (<anonymous>)
    at /app/node_modules/tarn/dist/Pool.js:207:53
    at async Client_SQLite3.destroy (/app/node_modules/knex/lib/client.js:338:9)
    at async RedBeanNode.close (/app/node_modules/redbean-node/dist/redbean-node.js:375:9)
    at async Function.close (/app/server/database.js:435:13)
    at async Object.shutdownFunction [as onShutdown] (/app/server/server.js:1771:5)
    at process.<anonymous> (/app/server/server.js:1794:13)
    at process.emit (node:events:525:35)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: Error: aborted
    at PendingOperation.abort (/app/node_modules/tarn/dist/PendingOperation.js:25:21)
    at /app/node_modules/tarn/dist/Pool.js:208:25
    at Array.map (<anonymous>)
    at /app/node_modules/tarn/dist/Pool.js:207:53
    at async Client_SQLite3.destroy (/app/node_modules/knex/lib/client.js:338:9)
    at async RedBeanNode.close (/app/node_modules/redbean-node/dist/redbean-node.js:375:9)
    at async Function.close (/app/server/database.js:435:13)
    at async Object.shutdownFunction [as onShutdown] (/app/server/server.js:1771:5)
    at process.<anonymous> (/app/server/server.js:1794:13)
    at process.emit (node:events:525:35)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: Error: aborted
    at PendingOperation.abort (/app/node_modules/tarn/dist/PendingOperation.js:25:21)
    at /app/node_modules/tarn/dist/Pool.js:208:25
    at Array.map (<anonymous>)
    at /app/node_modules/tarn/dist/Pool.js:207:53
    at async Client_SQLite3.destroy (/app/node_modules/knex/lib/client.js:338:9)
    at async RedBeanNode.close (/app/node_modules/redbean-node/dist/redbean-node.js:375:9)
    at async Function.close (/app/server/database.js:435:13)
    at async Object.shutdownFunction [as onShutdown] (/app/server/server.js:1771:5)
    at process.<anonymous> (/app/server/server.js:1794:13)
    at process.emit (node:events:525:35)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
```

**Comment by louislam** [comment]
Do you have a recurring maintenance?

**Comment by AyhamZz** [comment]
> 

Not really

**Comment by webartifex** [comment]
I can confirm @AyhamZz 's observations.

For the past couple of days, Uptime is very, very slow.

For example, when you open it, it takes up to a minute until the monitors are shown.

I do have a recurring maintenance windows. Yet, there were no issues when I set it up about 3-4 weeks ago. Must be a more recent version that causes the problems.

I run Uptime as a Docker container on an Ubuntu 22.04 LTS VM.

Since I am not really envolved on a technical level with your (great) project, @louislam , maybe you tell me how I can contribute to find and fix this bug.

**Comment by webartifex** [comment]
@louislam 

I will try that out, disabling maintenance windows.

However, I have to admit that they are quite a useful feature.

I just found that my local SQLite with all the history was about 2 GB, even though I only monitor the last 7 days with about 50 monitors. Seems to confirm your finding that "it will keep generating time slots endlessly".

**Comment by webartifex** [comment]
@louislam 

UPDATE: Disabling the maintenance windows works.

Also: Whoever faces the same issue, maybe take a look at the kuma.db file. Some tables may need to be emptied.

**Comment by AyhamZz** [comment]
@louislam 

Thank you for your response, regarding the maintenance window I didn't use it until now, but it is worth mentioning that the issue just disappears whenever I clear the logs and export the backup file then import it again using overwrite.

I have a good resources attached to my VM
<img width="217" alt="image" src="https://user-images.githubusercontent.com/127086952/224619395-3649df01-3a0a-46f2-9998-9e22616c472c.png">

But for now, it is stable after what I mentioned, thank you again.

**Comment by louislam** [comment]
@webartifex It should be fixed in 1.21.0-beta.1, feel free to try if you don't mind to use a beta version.

 https://github.com/louislam/uptime-kuma/releases/tag/1.21.0-beta.1

**Comment by petercharleston** [comment]
Hi Louis,

I really like your product.

We have run into the same issues with CPU 100+ for the node command.

I deleted the MX schedules and also upgraded to 1.21.2

Still having very slow or not loading UI.

Adding or editing monitors is very very slow.

we have about 3530 monitors running and I doubled the VM spec today to 32GB RAM and 8Vcpu's which did not make a differrence.

DB size is 2234 MB
I set the monitor history to 7 days, it was on 180 days.

Any advise please?
![image](https://user-images.githubusercontent.com/44698386/230065324-c197e7bc-ecbe-4a24-a962-ee89bd173270.png)

![image](https://user-images.githubusercontent.com/44698386/230065440-5bc7c223-091f-4719-b11c-5e364e4d6a84.png)

**Comment by petercharleston** [comment]
update.

Followed advise from [AyhamZz](https://github.com/AyhamZz)

export the backup file then import it again using overwrite.

we lost our status pages but this fixed the issue and shrank the DB very low from 2GB

**Comment by louislam** [comment]
> Hi Louis,
> 
> I really like your product.
> 
> We have run into the same issues with CPU 100+ for the node command.
> 
> I deleted the MX schedules and also upgraded to 1.21.2
> 
> Still having very slow or not loading UI.
> 
> Adding or editing monitors is very very slow.
> 
> we have about 3530 monitors running and I doubled the VM spec today to 32GB RAM and 8Vcpu's which did not make a differrence.
> 
> DB size is 2234 MB I set the monitor history to 7 days, it was on 180 days.
> 
> Any advise please? ![image](https://user-images.githubusercontent.com/44698386/230065324-c197e7bc-ecbe-4a24-a962-ee89bd173270.png)
> 
> ![image](https://user-images.githubusercontent.com/44698386/230065440-5bc7c223-091f-4719-b11c-5e364e4d6a84.png)

Unfortunately, 3530 monitors right now is too many for Uptime Kuma.

**Comment by petercharleston** [comment]
> 
sorry that was meant to be 350 monitors.
All working fine now thanks

**Comment by j-f1** [comment]
If other people run into these sorts of issues, you may be able to help by defining the environment variable `NODE_OPTIONS` with the value `--cpu-prof --diagnostic-dir=/app/data`. If you run Uptime Kuma for a short time and reproduce the slowness then exit it gracefully, the `.cpuprofile` file created in the data directory will provide detailed information about what was going on when it was running slowly.

**Comment by Zandor300** [comment]
@louislam

Running uptime-kuma 1.21.3.

Experiencing the same slowness on my instance with ~90 monitors, only ping, http and push monitor types.

My db is 5 GB according to the UI and history was on 180 days. Changed it to 30 days but don't know when it will start removing old history?

@j-f1 Tried adding your `NODE_OPTIONS` to the Docker container but it spat out the following:

```
-v /root/uptime-kuma-prof:/app/data-prof \
--env NODE_OPTIONS="--cpu-prof --diagnostic-dir=/app/data-prof"
```

```
node: --cpu-prof is not allowed in NODE_OPTIONS
```
