### ISSUE TITLE
MariaDB monitor crash

### ISSUE THREAD

**Issue by genpas** [louislam/uptime-kuma#2968]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When I add a MySQL/MariaDB monitor, the server crashes.
This problem occurs with and without docker.

### 👟 Reproduction steps

Just add a MySQL/MariaDB monitor.
The monitored service is MariaDB (10.3.25-MariaDB-0+deb10u1-log - Debian 10) on a custom port.

### 👀 Expected behavior

Normal operation

### 😓 Actual Behavior

Error and crash

### 🐻 Uptime-Kuma Version

1.21.0

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Chrome

### 🐋 Docker Version

Docker 23.0.1

### 🟩 NodeJS Version

19.8.1

### 📝 Relevant log output

```shell
root@monitor:~/uptime-kuma# node server/server.js
Welcome to Uptime Kuma
Your Node.js version: 19
2023-03-23T15:34:17+01:00 [SERVER] INFO: Welcome to Uptime Kuma
2023-03-23T15:34:17+01:00 [SERVER] INFO: Node Env: production
2023-03-23T15:34:17+01:00 [SERVER] INFO: Importing Node libraries
2023-03-23T15:34:17+01:00 [SERVER] INFO: Importing 3rd-party libraries
2023-03-23T15:34:18+01:00 [SERVER] INFO: Creating express and socket.io instance
2023-03-23T15:34:18+01:00 [SERVER] INFO: Server Type: HTTP
2023-03-23T15:34:18+01:00 [SERVER] INFO: Importing this project modules
2023-03-23T15:34:18+01:00 [NOTIFICATION] INFO: Prepare Notification Providers
2023-03-23T15:34:18+01:00 [SERVER] INFO: Version: 1.21.0
2023-03-23T15:34:18+01:00 [DB] INFO: Data Dir: ./data/
2023-03-23T15:34:18+01:00 [SERVER] INFO: Connecting to the Database
2023-03-23T15:34:18+01:00 [DB] INFO: SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
2023-03-23T15:34:18+01:00 [DB] INFO: SQLite Version: 3.39.4
2023-03-23T15:34:18+01:00 [SERVER] INFO: Connected
2023-03-23T15:34:18+01:00 [DB] INFO: Your database version: 10
2023-03-23T15:34:18+01:00 [DB] INFO: Latest database version: 10
2023-03-23T15:34:18+01:00 [DB] INFO: Database patch not needed
2023-03-23T15:34:18+01:00 [DB] INFO: Database Patch 2.0 Process
2023-03-23T15:34:18+01:00 [SERVER] INFO: Load JWT secret from database.
2023-03-23T15:34:19+01:00 [SERVER] INFO: Adding route
2023-03-23T15:34:19+01:00 [SERVER] INFO: Adding socket handler
2023-03-23T15:34:19+01:00 [SERVER] INFO: Init the server
2023-03-23T15:34:19+01:00 [SERVER] INFO: Listening on 3001
2023-03-23T15:34:19+01:00 [MONITOR] WARN: Monitor #1 'MariaDB - db101': Failing: Cannot read properties of null (reading 'constructor') | Interval: 60 seconds | Type: mysql | Down Count: 0 | Resend Interval: 0
node:events:490
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new NodeError (node:internal/errors:399:5)
    at _write (node:internal/streams/writable:322:11)
    at Writable.write (node:internal/streams/writable:337:10)
    at Connection.write (/root/uptime-kuma/node_modules/mysql2/lib/connection.js:245:32)
    at Connection.writePacket (/root/uptime-kuma/node_modules/mysql2/lib/connection.js:294:12)
    at ClientHandshake.sendCredentials (/root/uptime-kuma/node_modules/mysql2/lib/commands/client_handshake.js:69:16)
    at ClientHandshake.handshakeInit (/root/uptime-kuma/node_modules/mysql2/lib/commands/client_handshake.js:142:12)
    at ClientHandshake.execute (/root/uptime-kuma/node_modules/mysql2/lib/commands/command.js:45:22)
    at Connection.handlePacket (/root/uptime-kuma/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/root/uptime-kuma/node_modules/mysql2/lib/connection.js:85:12)
Emitted 'error' event on Connection instance at:
    at Connection._notifyError (/root/uptime-kuma/node_modules/mysql2/lib/connection.js:236:12)
    at Connection._handleFatalError (/root/uptime-kuma/node_modules/mysql2/lib/connection.js:167:10)
    at Connection._handleNetworkError (/root/uptime-kuma/node_modules/mysql2/lib/connection.js:180:10)
    at /root/uptime-kuma/node_modules/mysql2/lib/connection.js:247:14
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END',
  fatal: true
}

Node.js v19.8.1
```

**Comment by clarkhacks** [comment]
Same error here. I was adding a PostgresDB when it happened.

**Comment by clarkhacks** [comment]
@genpas If you need a workaround I found that editing the kuma.db directly to remove the monitor in the `monitors` table worked to get me back online without having to reenter all my previous monitors.

If you're unfamiliar with SQLite I can recommend a simple webtool like http://www.sqliteonline.net/ to handle it for you.

**Comment by louislam** [comment]
@genpas Maybe due to this #2729. 

Someone in the node-mysql2 repo also asked similar question: https://github.com/sidorares/node-mysql2/issues/1282


@clarkhacks Please open a new issue with error log

**Comment by louislam** [comment]
I think it is fixed. But since I cannot reproduce the issue in my side, could you please test this with this docker image: `louislam/uptime-kuma:nightly`

Switch back to `1` after finished the test, as `nightly` is for development purpose only.

**Comment by genpas** [comment]
Thanks @louislam, it's ok for me now with this nightly build image.

**Comment by Mahoo12138** [comment]
```
2023-03-30T23:26:02+08:00 [SERVER] INFO: Version: 1.21.1
2023-03-30T23:26:03+08:00 [DB] INFO: Data Dir: ./data/
2023-03-30T23:26:03+08:00 [SERVER] INFO: Connecting to the Database
2023-03-30T23:26:03+08:00 [DB] INFO: SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
2023-03-30T23:26:03+08:00 [DB] INFO: SQLite Version: 3.41.1
2023-03-30T23:26:03+08:00 [SERVER] INFO: Connected
2023-03-30T23:26:03+08:00 [DB] INFO: Your database version: 10
2023-03-30T23:26:03+08:00 [DB] INFO: Latest database version: 10
2023-03-30T23:26:03+08:00 [DB] INFO: Database patch not needed
2023-03-30T23:26:03+08:00 [DB] INFO: Database Patch 2.0 Process
2023-03-30T23:26:04+08:00 [SERVER] INFO: Load JWT secret from database.
2023-03-30T23:26:04+08:00 [SERVER] INFO: Adding route
2023-03-30T23:26:04+08:00 [SERVER] INFO: Adding socket handler
2023-03-30T23:26:04+08:00 [SERVER] INFO: Init the server
2023-03-30T23:26:04+08:00 [SERVER] INFO: Listening on 3001
2023-03-30T23:26:05+08:00 [MONITOR] WARN: Monitor #2 'MySQL': Failing: Cannot read properties of null (reading 'constructor') | Interval: 120 seconds | Type: mysql | Down Count: 0 | Resend Interval: 0
```
