### ISSUE TITLE
nmp build error v.1.5.0

### ISSUE THREAD

**Issue by R0GGER** [louislam/uptime-kuma#297]
**Is it a duplicate question?**
No.

**Info**
Uptime Kuma Version: 1.5.0
Using Docker?: No
OS: Debian 10
Browser: Chrome

**Command:**
root@uptime:/opt/uptime-kuma# npm install --legacy-peer-deps

**Error**
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> @louislam/better-sqlite3-with-prebuilds@7.4.3 install /opt/uptime-kuma/node_modules/@louislam/better-sqlite3-with-prebuilds
> prebuild-install || npm run build-release

prebuild-install WARN install /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/uptime-kuma/node_modules/@louislam/better-sqlite3-with-prebuilds/build/Release/better_sqlite3.node)

> @louislam/better-sqlite3-with-prebuilds@7.4.3 build-release /opt/uptime-kuma/node_modules/@louislam/better-sqlite3-with-prebuilds
> node-gyp rebuild --release

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:192:21)
gyp ERR! System Linux 5.11.22-3-pve
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /opt/uptime-kuma/node_modules/@louislam/better-sqlite3-with-prebuilds
gyp ERR! node -v v14.17.5
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @louislam/better-sqlite3-with-prebuilds@7.4.3 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @louislam/better-sqlite3-with-prebuilds@7.4.3 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-31T19_32_58_252Z-debug.log
npm WARN chartjs-adapter-dayjs@1.0.0 requires a peer of chart.js@>= 2.8.0 < 3 but none is installed. You must install peer dependencies yourself.
npm WARN vue-confirm-dialog@1.0.2 requires a peer of vue@^2.6.10 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @louislam/better-sqlite3-with-prebuilds@7.4.3 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @louislam/better-sqlite3-with-prebuilds@7.4.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-31T19_32_58_479Z-debug.log
```

**Comment by Ponkhy** [comment]
Hey, since it can't find the command `make`, i'll assume you need to install the build-essential.
You can use this command to install it `apt-get install build-essential`

**Comment by R0GGER** [comment]
Oops! Thanks!
