### ISSUE TITLE
Error when trying to update without docker

### ISSUE THREAD

**Issue by oezh** [louislam/uptime-kuma#298]
**Is it a duplicate question?**
Please search in Issues without filters: https://github.com/louislam/uptime-kuma/issues?q=

**Info**
Uptime Kuma Version: 1.5.0
Using Docker?: No
OS: Debian 10
Browser: Brave

I got this error when trying to update:

```
npm run build

> uptime-kuma@1.5.0 build /opt/uptime-kuma
> vite build

/opt/uptime-kuma/node_modules/esbuild/bin/esbuild:2
throw new Error(`esbuild: Failed to install correctly
^

Error: esbuild: Failed to install correctly

Make sure you don't have "ignore-scripts" set to true. You can check this with
"npm config get ignore-scripts". If that returns true you can reset it back to
false using "npm config set ignore-scripts false" and then reinstall esbuild.

If you're using npm v7, make sure your package-lock.json file contains either
"lockfileVersion": 1 or the code "hasInstallScript": true. If it doesn't have
either of those, then it is likely the case that a known bug in npm v7 has
corrupted your package-lock.json file. Regenerating your package-lock.json file
should fix this issue.

    at Object.<anonymous> (/opt/uptime-kuma/node_modules/esbuild/bin/esbuild:2:7)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
failed to load config from /opt/uptime-kuma/vite.config.js
error during build:
Error: The service was stopped
    at /opt/uptime-kuma/node_modules/esbuild/lib/main.js:1217:25
    at /opt/uptime-kuma/node_modules/esbuild/lib/main.js:609:9
    at Socket.afterClose (/opt/uptime-kuma/node_modules/esbuild/lib/main.js:587:7)
    at Socket.emit (events.js:412:35)
    at Socket.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uptime-kuma@1.5.0 build: `vite build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uptime-kuma@1.5.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-31T21_02_12_599Z-debug.log
```
Already checked: ignore-scripts = false

Here is:
[/root/.npm/_logs/2021-08-31T21_02_12_599Z-debug.log](https://pastebin.com/97X53s2y)

After that, I restarted with `pm2 restart uptime-kuma` and it restarted succesfully BUT now the frontend takes some more time to load (like 30 seconds) than before

What can I do?

**Comment by Ponkhy** [comment]
Yea i also already noticed it's a bit slower, for me the frontend loads quick but it takes longer to get the heartbeats out of the database.

**Comment by louislam** [comment]
You could try to delete package-lock.json and node_modules, and run `npm install && npm run build` again
