### ISSUE TITLE
Just updated docker container on unraid - nightly release - got Error: Connection terminated due to connection timeout

### ISSUE THREAD

**Issue by vw-kombi** [louislam/uptime-kuma#3004]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

log states this- 

==> Performing startup jobs and maintenance tasks
==> Starting application with user 99 group 100
Welcome to Uptime Kuma
Your Node.js version: 16

2023-03-31T10:14:40+10:00 [SERVER] INFO: Welcome to Uptime Kuma
2023-03-31T10:14:40+10:00 [SERVER] INFO: Node Env: production
2023-03-31T10:14:40+10:00 [SERVER] INFO: Importing Node libraries
2023-03-31T10:14:40+10:00 [SERVER] INFO: Importing 3rd-party libraries
2023-03-31T10:14:41+10:00 [SERVER] INFO: Creating express and socket.io instance
2023-03-31T10:14:41+10:00 [SERVER] INFO: Server Type: HTTP
2023-03-31T10:14:41+10:00 [SERVER] INFO: Importing this project modules
2023-03-31T10:14:41+10:00 [NOTIFICATION] INFO: Prepare Notification Providers
2023-03-31T10:14:42+10:00 [SERVER] INFO: Version: 1.21.1-nightly-20230329043034

2023-03-31T10:14:42+10:00 [DB] INFO: Data Dir: ./data/
2023-03-31T10:14:42+10:00 [SERVER] INFO: Connecting to the Database
2023-03-31T10:14:42+10:00 [DB] INFO: SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
2023-03-31T10:14:42+10:00 [DB] INFO: SQLite Version: 3.41.1

Trace: Error: Connection terminated due to connection timeout

at Connection.<anonymous> (/app/node_modules/pg/lib/client.js:132:73)
at Object.onceWrapper (node:events:627:28)
at Connection.emit (node:events:513:28)
at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:57:12)
at Socket.emit (node:events:513:28)
at TCP.<anonymous> (node:net:301:12)
at process.<anonymous> (/app/server/server.js:1804:13)
at process.emit (node:events:513:28)
at emit (node:internal/process/promises:140:20)
at processPromiseRejections (node:internal/process/promises:274:27)
at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues

### 👟 Reproduction steps

Updfate docker container as it said there was an update for nightly tag
When it restarted, it no longer works.
Checked logs and got this as above.

change to latest tag and it is working again.

### 👀 Expected behavior

was working before update.

### 😓 Actual Behavior

no longer working

### 🐻 Uptime-Kuma Version

louislam/uptime-kuma:nightly

### 💻 Operating System and Arch

Unraid

### 🌐 Browser

chrome

### 🐋 Docker Version

louislam/uptime-kuma:nightly

### 📝 Relevant log output

```shell
==> Performing startup jobs and maintenance tasks
==> Starting application with user 99 group 100
Welcome to Uptime Kuma
Your Node.js version: 16

2023-03-31T10:14:40+10:00 [SERVER] INFO: Welcome to Uptime Kuma
2023-03-31T10:14:40+10:00 [SERVER] INFO: Node Env: production
2023-03-31T10:14:40+10:00 [SERVER] INFO: Importing Node libraries
2023-03-31T10:14:40+10:00 [SERVER] INFO: Importing 3rd-party libraries
2023-03-31T10:14:41+10:00 [SERVER] INFO: Creating express and socket.io instance
2023-03-31T10:14:41+10:00 [SERVER] INFO: Server Type: HTTP
2023-03-31T10:14:41+10:00 [SERVER] INFO: Importing this project modules
2023-03-31T10:14:41+10:00 [NOTIFICATION] INFO: Prepare Notification Providers
2023-03-31T10:14:42+10:00 [SERVER] INFO: Version: 1.21.1-nightly-20230329043034

2023-03-31T10:14:42+10:00 [DB] INFO: Data Dir: ./data/
2023-03-31T10:14:42+10:00 [SERVER] INFO: Connecting to the Database
2023-03-31T10:14:42+10:00 [DB] INFO: SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
2023-03-31T10:14:42+10:00 [DB] INFO: SQLite Version: 3.41.1

Trace: Error: Connection terminated due to connection timeout

at Connection.<anonymous> (/app/node_modules/pg/lib/client.js:132:73)
at Object.onceWrapper (node:events:627:28)
at Connection.emit (node:events:513:28)
at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:57:12)
at Socket.emit (node:events:513:28)
at TCP.<anonymous> (node:net:301:12)
at process.<anonymous> (/app/server/server.js:1804:13)
at process.emit (node:events:513:28)
at emit (node:internal/process/promises:140:20)
at processPromiseRejections (node:internal/process/promises:274:27)
at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
```

**Comment by louislam** [comment]
Please dont use nightly, it is an unstable version.
