### ISSUE TITLE
error in replit

### ISSUE THREAD

**Issue by Nipatsu** [louislam/uptime-kuma#3232]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I got this error when I tried to run it in repl.it
`internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'dayjs'
Require stack:
- /home/runner/hshshhsh/uptime-kuma/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/hshshhsh/uptime-kuma/server/server.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/hshshhsh/uptime-kuma/server/server.js' ]`

Link to repl [here](https://replit.com/@nipatsuyt/hshshhsh)

### 👟 Reproduction steps

just run  it in replit

### 👀 Expected behavior

it would start

### 😓 Actual Behavior

got error

### 🐻 Uptime-Kuma Version

i dont know. i just used git clone

### 💻 Operating System and Arch

replit

### 🌐 Browser

firefox

### 🟩 NodeJS Version

14

### 📝 Relevant log output

```shell
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'dayjs'
Require stack:
- /home/runner/hshshhsh/uptime-kuma/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/hshshhsh/uptime-kuma/server/server.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/hshshhsh/uptime-kuma/server/server.js' ]
```

**Comment by louislam** [comment]
replit is not supported
