### ISSUE TITLE
Uptime Kuma unresponsive with High CPU after clearing events on a monitor

### ISSUE THREAD

**Issue by bignay2000** [louislam/uptime-kuma#3248]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Clearing the Events on a http(s) monitor hangs Uptime Kuma for over a minute.  Get a black page with only showing the Uptime Kuma banner & Logo.

### 👟 Reproduction steps

Run louislam/uptime-kuma:1.21.3-alpine container on Raspberry Pi 4
Create a HTTP(s) web type monitor
Run monitor for more than 180 days
Log into Uptime Kuma
Click on the monitor
Click Clear Data
Click Events
Refresh webpage

### 👀 Expected behavior

Clear Data -> Events should not hang the application.  

I think their is a SQL query that is long running without a limit that takes up all the CPU.  
Maybe delete 100 records at a time with a 1 second sleep between calls to SQL?  Or limit the SQL transcaction to a single CPU Core.
```
sql: 'SELECT `value` FROM setting WHERE `key` = ?  limit ?'
```

### 😓 Actual Behavior

Raspberry Pi Load one minute Load Average jumps to 4.5
Errors are logged. 

uptime
```
load average: 4.07, 4.57, 2.80
```
![Screenshot 2023-06-11 at 3 26 56 PM](https://github.com/louislam/uptime-kuma/assets/11713022/8789849a-a238-4c96-a7d2-5682a4cacbf9)

### 🐻 Uptime-Kuma Version

louislam/uptime-kuma:1.21.3-alpine

### 💻 Operating System and Arch

Docker on Raspbian

### 🌐 Browser

Google Chrome 114

### 🐋 Docker Version

Docker version 24.0.2, build cb74dfc

### 🟩 NodeJS Version

v16.13.1

### 📝 Relevant log output

```shell
2023-06-11T15:11:21-04:00 [AUTH] INFO: Login by token. IP=172.16.16.7
2023-06-11T15:11:21-04:00 [AUTH] INFO: Username from JWT: hiveadmin
2023-06-11T15:13:21-04:00 [AUTH] ERROR: Invalid token. IP=172.16.16.7
2023-06-11T15:13:52-04:00 [MONITOR] WARN: Monitor #1 'esxi HTTPS': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 3 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2023-06-11T15:13:52-04:00 [MONITOR] WARN: Monitor #2 'esxi SSH': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 3 | Retry: 1 | Retry Interval: 60 seconds | Type: port
2023-06-11T15:13:52-04:00 [MONITOR] WARN: Monitor #7 'influxdb': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 3 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2023-06-11T15:13:52-04:00 [MONITOR] WARN: Monitor #16 'netdata.pi': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 3 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2023-06-11T15:13:52-04:00 [MONITOR] WARN: Monitor #14 'home': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 3 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2023-06-11T15:13:53-04:00 [MONITOR] WARN: Monitor #10 'hive VPN': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 3 | Retry: 1 | Retry Interval: 60 seconds | Type: dns
2023-06-11T15:13:54-04:00 [MONITOR] WARN: Monitor #3 'jenkins': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 3 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2023-06-11T15:13:54-04:00 [MONITOR] WARN: Monitor #13 'checkmk': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 3 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2023-06-11T15:13:55-04:00 [MONITOR] WARN: Monitor #6 'oldgitlab': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 3 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2023-06-11T15:13:55-04:00 [MONITOR] WARN: Monitor #5 'gitlab': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 3 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2023-06-11T15:13:55-04:00 [MONITOR] WARN: Monitor #15 'netdata.hivevm': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 3 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2023-06-11T15:13:55-04:00 [MONITOR] WARN: Monitor #4 'nexus': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 3 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2023-06-11T15:13:56-04:00 [MONITOR] WARN: Monitor #12 'glance.hivevm': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 3 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2023-06-11T15:13:57-04:00 [MONITOR] WARN: Monitor #11 'medpay.test': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 3 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2023-06-11T15:13:57-04:00 [MONITOR] WARN: Monitor #9 'hivetechnologies.net': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 3 | Retry: 1 | Retry Interval: 60 seconds | Type: http
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:569:22)
    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:555:22)
    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:590:19)
    at async Function.get (/app/server/settings.js:54:21)
    at async exports.setting (/app/server/util-server.js:438:12)
    at async /app/server/server.js:188:13 {
  sql: 'SELECT `value` FROM setting WHERE `key` = ?  limit ?',
  bindings: [ 'trustProxy', 1 ]
}
    at process.<anonymous> (/app/server/server.js:1804:13)
    at process.emit (node:events:390:28)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:569:22)
    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:555:22)
    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:590:19)
    at async Function.get (/app/server/settings.js:54:21) {
  sql: 'SELECT `value` FROM setting WHERE `key` = ?  limit ?',
  bindings: [ 'primaryBaseURL', 1 ]
}
    at process.<anonymous> (/app/server/server.js:1804:13)
    at process.emit (node:events:390:28)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:569:22)
    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:555:22)
    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:590:19)
    at async Function.get (/app/server/settings.js:54:21)
    at async exports.setting (/app/server/util-server.js:438:12)
    at async Namespace.<anonymous> (/app/server/server.js:1525:13) {
  sql: 'SELECT `value` FROM setting WHERE `key` = ?  limit ?',
  bindings: [ 'disableAuth', 1 ]
}
    at process.<anonymous> (/app/server/server.js:1804:13)
    at process.emit (node:events:390:28)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:569:22)
    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:555:22)
    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:590:19)
    at async Function.get (/app/server/settings.js:54:21)
    at async UptimeKumaServer.getClientIP (/app/server/uptime-kuma-server.js:242:13)
    at async Socket.<anonymous> (/app/server/server.js:279:30) {
  sql: 'SELECT `value` FROM setting WHERE `key` = ?  limit ?',
  bindings: [ 'trustProxy', 1 ]
}
    at process.<anonymous> (/app/server/server.js:1804:13)
    at process.emit (node:events:390:28)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:569:22)
    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:555:22)
    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:590:19)
    at async Function.get (/app/server/settings.js:54:21) {
  sql: 'SELECT `value` FROM setting WHERE `key` = ?  limit ?',
  bindings: [ 'primaryBaseURL', 1 ]
}
    at process.<anonymous> (/app/server/server.js:1804:13)
    at process.emit (node:events:390:28)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:569:22)
    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:555:22)
    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:590:19)
    at async Function.get (/app/server/settings.js:54:21)
    at async exports.setting (/app/server/util-server.js:438:12)
    at async Namespace.<anonymous> (/app/server/server.js:1525:13) {
  sql: 'SELECT `value` FROM setting WHERE `key` = ?  limit ?',
  bindings: [ 'disableAuth', 1 ]
}
    at process.<anonymous> (/app/server/server.js:1804:13)
    at process.emit (node:events:390:28)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:569:22)
    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:555:22)
    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:590:19)
    at async Function.get (/app/server/settings.js:54:21)
    at async UptimeKumaServer.getClientIP (/app/server/uptime-kuma-server.js:242:13)
    at async Socket.<anonymous> (/app/server/server.js:279:30) {
  sql: 'SELECT `value` FROM setting WHERE `key` = ?  limit ?',
  bindings: [ 'trustProxy', 1 ]
}
    at process.<anonymous> (/app/server/server.js:1804:13)
    at process.emit (node:events:390:28)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:569:22)
    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:555:22)
    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:590:19)
    at async Function.get (/app/server/settings.js:54:21) {
  sql: 'SELECT `value` FROM setting WHERE `key` = ?  limit ?',
  bindings: [ 'primaryBaseURL', 1 ]
}
    at process.<anonymous> (/app/server/server.js:1804:13)
    at process.emit (node:events:390:28)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:569:22)
    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:555:22)
    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:590:19)
    at async Function.get (/app/server/settings.js:54:21)
    at async exports.setting (/app/server/util-server.js:438:12)
    at async Namespace.<anonymous> (/app/server/server.js:1525:13) {
  sql: 'SELECT `value` FROM setting WHERE `key` = ?  limit ?',
  bindings: [ 'disableAuth', 1 ]
}
    at process.<anonymous> (/app/server/server.js:1804:13)
    at process.emit (node:events:390:28)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:569:22)
    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:555:22)
    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:590:19)
    at async Function.get (/app/server/settings.js:54:21)
    at async UptimeKumaServer.getClientIP (/app/server/uptime-kuma-server.js:242:13)
    at async Socket.<anonymous> (/app/server/server.js:279:30) {
  sql: 'SELECT `value` FROM setting WHERE `key` = ?  limit ?',
  bindings: [ 'trustProxy', 1 ]
}
    at process.<anonymous> (/app/server/server.js:1804:13)
    at process.emit (node:events:390:28)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
2023-06-11T15:15:18-04:00 [AUTH] INFO: Login by token. IP=172.16.16.7
2023-06-11T15:15:18-04:00 [AUTH] INFO: Username from JWT: hiveadmin
2023-06-11T15:15:19-04:00 [AUTH] INFO: Successfully logged in user hiveadmin. IP=172.16.16.7
```

**Comment by CommanderStorm** [comment]
What kind of storage do you use on your pi?

**Comment by CommanderStorm** [comment]
This may be a duplicate of https://github.com/louislam/uptime-kuma/issues/2346

**Comment by bignay2000** [comment]
> What kind of storage do you use on your pi?

Runs off a micro SD card.

**Comment by bignay2000** [comment]
> This may be a duplicate of #2346

Any work arounds?

**Comment by bignay2000** [comment]
Any idea how long a monitor event is kept in the database?  Maybe a configuration to limit the number of history for Events and Heartbeats...  I only need 4 days worth of metrics (just enough to cover a long weekend).

**Comment by bignay2000** [comment]
Update to 30 days history.  Ran the Clear all Statistics.

![Screenshot 2023-06-11 at 7 42 25 PM](https://github.com/louislam/uptime-kuma/assets/11713022/2e803466-b8de-4a7b-847f-e1d2eb0514af)

**Comment by bignay2000** [comment]
ouislam/uptime-kuma:1.21.3-alpine is Alpine Linux v3.12 (reelased on 2020-05-29) with Node v16.13.1 installed.

I wonder why the latest container is shipping with older Alpine and Node.js

Uptime Kuma supports Node v.18 (per the README in GitHub)

**Comment by bignay2000** [comment]
Moved from louislam/uptime-kuma:1.21.3-alpine to louislam/uptime-kuma:1.21.3-debian

Node is now 16.20.0 and the OS is more current.

**Comment by CommanderStorm** [comment]
> Runs off a micro SD card

Running IO-Heavy Workloads of off slow micro SD cards is not recomended. The delete operation could delete hundreds of MB worth of data => I would expect there to be performance penalties.

> Any work arounds to throttle SQL queries

Over in #2346 Nelson has noted that `PRAGMA synchronous = NORMAL` or `PRAGMA synchronous = OFF` might be worth a try, but no user has yet reported back the results.'
Given that I don't have access to a Pi, could you install uptime-kuma on your machine and see if this solves the performance problems?

**Comment by CommanderStorm** [comment]
I think this is a duplicate of #2346 could we close this issue and continue investigation over there?
