### ISSUE TITLE
Error: Cannot find module 'dayjs'

### ISSUE THREAD

**Issue by fynnpunkt** [louislam/uptime-kuma#3423]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

The Uptime Kuma Server is down, and i cant start it.

### 📝 Error Message(s) or Log

root@vps-zap1078412-2:~/uptime-kuma# node server/server.js
Welcome to Uptime Kuma
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module 'dayjs'
Require stack:
- /root/uptime-kuma/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/root/uptime-kuma/server/server.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/root/uptime-kuma/server/server.js' ]
}
root@vps-zap1078412-2:~/uptime-kuma#

### 🐻 Uptime-Kuma Version

The Newest

### 💻 Operating System and Arch

Debian 10 - 64bit

### 🌐 Browser

Google Chrome 

### 🐋 Docker Version

-

### 🟩 NodeJS Version

14.18

**Comment by fynnpunkt** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/136633467/040d0ba0-6bd6-4285-a298-c121e49f4edf)

**Comment by Zaid-maker** [comment]
Looks like `npm install` not runned correctly, remove the existing node_modules and run the `npm install` again it should work fine!

**Comment by CommanderStorm** [comment]
Btw you are using node 14, [which is EOL](https://endoflife.date/nodejs) and has known bugs associated with it.
Please consider upgrading your node version to a more recent version like node 18
