### ISSUE TITLE
QQ邮件配置无法测试通过

### ISSUE THREAD

**Issue by gaye746560359** [louislam/uptime-kuma#3434]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![image](https://github.com/louislam/uptime-kuma/assets/3060035/8b795099-47eb-4c1b-b29c-aaea3c5a7f91)

### 👟 Reproduction steps

![image](https://github.com/louislam/uptime-kuma/assets/3060035/b3c784ad-1ceb-4c7c-8ec9-4c57f08a357c)

### 👀 Expected behavior

发送邮件

### 😓 Actual Behavior

未发送

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

centos7

### 🌐 Browser

chrome 114

### 🐋 Docker Version

Docker version 23.0.1

### 📝 Relevant log output

```shell
Error: Invalid login: 535 Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256
    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1536:34)
    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:540:26)
    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)
    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
    at TLSSocket.SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10) {
  code: 'EAUTH',
  response: '535 Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256',
  responseCode: 535,
  command: 'AUTH PLAIN'
}
```

**Comment by louislam** [comment]
這個明顯是 QQ 郵件的問題吧。 Google或百度一下 `535 Login Fail` 已經可以找到很多解決方法。

**Comment by gaye746560359** [comment]
> 這個明顯是 QQ 郵件的問題吧。 Google或百度一下 `535 Login Fail` 已經可以找到很多解決方法。

已解决，是用户名和发信人需要一致

**Comment by grafies** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/54047540/ea4813c6-7e31-4541-9b9a-ce07c43568a9)

可以这样设置
