### ISSUE TITLE
[pushplus] support notification provider

### ISSUE THREAD

**Issue by kilvn** [louislam/uptime-kuma#3453]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [x] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

pushplus is a good notice service.
website home: https://www.pushplus.plus/

### ✔️ Solution

no have, please see website.

**Comment by kilvn** [comment]
Uptime kuma is very useful, but it may show the running situation within a few hours. I have already switched to Uptime robot, and what I need is the running situation over a long period of time https://status.kilvn.com/

**Comment by crazybird** [comment]
Error log:

Error: Error: Error: getaddrinfo EAI_AGAIN www.pushplus.plus
    at Webhook.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:38:15)
    at Webhook.send (/app/server/notification-providers/webhook.js:57:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Socket.<anonymous> (/app/server/server.js:1298:27)

**Comment by CommanderStorm** [comment]
@crazybird your issue is unrelated: Your issue is that your DNS Provider does not return a response for that dns entry. You will need to query fewer times or
- enable dns caching in the settings (for docker users)
- install an equivalend dns caching solution (for non-docker users)
