### ISSUE TITLE
Upgraded from 1.19.1 to 1.22.1 and now keeps crashing

### ISSUE THREAD

**Issue by sricard999** [louislam/uptime-kuma#3500]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Was running under k3s fine for about a year

### 👟 Reproduction steps

Don't have to do anything and it crashes by itself.

### 👀 Expected behavior

don't crash

### 😓 Actual Behavior

Crashes

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Distributor ID: Ubuntu Description:    Ubuntu 20.04.6 LTS Release:        20.04 Codename:       focal

### 🌐 Browser

Chrome Version 114.0.5735.199 (Official Build) (64-bit)

### 🐋 Docker Version

k3s v1.25.11+k3s1

### 🟩 NodeJS Version

Whatever is inside the Docker

### 📝 Relevant log output

```shell
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Your Node.js version: 16
2023-07-28T21:44:54Z [SERVER] INFO: Welcome to Uptime Kuma
2023-07-28T21:44:54Z [SERVER] INFO: Node Env: production
2023-07-28T21:44:54Z [SERVER] INFO: Importing Node libraries
2023-07-28T21:44:54Z [SERVER] INFO: Importing 3rd-party libraries
2023-07-28T21:44:56Z [SERVER] INFO: Creating express and socket.io instance
2023-07-28T21:44:56Z [SERVER] INFO: Server Type: HTTP
2023-07-28T21:44:56Z [SERVER] INFO: Importing this project modules
2023-07-28T21:44:56Z [NOTIFICATION] INFO: Prepare Notification Providers
2023-07-28T21:44:56Z [SERVER] INFO: Version: 1.22.1
2023-07-28T21:44:57Z [DB] INFO: Data Dir: ./data/
2023-07-28T21:44:57Z [SERVER] INFO: Connecting to the Database
2023-07-28T21:44:57Z [DB] INFO: SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
2023-07-28T21:44:57Z [DB] INFO: SQLite Version: 3.41.1
2023-07-28T21:44:57Z [SERVER] INFO: Connected
2023-07-28T21:44:57Z [DB] INFO: Your database version: 10
2023-07-28T21:44:57Z [DB] INFO: Latest database version: 10
2023-07-28T21:44:57Z [DB] INFO: Database patch not needed
2023-07-28T21:44:57Z [DB] INFO: Database Patch 2.0 Process
2023-07-28T21:44:57Z [SERVER] INFO: Load JWT secret from database.
2023-07-28T17:44:57-04:00 [SERVER] INFO: Adding route
2023-07-28T17:44:57-04:00 [SERVER] INFO: Adding socket handler
2023-07-28T17:44:57-04:00 [SERVER] INFO: Init the server
2023-07-28T17:44:57-04:00 [SERVER] INFO: Listening on 3001
2023-07-28T17:45:05-04:00 [AUTH] INFO: Login by token. IP=10.42.6.76
2023-07-28T17:45:05-04:00 [AUTH] INFO: Username from JWT: xxxxx
2023-07-28T17:45:05-04:00 [AUTH] INFO: Successfully logged in user xxxx. IP=10.42.6.76
2023-07-28T17:45:31-04:00 [SERVER] INFO: Shutdown requested
2023-07-28T17:45:31-04:00 [SERVER] INFO: Called signal: SIGTERM
2023-07-28T17:45:32-04:00 [SERVER] INFO: Stopping all monitors
2023-07-28T17:45:34-04:00 [DB] INFO: Closing the database
Trace: Error: aborted
    at PendingOperation.abort (/app/node_modules/tarn/dist/PendingOperation.js:25:21)
    at /app/node_modules/tarn/dist/Pool.js:208:25
    at Array.map (<anonymous>)
    at /app/node_modules/tarn/dist/Pool.js:207:53
    at async Client_SQLite3.destroy (/app/node_modules/knex/lib/client.js:338:9)
    at async RedBeanNode.close (/app/node_modules/redbean-node/dist/redbean-node.js:378:9)
    at async Function.close (/app/server/database.js:419:13)
    at async Object.shutdownFunction [as onShutdown] (/app/server/server.js:1802:5)
    at safeBeat (/app/server/model/monitor.js:857:25)
2023-07-28T17:45:40-04:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
2023-07-28T17:45:40-04:00 [MONITOR] ERROR: Caught error
2023-07-28T17:45:40-04:00 [MONITOR] ERROR: aborted
Trace: Error: aborted
    at PendingOperation.abort (/app/node_modules/tarn/dist/PendingOperation.js:25:21)
    at /app/node_modules/tarn/dist/Pool.js:208:25
    at Array.map (<anonymous>)
    at /app/node_modules/tarn/dist/Pool.js:207:53
    at async Client_SQLite3.destroy (/app/node_modules/knex/lib/client.js:338:9)
    at async RedBeanNode.close (/app/node_modules/redbean-node/dist/redbean-node.js:378:9)
    at async Function.close (/app/server/database.js:419:13)
    at async Object.shutdownFunction [as onShutdown] (/app/server/server.js:1802:5)
    at safeBeat (/app/server/model/monitor.js:857:25)
2023-07-28T17:45:40-04:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
Trace: Error: aborted
    at PendingOperation.abort (/app/node_modules/tarn/dist/PendingOperation.js:25:21)
    at /app/node_modules/tarn/dist/Pool.js:208:25
    at Array.map (<anonymous>)
    at /app/node_modules/tarn/dist/Pool.js:207:53
    at async Client_SQLite3.destroy (/app/node_modules/knex/lib/client.js:338:9)
    at async RedBeanNode.close (/app/node_modules/redbean-node/dist/redbean-node.js:378:9)
    at async Function.close (/app/server/database.js:419:13)
    at async Object.shutdownFunction [as onShutdown] (/app/server/server.js:1802:5)
    at process.<anonymous> (/app/server/server.js:1825:13)
    at process.emit (node:events:525:35)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: Error: aborted
    at PendingOperation.abort (/app/node_modules/tarn/dist/PendingOperation.js:25:21)
    at /app/node_modules/tarn/dist/Pool.js:208:25
    at Array.map (<anonymous>)
    at /app/node_modules/tarn/dist/Pool.js:207:53
    at async Client_SQLite3.destroy (/app/node_modules/knex/lib/client.js:338:9)
    at async RedBeanNode.close (/app/node_modules/redbean-node/dist/redbean-node.js:378:9)
    at async Function.close (/app/server/database.js:419:13)
    at async Object.shutdownFunction [as onShutdown] (/app/server/server.js:1802:5)
    at process.<anonymous> (/app/server/server.js:1825:13)
    at process.emit (node:events:525:35)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
2023-07-28T17:45:42-04:00 [DB] INFO: Waiting to close the database
2023-07-28T17:45:44-04:00 [DB] INFO: SQLite closed
2023-07-28T17:45:44-04:00 [CLOUDFLARED] INFO: Stop cloudflared
2023-07-28T17:45:44-04:00 [SERVER] INFO: Graceful shutdown successful!
```

**Comment by CommanderStorm** [comment]
Currently, I could not replicate this issue.
Can you provide us a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

I tried to replicate it via these steps:

- ```bash
  sudo docker volume create uptime-kuma
  sudo docker run --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1.19.1
  ```
- setup kuma
- add a few monitors
- ```bash
  sudo docker run --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1.21.1
  ```

**Comment by CommanderStorm** [comment]
Could you also check the steps in https://github.com/louislam/uptime-kuma/issues/2889

**Comment by chakflying** [comment]
To be clear, it's not crashing, since the logs show that the server received `SIGTERM` exactly 30 seconds after start. This is more likely a healthcheck issue. Maybe you should check your kubernetes logs to see if it thinks the container is unhealthy and terminated it.

**Comment by sricard999** [comment]
Thanks guys for a rapid response.

The health check is calling:

node extra/healthcheck.js

and expecting an exit with status 0.

When I execute node extra/healthcheck.js inside the container, I get this answer:

***@***.***:/app# node extra/healthcheck.js
Health Check OK [Res Code: 302]
***@***.***:/app#

I guess the status code is not 0

Will disable health check for now to stop the crashlooping.

Any suggestions,
Thanks

Stéphane Ricard
***@***.******@***.***>
________________________________

**Comment by CommanderStorm** [comment]
`extra/healthcheck.js` is not working in k8s due to the collision of `UPTIME_KUMA_PORT` env vars
See https://github.com/louislam/uptime-kuma/issues/2805#issuecomment-1437430838

**Comment by CommanderStorm** [comment]
Where did you get your helm chart from?

**Comment by sricard999** [comment]
uptime-kuma                         https://dirsigler.github.io/uptime-kuma-helm
Usage<https://dirsigler.github.io/uptime-kuma-helm>
This Helm Chart installs Uptime-Kuma from @louislam to your Kubernetes Cluster.
dirsigler.github.io

But tried to update it directly by updating the container image version manually to 1.22.1

Up and running now but with no health check. Was thinking of adding http 200 on an http request to / but would need to test.

Thanks

Stéphane Ricard
***@***.******@***.***>
________________________________

**Comment by CommanderStorm** [comment]
Please also update your deployments in the future: https://github.com/dirsigler/uptime-kuma-helm/blob/1b75f5e6fa0f7f593e4268628557675f98862286/charts/uptime-kuma/templates/deployment.yaml#L56

**Comment by CommanderStorm** [comment]
Could you close this issue as it is resolved?

**Comment by sricard999** [comment]
Will do thanks

Stéphane Ricard
***@***.******@***.***>
________________________________

**Comment by sricard999** [comment]
Thanks for your quick responses on this issue.

**Comment by CommanderStorm** [comment]
Always welcome ^^
