### ISSUE TITLE
the db monitor not opening after restore of db

### ISSUE THREAD

**Issue by amanasterdio** [louislam/uptime-kuma#3577]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

A mistake from my end. 
It seemed that the uptime kuma backup-and-restore feature had been depreceated. 

i wanted to mass update my older monitors to the new monitor-group feature. So I had backed up the configuration which resulted in a JSON file. 
Now I had updated the required data on the backed up JSON file and restored it. 
everything is crashed now. 
The monitors are in paused. No option to resume all at once. 
I manually enabled all the HTTP and ping monitors. 
But the database monitors like mariadb. mongodb and postgres are not opening in the monitor to resume it. 
It just shows blank screen on the right, 

![image](https://github.com/louislam/uptime-kuma/assets/113028289/72f63b94-6db8-49de-b245-d83fa114fa63)

Now when I check into my other monitors which monitor the databases. this black screen appears. This is seen while I am trying to resume the postgres monitor. 
![image](https://github.com/louislam/uptime-kuma/assets/113028289/5b8c3a9f-ca66-4628-90ef-5851d55d0671)

### 📝 Error Message(s) or Log

![image](https://github.com/louislam/uptime-kuma/assets/113028289/96d5182d-653d-4efd-b4cc-d17074c3eabd)
 
 this error was seen in the docker
 
 

2023-08-15 15:22:29	
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
2023-08-15 15:22:29	
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
2023-08-15 15:22:29	
    at processPromiseRejections (node:internal/process/promises:274:27)
2023-08-15 15:22:29	
    at emit (node:internal/process/promises:140:20)
2023-08-15 15:22:29	
    at process.emit (node:events:513:28)
2023-08-15 15:22:29	
    at process.<anonymous> (/app/server/server.js:1825:13)
2023-08-15 15:22:29	
}
2023-08-15 15:22:29	
  bindings: undefined
2023-08-15 15:22:29	
  sql: undefined,
2023-08-15 15:22:29	
    at async Object.exports.login (/app/server/auth.js:21:16) {
2023-08-15 15:22:29	
    at async RedBeanNode.findOne (/app/node_modules/redbean-node/dist/redbean-node.js:499:19)
2023-08-15 15:22:29	
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
2023-08-15 15:22:29	
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
2023-08-15 15:22:29	
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
2023-08-15 15:22:28	
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
2023-08-15 15:22:00	
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
2023-08-15 15:22:00	
    at processTimers (node:internal/timers:499:9)
2023-08-15 15:22:00	
    at runNextTicks (node:internal/process/task_queues:65:3)
2023-08-15 15:22:00	
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
2023-08-15 15:22:00	
    at processPromiseRejections (node:internal/process/promises:274:27)
2023-08-15 15:22:00	
    at emit (node:internal/process/promises:140:20)
2023-08-15 15:22:00	
    at process.emit (node:events:513:28)
2023-08-15 15:22:00	
    at process.<anonymous> (/app/server/server.js:1825:13)
2023-08-15 15:22:00	
}
2023-08-15 15:22:00	
  ]
2023-08-15 15:22:00	
    177
2023-08-15 15:22:00	
    '2023-08-14 09:34:59',
2023-08-15 15:22:00	
    '2023-08-14 09:34:59',
2023-08-15 15:22:00	
    '2023-08-14 09:34:59',
2023-08-15 15:22:00	
    '2023-08-14 09:34:59',
2023-08-15 15:22:00	
    '2023-08-14 09:34:59',
2023-08-15 15:22:00	
  bindings: [
2023-08-15 15:22:00	
    '        ',
2023-08-15 15:22:00	
    '            AND monitor_id = ?\n' +
2023-08-15 15:22:00	
    '            WHERE time > ?\n' +
2023-08-15 15:22:00	
    '            FROM heartbeat\n' +
2023-08-15 15:22:00	
    '                ) AS uptime_duration\n' +
2023-08-15 15:22:00	
    '                        END\n' +
2023-08-15 15:22:00	
    '                            END\n' +
2023-08-15 15:22:00	
    '                                ELSE duration\n' +
2023-08-15 15:22:00	
    '                                    THEN (JULIANDAY(`time`) - JULIANDAY(?)) * 86400\n' +
2023-08-15 15:22:00	
    '                                WHEN (JULIANDAY(`time`) - JULIANDAY(?)) * 86400 < duration\n' +
2023-08-15 15:22:00	
    '                            CASE\n' +
2023-08-15 15:22:00	
    '                        THEN\n' +
2023-08-15 15:22:00	
    '                        WHEN (status = 1 OR status = 3)\n' +
2023-08-15 15:22:00	
    '                    CASE\n' +
2023-08-15 15:22:00	
    '                SUM(\n' +
2023-08-15 15:22:00	
    '               -- SUM all uptime duration, also trim off the beat out of time window\n' +
2023-08-15 15:22:00	
    '\n' +
2023-08-15 15:22:00	
    '                ) AS total_duration,\n' +
2023-08-15 15:22:00	
    '                    END\n' +
2023-08-15 15:22:00	
    '                        ELSE duration\n' +
2023-08-15 15:22:00	
    '                        THEN (JULIANDAY(`time`) - JULIANDAY(?)) * 86400\n' +
2023-08-15 15:22:00	
    '                        WHEN (JULIANDAY(`time`) - JULIANDAY(?)) * 86400 < duration\n' +
2023-08-15 15:22:00	
    '                    CASE\n' +
2023-08-15 15:22:00	
    '                SUM(\n' +
2023-08-15 15:22:00	
    '               -- SUM all duration, also trim off the beat out of time window\n' +
2023-08-15 15:22:00	
    '            SELECT\n' +
2023-08-15 15:22:00	
  sql: '\n' +
2023-08-15 15:22:00	
    at async Function.sendUptime (/app/server/model/monitor.js:1137:24) {
2023-08-15 15:22:00	
    at async Function.calcUptime (/app/server/model/monitor.js:1071:22)
2023-08-15 15:22:00	
    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:558:22)
2023-08-15 15:22:00	
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:572:22)
2023-08-15 15:22:00	
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
2023-08-15 15:22:00	
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
2023-08-15 15:22:00	
    at processTimers (node:internal/timers:499:9)
2023-08-15 15:22:00	
    at runNextTicks (node:internal/process/task_queues:61:5)
2023-08-15 15:22:00	
    at runMicrotasks (<anonymous>)
2023-08-15 15:22:00	
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
2023-08-15 15:22:00	
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
2023-08-15 15:22:00	
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
2023-08-15 15:22:00	
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
2023-08-15 15:22:00	
    at processPromiseRejections (node:internal/process/promises:274:27)
2023-08-15 15:22:00	
    at emit (node:internal/process/promises:140:20)
2023-08-15 15:22:00	
    at process.emit (node:events:513:28)
2023-08-15 15:22:00	
    at process.<anonymous> (/app/server/server.js:1825:13)
2023-08-15 15:22:00	
}
2023-08-15 15:22:00	
  bindings: undefined
2023-08-15 15:22:00	
  sql: undefined,
2023-08-15 15:22:00	
    at async Function.sendStats (/app/server/model/monitor.js:1006:13) {
2023-08-15 15:22:00	
    at async Function.sendCertInfo (/app/server/model/monitor.js:1041:23)
2023-08-15 15:22:00	
    at async RedBeanNode.findOne (/app/node_modules/redbean-node/dist/redbean-node.js:499:19)
2023-08-15 15:22:00	
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
2023-08-15 15:22:00	
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
2023-08-15 15:22:00	
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
2023-08-15 15:22:00	
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

### 🐻 Uptime-Kuma Version

Version: 1.22.1

### 💻 Operating System and Arch

Ubuntu 18.04.6 LTS

### 🌐 Browser

Version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)

### 🐋 Docker Version

Docker version 23.0.4, build f480fb1

**Comment by CommanderStorm** [comment]
You edited the json file manually, did I read that correctly?
What did you edit?

**Comment by amanasterdio** [comment]
My plan was to basically add the already running monitors to my newly created monitor groups. 
So I added the monitors to the monitor group, still same. 
But the issue was even same when I tried using  it after undoing the changes to the json file.

Tried with the mentioned version  and same in Version: 1.22.1-nightly-20230804151121 too.
