### ISSUE TITLE
Showing  a white screen

### ISSUE THREAD

**Issue by gamer50082** [louislam/uptime-kuma#3691]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Received a white screen

## No error on server side console
# Error from browser devtools console

Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
--------------------------------------------------------------------------------------------------------------------------
index-919ccbd7.js:9 
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' http: https: data: blob: 'unsafe-inline'".

    at new Function (<anonymous>)
    at Qg (index-919ccbd7.js:9:48918)
    at Rg (index-919ccbd7.js:9:21416)
    at Ig (index-919ccbd7.js:9:20350)
    at index-919ccbd7.js:9:28949
    at U (index-919ccbd7.js:9:28795)
    at Object.P [as t] (index-919ccbd7.js:9:28936)
    at Object.t (index-919ccbd7.js:9:35124)
    at Proxy.$t (index-919ccbd7.js:9:41751)
    at Proxy.data (index-919ccbd7.js:20:11259)

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

linux

### 🌐 Browser

Microsoft Edge Version 116.0.1938.69 (Official build) (64-bit) & Brave  Version 1.57.57 Chromium: 116.0.5845.163 (Official Build) (64-bit)

### 🟩 NodeJS Version

Nodejs 18

**Comment by gamer50082** [comment]
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
is shown only on brave after refreshing again

**Comment by gamer50082** [comment]
its just my hosting provider issue with thier reverse proxy
