### ISSUE TITLE
Notification only being sent when monitored service comes back up

### ISSUE THREAD

**Issue by lordmofisto** [louislam/uptime-kuma#3778]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I recently updated to 1.23.1. 

I am using a webhook notification to send alerts when monitored services are down using PING 

I can do a test send and I receive it. I also receive notifications when a service comes back up after being down, but the alert letting me know a service went down in the first place isn't coming through. The logs are included below 

### 📝 Error Message(s) or Log

```
2023-09-20T20:51:51.094326466Z 2023-09-20T14:51:51-06:00 [MONITOR] ERROR: Cannot send notification to Uptime-Kuma Dectection
2023-09-20T20:51:51.096885926Z Error: Error: AxiosError: Request failed with status code 400 {"status":400,"error":{"message":"Unexpected token \""}}
2023-09-20T20:51:51.096922873Z     at Webhook.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:38:15)
2023-09-20T20:51:51.096953290Z     at Webhook.send (/app/server/notification-providers/webhook.js:57:18)
2023-09-20T20:51:51.096960747Z     at runMicrotasks (<anonymous>)
2023-09-20T20:51:51.096967522Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-09-20T20:51:51.096973864Z     at async Function.sendNotification (/app/server/model/monitor.js:1380:21)
2023-09-20T20:51:51.096980236Z     at async beat (/app/server/model/monitor.js:917:21)
2023-09-20T20:51:51.096988676Z     at async Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:985:17)
```

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Ubuntu Server 20.04

### 🌐 Browser

Chrome

**Comment by CommanderStorm** [comment]
- What is your template?
- To check how you need to tweak the template, a interceptor like https://webhook.site/ might be helpfull.
- Could you have a look at https://github.com/louislam/uptime-kuma/pull/3636 if this maybe cleas up some things?

**Comment by lordmofisto** [comment]
I am using the following

1.) Notification Type: Webhook
2.) Request Body: Custom Body
3.) Custom JSON body (see below) 
4.) Additional Headers: On/True
5.) Additional Header Content (see below) 


Custom Body
`
{
  "attachments": [
    {
      "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
      "type": "AdaptiveCard",
      "version": "1.3",
      "body": [
        {
          "type": "Container",
          "items": [
            {
              "type": "ColumnSet",
              "columns": [
                {
                  "type": "Column",
                  "width": "stretch",
                  "items": [
                    {
                      "type": "TextBlock",
                      "text": "A monitored service is down",
                      "weight": "bolder",
                      "size": "large",
                      "color": "warning",
                      "wrap": true
                    },
                    {
                      "type": "Image",
                      "url": "MYPICURL",
                      "size": "small",
                      "style": "person"
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "type": "Container",
          "items": [
            {
              "type": "FactSet",
              "facts": [
                {
                  "title": "Name",
                  "value": "{{ monitorJSON['name'] }}"
                },
                {
                  "title": "Description",
                  "value": "{{ monitorJSON['description'] }}"
                },
                {
                  "title": "Hostname",
                  "value": "{{ monitorJSON['hostname'] }}"
                },
                {
                  "title": "Type",
                  "value": "{{ monitorJSON['type'] }}"
                }
              ]
            }
          ]
        },
        {
          "type": "Container",
          "items": [
            {
              "type": "TextBlock",
              "text": "{{ msg }}"
            }
          ]
        }
      ]
    }
  ]
}
`


Custom Header
`
{
  "Content-Type": "application/json"
}
`

I don't get an invalid token message when I do the test notification or when the service comes back up, so I am not sure why the down notification would be treated differently.

**Comment by CommanderStorm** [comment]
<details><summary>here is the output nicely formatted</summary>
<p>

```json
{
  "attachments": [
    {
      "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
      "type": "AdaptiveCard",
      "version": "1.3",
      "body": [
        {
          "type": "Container",
          "items": [
            {
              "type": "ColumnSet",
              "columns": [
                {
                  "type": "Column",
                  "width": "stretch",
                  "items": [
                    {
                      "type": "TextBlock",
                      "text": "A monitored service is down",
                      "weight": "bolder",
                      "size": "large",
                      "color": "warning",
                      "wrap": true
                    },
                    {
                      "type": "Image",
                      "url": "MYPICURL",
                      "size": "small",
                      "style": "person"
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "type": "Container",
          "items": [
            {
              "type": "FactSet",
              "facts": [
                {
                  "title": "Name",
                  "value": "{{ monitorJSON['name'] }}"
                },
                {
                  "title": "Description",
                  "value": "{{ monitorJSON['description'] }}"
                },
                {
                  "title": "Hostname",
                  "value": "{{ monitorJSON['hostname'] }}"
                },
                {
                  "title": "Type",
                  "value": "{{ monitorJSON['type'] }}"
                }
              ]
            }
          ]
        },
        {
          "type": "Container",
          "items": [
            {
              "type": "TextBlock",
              "text": "{{ msg }}"
            }
          ]
        }
      ]
    }
  ]
}
```

</p>
</details> 

That does not look faulty, nor like the culprit. Interesting.

I have a few ideas:
- could you test sending this webhook event using postman, curl or equivalent tools to rule out that the template is at fault?
- Where does the token come from? Is it somewhere in the url? How do you authentificate exactly? (what is the notification provider you are using)
- Do you have other monitors running that could produce such a message (might this log message be misleading?)

**Comment by chakflying** [comment]
This is quite a nasty bug. Apparently if `msg` contains newline characters, it causes the whole body to be escaped and enclosed in `""`, thereby becoming invalid JSON and gets rejected by Teams. Will need to continue to investigate the root cause.

For now, please change this in the template which should mitigate the issue:
```json
            {
              "type": "TextBlock",
              "text": "{{ msg | replace: "\n", "" }}"
            }
```

**Comment by lordmofisto** [comment]
That has fixed my issue, thank you very much for your help

**Comment by chakflying** [comment]
After investigation, this is a combination of 2 things:

- `msg` containing unescaped newline characters as a footgun:
  
  When the template engine simply substitutes `{{ msg }}`, this results in:
  ```json
        {
          "type": "Container",
          "items": [
            {
              "type": "TextBlock",
              "text": "[Test Bad Ping] [🔴 Down]
    Pinging 107.210.24.15 with 56 bytes of data:
    Request timed out.
    
    Ping statistics for 107.210.24.15:
        Packets: Sent = 1, Received = 0, Lost = 1 (100% loss),
    "
            }
          ]
  ```
  Which itself is invalid JSON, but if this got sent the error should be more obvious, if not for
- `axios` trying to parse the body as JSON again 🤦🏻‍♂️. 
   
   `axios` would detect that we have set the `Content-Type` as `application/json`, and try to parse the data as JSON to trim whitespaces. But since we provided invalid JSON, it then falls back to calling `JSON.stringify(data)`, which created the resulting mess.

I don't see an easy way to fix this. Maybe `msg` shouldn't contain unescaped newlines? Or maybe we shouldn't even be using `axios` in this case? In these situations where we want to precisely control over the output, `axios` is too opinionated to work with.

**Comment by DemoJ** [comment]
> This is quite a nasty bug. Apparently if `msg` contains newline characters, it causes the whole body to be escaped and enclosed in `""`, thereby becoming invalid JSON and gets rejected by Teams. Will need to continue to investigate the root cause.这是一个非常讨厌的错误。显然，如果 `msg` 包含换行符，则会导致整个正文被转义并包含在 `""` 中，从而成为无效的 JSON 并被 Teams 拒绝。需要继续调查根本原因。
> 
> For now, please change this in the template which should mitigate the issue:现在，请在模板中更改此设置，这应该可以缓解该问题：
> 
> ```
>             {
>               "type": "TextBlock",
>               "text": "{{ msg | replace: "\n", "" }}"
>             }
> ```

After searching for so long, I've finally found the solution. It's a lifesaver!

**Comment by JoshTheBlack** [comment]
This issue was closed, but should probably remain open until it has been fixed.  Can you reopen please?

**Comment by CommanderStorm** [comment]
> maybe we shouldn't even be using `axios` in this case? In these situations where we want to precisely control over the output, `axios` is too opinionated to work with

It needs investigating if we can disable the json parsing in axios via a request option.
If this is the case, I would suggest to stick with it for the time being.
If no such option exists, switching to plain `fetch` or `XMLHttpRequest`s seems like a good idea.

If a contributor would like to look into this, the webhook notification-provider is located [here](https://github.com/louislam/uptime-kuma/blob/master/server/notification-providers/webhook.js) and the contributing guide (how to setup your environment, ...) is located [here](https://github.com/louislam/uptime-kuma/blob/a309cf0e2cdfa0a9f9a39215c163b90e52eece9c/CONTRIBUTING.md)
