### ISSUE TITLE
[Real Browser] High CPU/Memory Usage

### ISSUE THREAD

**Issue by Ali-Razmjoo** [louislam/uptime-kuma#3788]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hi.

I have been using the new feature using web drive to browse a URL; and today I noticed my status page is down; when I tried to connect to my SSH I got time out and my monitoring indicates there is high CPU usage of chromium inside of docker.

Here is how service is affected.

<img width="644" alt="image" src="https://github.com/louislam/uptime-kuma/assets/7676267/0ab51cd9-349a-4cc2-8973-f0767b55134c">

Current status from processes usages sort by highest  size / usage : 

<img width="1089" alt="image" src="https://github.com/louislam/uptime-kuma/assets/7676267/8489871b-c3d5-458d-a9e3-e4084726e2de">

Full command (there are many of these) list from my current processes:
```
/usr/lib/chromium/chromium --type=renderer --no-sandbox --disable-dev-shm-usage --disable-background-timer-throttling --disable-breakpad --enable-automation --file-url-path-alias=/gen=/usr/lib/chromium/gen --force-color-profile=srgb --remote-debugging-pipe --allow-pre-commit-input --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --field-trial-handle=10896847204213107046,12334856278103598370,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=AcceptCHFrame,AutoExpandDetailsElement,AvoidUnnecessaryBeforeUnloadCheckSync,CertificateTransparencyComponentUpdater,DestroyProfileOnBrowserClose,DialMediaRouteProvider,GlobalMediaControls,ImprovedCookieControls,LazyFrameLoading,MediaRouter,Translate --disable-databases --disable-gpu-compositing --lang=en-US --headless --export-tagged-pdf --num-raster-threads=1 --renderer-client-id=5747 --shared-files=v8_context_snapshot_data:100
```

I think the implementation has some issues with killing the previous process or clearing cache. I have only one check which uses webdriver, with interval every 20 seconds and retrying 3 times before getting alert.
 

### 👟 Reproduction steps

Just setup a chrome check and wait a couple of days.

### 👀 Expected behavior

Not crashing / less cpu usage.

### 😓 Actual Behavior

Crashing and high CPU usage.

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Ubuntu 22.04.3 LTS

### 🌐 Browser

Chromium 90.0.4430.212 (in docker)

### 🐋 Docker Version

Docker version 24.0.6, build ed223bc

**Comment by chakflying** [comment]
Do you have a chart for the RAM used? I'm guessing it ran out of memory and started swapping.

**Comment by Ali-Razmjoo** [comment]
I exported the table on photo via WAZUH XDR, I assume the Size is the memory size, and the virtual server had 4GB of memory. 

Here is hardware information [Hetzner CPX21](https://browser.geekbench.com/v5/cpu/21131822).

**Comment by Ali-Razmjoo** [comment]
I sent a PR that might fix this issue; I had around 40 chrome processes open so I think closing them is a big help.

**Comment by chakflying** [comment]
Running the docker container version, using 1 browser monitor type. Memory usage does slowly increase.

![image](https://github.com/louislam/uptime-kuma/assets/3271800/1c7d2ab5-24fd-4a1c-a38f-a436f9f0b98d)

A group of chromium processes stay running in background. When the monitor heartbeat runs, another group of chromium processes spawn, and die when heartbeat is finished.

|idle|running|
|----|----|
|![image](https://github.com/louislam/uptime-kuma/assets/3271800/e9e7ce04-da81-4779-8cdc-653cdc2934e8)|![image](https://github.com/louislam/uptime-kuma/assets/3271800/17f6847a-1a08-4b97-8fc7-b079aad85ed7)|

**Comment by aliuq** [comment]
same issue, I deployed 3 hours ago, it contains 3 monitors with ` HTTP(s) - Browser Engine (Chrome/Chromium) (Beta) ` and 1 docker monitor

```bash
/usr/lib/chromium/chromium --type=renderer --no-sandbox --disable-dev-shm-usage --disable-background-timer-throttling --disable-breakpad --enable-automation --file-url-path-alias=/gen=/usr/lib/chromium/gen --force-color-profile=srgb --remote-debugging-pipe --allow-pre-commit-input --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --field-trial-handle=14242269732325328734,17121546340593549101,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=AcceptCHFrame,AutoExpandDetailsElement,AvoidUnnecessaryBeforeUnloadCheckSync,CertificateTransparencyComponentUpdater,DestroyProfileOnBrowserClose,DialMediaRouteProvider,GlobalMediaControls,ImprovedCookieControls,LazyFrameLoading,MediaRouter,Translate --disable-databases --lang=en-US --headless --export-tagged-pdf --num-raster-threads=2 -
```

![image](https://github.com/louislam/uptime-kuma/assets/11707934/d4cfe230-7be2-4967-8a86-8d1ba5e0bc2f)

**Comment by panaris** [comment]
same problem on docker desktop

**Comment by devneok** [comment]
Same with me - Older version ran smooth, This new version Very High CPU usage. One there's core it will use all of it.

**Comment by peterbo** [comment]
Same here - Chromium processes eating up all server resources (RAM/CPU/IO) over time. around 4 Headless tests are set up. Server is mostly just for monitoring, so the specs of 4vCores, 16GB RAM should be more than enough.
![kuma-chromium](https://github.com/louislam/uptime-kuma/assets/1018973/cd195c25-0d6b-4df1-af4c-4258f3cc494d)

**Comment by turtur1234** [comment]
I want to add on to this, I just had a system lock/ crash due to what I believe is a chromium based issue. If someone can guide me on how to extract logs from the container, I would love to provide them. I'm running a x86 unraid system w/ 32GB of RAM and uptime kuma ate it all in about 2 minutes.

The logs I do have follow and is all I know how to get now:

`    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:572:22)
    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:558:22)
    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:593:19)
    at async Settings.get (/app/server/settings.js:54:21) {
  sql: 'SELECT `value` FROM setting WHERE `key` = ?  limit ?',
  bindings: [ 'trustProxy', 1 ]
}
    at process.unexpectedErrorHandler (/app/server/server.js:1905:13)
    at process.emit (node:events:517:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:32)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:572:22)
    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:558:22)
    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:593:19)
    at async Settings.get (/app/server/settings.js:54:21) {
  sql: 'SELECT `value` FROM setting WHERE `key` = ?  limit ?',
  bindings: [ 'trustProxy', 1 ]
}
    at process.unexpectedErrorHandler (/app/server/server.js:1905:13)
    at process.emit (node:events:517:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:32)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:572:22)
    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:558:22)
    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:593:19)
    at async Settings.get (/app/server/settings.js:54:21) {
  sql: 'SELECT `value` FROM setting WHERE `key` = ?  limit ?',
  bindings: [ 'trustProxy', 1 ]
}
    at process.unexpectedErrorHandler (/app/server/server.js:1905:13)
    at process.emit (node:events:517:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:32)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:572:22)
    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:558:22)
    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:593:19)
    at async Settings.get (/app/server/settings.js:54:21) {
  sql: 'SELECT `value` FROM setting WHERE `key` = ?  limit ?',
  bindings: [ 'trustProxy', 1 ]
}
    at process.unexpectedErrorHandler (/app/server/server.js:1905:13)
    at process.emit (node:events:517:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:32)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
2024-08-05T13:24:34-05:00 [MONITOR] WARN: Monitor #2 'Uptime Kuma': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 2 | Retry: 1 | Retry Interval: 60 seconds | Type: http`

Additionally here are some screenshots of my grafana dash: 


## CPU Usage
![image](https://github.com/user-attachments/assets/d58ed1e0-0275-4570-af37-158c03e0ef9e)

## Memory Usage
![image](https://github.com/user-attachments/assets/e52dcaa6-2a67-467c-a93d-458be416e4b7)

## Memory Usage Detail:

![image](https://github.com/user-attachments/assets/471f32a2-fc33-4581-94bc-e406b3a3f4f6)


To my untrained eye, it appears that upon container restart (I restart all my containers daily for backup and to try to avoid memory leaks from containers) it began using a weirdly high amount of CPU (20% of my i5), which it continued to use for ~2.5 hrs until it increased from .5gb RAM usage to 17gb in 2 minutes. This is where my system locked up/ crashed. Is there any way to add a hard ram limit for chromium, I would not expect even a power user to want to allocate more then 4-8 gb of RAM to uptime kuma.

**Comment by Problem186Die** [comment]
https://github.com/microsoft/playwright/issues/15400#issuecomment-1709261002

**Comment by mnasruul** [comment]
Yes, I have disabled this browser monitor and killed the process ID using the command `pkill -9 chromium`. I created three Browser Monitors, which consumed around 1GB of memory. After disabling them and killing the process ID, memory usage dropped to around 100-200 MB.

**Comment by SansGuidon** [comment]
I run a Dockerized Uptime Kuma 1.23.16 on Cloudron, with 0.5GB memory allocated.
OS is Ubuntu 24.04.

![Image](https://github.com/user-attachments/assets/5cf05237-6a0c-433c-b4ad-b07021d5c20f)

I first encounter the same Knex timeout issues
```bash
2025-05-13T00:25:57.000Z => Healtheck error: Error: Timeout of 7000ms exceeded
2025-05-13T00:26:04Z 2025-05-13T02:25:48+02:00 [MONITOR] WARN: Monitor #26 'FastMail': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 3 | Retry: 2 | Retry Interval: 60 seconds | Type: keyword
2025-05-13T00:26:07.000Z => Healtheck error: Error: Timeout of 7000ms exceeded
...
2025-05-13T00:27:07.000Z => Healtheck error: Error: Timeout of 7000ms exceeded
2025-05-13T00:27:13Z     at listOnTimeout (node:internal/timers:538:9)
2025-05-13T00:27:13Z     at <REDACTED_DOMAIN> (node:internal/timers:512:7)
2025-05-13T00:27:13Z     at runNextTicks (node:internal/process/task_queues:60:5)
2025-05-13T00:27:13Z Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
2025-05-13T00:27:13Z at <REDACTED_DOMAIN> (/app/code/node_modules/knex/lib/<REDACTED_DOMAIN>:312:26)
2025-05-13T00:27:13Z at <REDACTED_DOMAIN> [as _onTimeout] (/<REDACTED_TOKEN>/<REDACTED_DOMAIN>:1034:25)
2025-05-13T00:27:13Z at async <REDACTED_DOMAIN> (/app/code/node_modules/redbean-node/dist/<REDACTED_DOMAIN>:110:20)
2025-05-13T00:27:13Z at async <REDACTED_DOMAIN> (/app/code/node_modules/redbean-node/dist/<REDACTED_DOMAIN>:150:26)
2025-05-13T00:27:13Z at async <REDACTED_DOMAIN> (/app/code/node_modules/knex/lib/execution/<REDACTED_DOMAIN>:287:28)
2025-05-13T00:27:13Z at async <REDACTED_DOMAIN> (/app/code/node_modules/knex/lib/execution/<REDACTED_DOMAIN>:30:19)
2025-05-13T00:27:13Z at async <REDACTED_DOMAIN> [as _onTimeout] (/app/code/server/model/<REDACTED_DOMAIN>:1032:17) {
2025-05-13T00:27:13Z at async beat (/app/code/server/model/<REDACTED_DOMAIN>:1013:13)
2025-05-13T00:27:13Z at listOnTimeout (node:internal/timers:538:9)
2025-05-13T00:27:13Z at <REDACTED_DOMAIN> (node:internal/timers:512:7)
2025-05-13T00:27:13Z at runNextTicks (node:internal/process/task_queues:60:5)
2025-05-13T00:27:13Z bindings: undefined
2025-05-13T00:27:13Z sql: undefined,
2025-05-13T00:27:13Z }
2025-05-13T00:27:17.000Z => Healtheck error: Error: Timeout of 7000ms exceeded
2025-05-13T00:27:24Z 2025-05-13T02:27:16+02:00 [MONITOR] ERROR: Please report to https://<REDACTED_DOMAIN>/louislam/uptime-kuma/issues
2025-05-13T00:27:27.000Z => Healtheck error: Error: Timeout of 7000ms exceeded
2025-05-13T00:27:37.000Z => Healtheck error: Error: Timeout of 7000ms exceeded
2025-05-13T00:27:47.000Z => Healtheck error: Error: Timeout of 7000ms exceeded
2025-05-13T00:27:53Z 2025-05-13T02:27:24+02:00 [MONITOR] INFO: Try to restart the monitor
2025-05-13T00:27:57.000Z => Healtheck error: Error: Timeout of 7000ms exceeded
2025-05-13T00:28:07.000Z => Healtheck error: Error: Timeout of 7000ms exceeded
2025-05-13T00:28:11Z 2025-05-13T02:28:03+02:00 [MONITOR] WARN: Monitor #5 'Blog': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 3 | Retry: 2 | Retry Interval: 60 seconds | Type: http
2025-05-13T00:28:17.000Z => Healtheck error: Error: Timeout of 7000ms exceeded
...
2025-05-13T00:28:57.000Z => Healtheck error: Error: Timeout of 7000ms exceeded

```


A bit later, real browser/chromium related issues
```bash
2025-05-13T01:15:17.000Z => Healtheck error: Error: Timeout of 7000ms exceeded
2025-05-13T01:15:20Z 2025-05-13T03:15:20+02:00 [MONITOR] WARN: Monitor #25 'Shaarli is browsable': Failing: <REDACTED_DOMAIN>: Timeout 30000ms exceeded.
2025-05-13T01:15:20Z =========================== logs ===========================
2025-05-13T01:15:20Z ============================================================ | Interval: 60 seconds | Type: real-browser | Down Count: 0 | Resend Interval: 0
2025-05-13T01:15:20Z taking page screenshot
2025-05-13T01:18:13Z 2025-05-13T03:18:13+02:00 [MONITOR] WARN: Monitor #25 'Shaarli is browsable': Failing: <REDACTED_DOMAIN>: Timeout 30000ms exceeded.
2025-05-13T01:18:13Z =========================== logs ===========================
2025-05-13T01:18:13Z ============================================================ | Interval: 60 seconds | Type: real-browser | Down Count: 0 | Resend Interval: 0
2025-05-13T01:18:13Z taking page screenshot
2025-05-13T01:18:47Z 2025-05-13T03:18:47+02:00 [MONITOR] WARN: Monitor #4 'Shaarli': Pending: Request failed with status code 500 | Max retries: 3 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2025-05-13T01:19:38Z     at <REDACTED_DOMAIN> (node:events:529:35)
2025-05-13T01:19:38Z     at <REDACTED_DOMAIN> (node:events:631:28)
2025-05-13T01:19:38Z 2025-05-13T03:19:38+02:00 [MONITOR] WARN: Monitor #25 'Shaarli is browsable': Failing: <REDACTED_DOMAIN>: Browser closed.
2025-05-13T01:19:38Z <launched> pid=31197
2025-05-13T01:19:38Z <launching> /usr/bin/chromium --disable-field-trial-config --disable-background-networking --enable-<REDACTED_TOKEN>,<REDACTED_TOKEN> --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-<REDACTED_TOKEN>,LazyFrameLoading,GlobalMediaControls,<REDACTED_TOKEN>,MediaRouter,<REDACTED_TOKEN>,AcceptCHFrame,<REDACTED_TOKEN>,<REDACTED_TOKEN>,<REDACTED_TOKEN>,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-<REDACTED_TOKEN>,<REDACTED_TOKEN>,<REDACTED_TOKEN>,<REDACTED_TOKEN> --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-ZTXo9G --remote-debugging-pipe --no-startup-window
2025-05-13T01:19:38Z ==================== Browser output: ====================
2025-05-13T01:19:38Z If you keep encountering errors, please report to https://<REDACTED_DOMAIN>/louislam/uptime-kuma/issues
2025-05-13T01:19:38Z Trace: Error: Page closed
2025-05-13T01:19:38Z [pid=31197][err]
2025-05-13T01:19:38Z [pid=31197][err]     at CheckVkSuccessImpl (../../chromium-135.0.7049.114/third_party<REDACTED_TOKEN>/<REDACTED_DOMAIN>:106)
2025-05-13T01:19:38Z [pid=31197][err] Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
2025-05-13T01:19:38Z [pid=31197][err] Warning: vkCreateInstance: Found no drivers!
2025-05-13T01:19:38Z [pid=31197][err] [0513/031937.008965:ERROR:<REDACTED_DOMAIN>(145)] open /<REDACTED_TOKEN>scaling_cur_freq: No such file or directory (2)
2025-05-13T01:19:38Z [pid=31197][err] [0513/031937.010557:ERROR:<REDACTED_DOMAIN>(145)] open /<REDACTED_TOKEN>scaling_max_freq: No such file or directory (2) | Interval: 60 seconds | Type: real-browser | Down Count: 0 | Resend Interval: 0
2025-05-13T01:19:38Z [pid=31197][err] [31197:31197:0511/235744.183816:ERROR:<REDACTED_DOMAIN>(589)] Failed to call method: <REDACTED_DOMAIN>: object_path= /<REDACTED_TOKEN>: unknown error type:
2025-05-13T01:19:38Z [pid=31197][err] [31197:31197:0511/235744.187353:ERROR:<REDACTED_DOMAIN>(589)] Failed to call method: <REDACTED_DOMAIN>: object_path= /<REDACTED_TOKEN>: unknown error type:
2025-05-13T01:19:38Z [pid=31197][err] [31197:31197:0511/235744.194959:ERROR:<REDACTED_DOMAIN>(350)] Failed to connect to signal: <REDACTED_DOMAIN>
2025-05-13T01:19:38Z [pid=31197][err] [31197:31197:0511/235744.194981:ERROR:<REDACTED_DOMAIN>(589)] Failed to call method: <REDACTED_DOMAIN>: object_path= /<REDACTED_TOKEN>: unknown error type:
2025-05-13T01:19:38Z [pid=31197][err] [31197:31197:0511/235744.201160:ERROR:<REDACTED_DOMAIN>(589)] Failed to call method: <REDACTED_DOMAIN>: object_path= /<REDACTED_TOKEN>: unknown error type:
2025-05-13T01:19:38Z [pid=31197][err] [31197:31197:0512/000044.208598:ERROR:<REDACTED_DOMAIN>(36)] Unexpected on_device_model service disconnect: The device's GPU is not supported.
2025-05-13T01:19:38Z [pid=31197][err] [31197:31197:0513/022139.403256:ERROR:<REDACTED_DOMAIN>(954)] GPU process exited unexpectedly: exit_code=9
...
2025-05-13T01:19:38Z [pid=31197][err] [31197:31197:0513/031936.838378:FATAL:<REDACTED_DOMAIN>(415)] GPU process isn't usable. Goodbye.
2025-05-13T01:19:38Z [pid=31197][err] [31197:31209:0511/235744.215495:ERROR:<REDACTED_DOMAIN>(48)] Failed to create /home/cloudron/.pki/nssdb directory.
2025-05-13T01:19:38Z [pid=31197][err] [31197:31211:0511/235743.963432:ERROR:<REDACTED_DOMAIN>(408)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2025-05-13T01:19:38Z [pid=31197][err] [31197:31211:0511/235744.005773:ERROR:<REDACTED_DOMAIN>(408)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
...
2025-05-13T01:19:38Z [pid=31197][err] [31197:31214:0511/235743.975818:ERROR:<REDACTED_DOMAIN>(408)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
...
2025-05-13T01:19:38Z [pid=31197][err] [31330:31330:0512/000044.207204:ERROR:<REDACTED_DOMAIN>(119)] Unable to get gpu adapter
2025-05-13T01:19:38Z at /app/code/node_modules/playwright-coreEDACTED_TOKEN>/<REDACTED_DOMAIN>:211:39
2025-05-13T01:19:38Z at CRSession.<anonymous> (/app/code/node_modules/playwright-coreEDACTED_TOKEN>/<REDACTED_DOMAIN>:377:54)
2025-05-13T01:19:38Z at emit (node:<REDACTED_TOKEN>:149:20)
2025-05-13T01:19:38Z at <REDACTED_DOMAIN> (node:events:517:28)
2025-05-13T01:19:38Z at <REDACTED_DOMAIN> (node:internal/process/task_queues:96:32)
2025-05-13T01:19:38Z at <REDACTED_DOMAIN> (/app/code/server/<REDACTED_DOMAIN>:1905:13)
2025-05-13T01:19:38Z at <REDACTED_TOKEN> (node:<REDACTED_TOKEN>:283:27)
```

The app ran out of memory and Cloudron automatically restarted it.
In the meantime, I've followed the best practices recalled here https://github.com/louislam/uptime-kuma/issues/5583#issuecomment-2670945597 and have adapted the monitoring to check every 5 minutes instead of every minute.

I'll monitor if that improves anything.

**Comment by BRJoaquin** [comment]
![Image](https://github.com/user-attachments/assets/352e1c63-031c-4460-ba00-993752bfcee3)

Same here, after a couple of days running fine, last night the server crashed.

**Comment by helloworlde** [comment]
Same issue with me, Chromium using very high io read:

```bash
CONTAINER ID   NAME                CPU %     MEM USAGE / LIMIT   MEM %     NET I/O           BLOCK I/O         PIDS
634e5b7696d2   uptime              7.31%     299.8MiB / 2GiB     14.64%    10.6GB / 1.94GB   1.08GB / 94.1GB   19
008604c494b9   prometheus          0.00%     275.7MiB / 500MiB   55.15%    15GB / 196MB      4.87GB / 1.47GB   11
```

then I enter uptime container, and killed Chromium like this:

```bash
pkill -9 chromium
```

then io recovery to normal.

**Comment by monossido** [comment]
Still an issue after almost 2 years!

**Comment by CommanderStorm** [comment]
@monossido Feel free to investigate where our integration of chromium is bad. Lets remember that Open source is driven by volunteers like you or I ^^

**Comment by falk-miracode** [comment]
Looks to me like @Ali-Razmjoo has identified the problem https://github.com/louislam/uptime-kuma/pull/3791#discussion_r1634668342 (tabs not getting closed) and apparently offered a solution https://github.com/louislam/uptime-kuma/pull/3791/commits/4e667c9adb93aaa6eddb19bf1e617c2d059dfb0d ? But the discussion on the PR somehow stopped.

**Comment by CommanderStorm** [comment]
Feel free to test said PR:

```bash
npx kuma-pr Ali-Razmjoo:fix-browser-high-cpu-issue
```

**Comment by falk-miracode** [comment]
> Feel free to test said PR:
> 
> npx kuma-pr Ali-Razmjoo:fix-browser-high-cpu-issue

I tested it in our server environment (checked out the branch and ran with nixpacks).

I added 10 chromium based monitors with an intervall of 20 secs to quickly see what's going on.

@Ali-Razmjoo s PR seems not to fix it for us. Mem usage raised quickly until the OS started to kill chromium instances. (Docker ressource limits `--memory="1g" --cpu-shares="512"` protected the server from DoS.)

<img width="1497" height="760" alt="Image" src="https://github.com/user-attachments/assets/23b2ac04-8944-47e7-936f-cc223c6a9ba9" />

Thanks for your effort, @CommanderStorm and @Ali-Razmjoo

**Comment by falk-miracode** [comment]
I googled a bit and found, that people on the internet had similar problems with chromium memory leaks with selenium. And some folks claimed, that parallelization within a browser instance was not a good idea and would lead to that instance consuming more and more memory.

So I tried another approach without recycling the browser instance and instead created a new one with every check and closed it after. Although I used BrowserServer.close(), zombie processes remained. So I still needed tree-kill to kill them with fire.

The memory leak was gone. But you can see that creating a browser instance for every check has its price when it comes to CPU usage.

Here the container stats of [my kuma fork](https://github.com/falk-miracode/uptime-kuma/commit/3fa59e3655a1d6e1bb090de5d67fc18441974fc9) with 20 real browser monitorings, each with a 20s interval:

<img width="1549" height="776" alt="Image" src="https://github.com/user-attachments/assets/277ad8c7-e4a7-40a1-99b8-eb05bc287723" />

Maybe it should be configurable (settings or env), if the browser instance should be reused or not.

Another approuch could be a browser pool, where old instances are replaced after a while or after n usages.

Probably next week I'll make pull request.

**Comment by Norbz** [comment]
same here, I am monitoring two client's website every minute, and ended with 24Go of my ram taken by chromium processes.

Stopping them for now ;)

**Comment by SansGuidon** [comment]
> same here, I am monitoring two client's website every minute, and ended with 24Go of my ram taken by chromium processes.
> 
> Stopping them for now ;)

As a workaround I'm relying on changedetection until this feature becomes more mature.

**Comment by Sleywill** [comment]
This is a known issue with self-hosted Chromium — it's inherently memory/CPU-heavy, especially when running multiple concurrent monitors or in containers with limited resources.

One architectural alternative worth considering: instead of running Chromium inside Uptime Kuma's Docker container, offload the browser rendering to an external API. Tools like [SnapAPI](https://snapapi.pics) let you trigger a real browser visit via a simple HTTP request and return the result — so Uptime Kuma's container only makes an API call, not spin up a Chrome instance.

The tradeoff is an external dependency and latency, but for teams where the Chromium CPU/memory is causing actual instability (like here), it's often worth it. Free tier available for moderate usage.

**Comment by CommanderStorm** [comment]
@Sleywill 
We have remote browser as well...

Also please don't pretend that you don't work for that company for which you are doing advertisement for. Given that all your contributions in the last few days are to promote this website, that is a given.

**Comment by SansGuidon** [comment]
> [@SansGuidon](https://github.com/SansGuidon) We have remote browser as well...
> 
> Also please don't pretend that you don't work for that company for which you are doing advertisement for. Given that all your contributions in the last few days are to promote this website, that is a given.

I dont work for CD, but I'm only using it a lot because it has lot of customisable behaviors and out of the box features around drift detection, for which some are useful when UK feels lacking.

**Comment by CommanderStorm** [comment]
Sorry, I pinged the wrong person
