### ISSUE TITLE
My Side is not loading

### ISSUE THREAD

**Issue by amorking1996** [louislam/uptime-kuma#3796]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

http://city-life-roleplay.net:3001/

https://prnt.sc/ZPdNeXfFroPf

### 📝 Error Message(s) or Log

Error: Cannot find module 'node:crypto'
Require stack:
- /root/uptime-kuma/node_modules/@noble/hashes/cryptoNode.js
- /root/uptime-kuma/node_modules/@noble/hashes/utils.js
- /root/uptime-kuma/node_modules/@noble/hashes/_sha2.js
- /root/uptime-kuma/node_modules/@noble/hashes/sha256.js
- /root/uptime-kuma/node_modules/@noble/curves/secp256k1.js
- /root/uptime-kuma/node_modules/nostr-tools/lib/nostr.cjs.js
- /root/uptime-kuma/server/notification-providers/nostr.js
- /root/uptime-kuma/server/notification.js
- /root/uptime-kuma/server/model/monitor.js
- /root/uptime-kuma/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/uptime-kuma/node_modules/@noble/hashes/cryptoNode.js:8:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/uptime-kuma/node_modules/@noble/hashes/cryptoNode.js',
    '/root/uptime-kuma/node_modules/@noble/hashes/utils.js',
    '/root/uptime-kuma/node_modules/@noble/hashes/_sha2.js',
    '/root/uptime-kuma/node_modules/@noble/hashes/sha256.js',
    '/root/uptime-kuma/node_modules/@noble/curves/secp256k1.js',
    '/root/uptime-kuma/node_modules/nostr-tools/lib/nostr.cjs.js',
    '/root/uptime-kuma/server/notification-providers/nostr.js',
    '/root/uptime-kuma/server/notification.js',
    '/root/uptime-kuma/server/model/monitor.js',
    '/root/uptime-kuma/server/server.js'
  ]
}

### 🐻 Uptime-Kuma Version

newst

### 💻 Operating System and Arch

ubuntu 20.04

### 🌐 Browser

firefox

### 🐋 Docker Version

no

### 🟩 NodeJS Version

 v14.16.0

**Comment by louislam** [comment]
Your page is accessible at this moment, I assume that you have fixed it.
