### ISSUE TITLE
CSP error on fresh install

### ISSUE THREAD

**Issue by selfagency** [louislam/uptime-kuma#3806]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

After starting up a fresh install of Uptime Kuma and navigating to the web page, I am greeted with a blank white page and a console error:

![image](https://github.com/louislam/uptime-kuma/assets/2541728/a9e5764e-da16-4e7a-a9f7-8bdd1205a3f1)

### 👟 Reproduction steps

1. `git clone https://github.com/louislam/uptime-kuma.git`
2. `cd uptime-kuma; npm run setup`
3. `sudo pm2 install pm2-logrotate`
4. `sudo pm2 start server/server.js --name uptime-kuma -- --port=8101 --host=127.0.0.1`
5. `sudo vi /etc/nginx/sites-available/uptime.edsapps.cnyric.org.conf`
6. `sudo ln -s /etc/nginx/sites-available/uptime.edsapps.cnyric.org.conf /etc/nginx/sites-enabled/uptime.edsapps.cnyric.org.conf`
7. `sudo systemctl restart nginx`
8. `sudo certbot --nginx`

### 👀 Expected behavior

I expected to see the admin account creation screen, and sure enough, if I use a browser extension to disable the Content Security Policy, everything works as expected.

### 😓 Actual Behavior

Blank screen and console error.

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Ubuntu 22.04.3 x64

### 🌐 Browser

Microsoft Edge for Business 117.0.2045.36 (Official build) (64-bit)

### 🐋 Docker Version

N/A

### 🟩 NodeJS Version

18.17.1

### 📝 Relevant log output

```shell
index-7c277e6c.js:9  Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' http: https: ws: wss: data: blob: 'unsafe-inline'".

    at new Function (<anonymous>)
    at Qg (index-7c277e6c.js:9:48918)
    at Rg (index-7c277e6c.js:9:21416)
    at Ig (index-7c277e6c.js:9:20350)
    at index-7c277e6c.js:9:28949
    at U (index-7c277e6c.js:9:28795)
    at Object.P [as t] (index-7c277e6c.js:9:28936)
    at Object.t (index-7c277e6c.js:9:35124)
    at Proxy.$t (index-7c277e6c.js:9:41751)
    at Proxy.data (index-7c277e6c.js:20:11259)
```

**Comment by louislam** [comment]
Try to access without a reverse proxy, if it is ok. It is your reverse proxy issue. 
Please search `CSP` here for similar issues.
