### ISSUE TITLE
Accessing non-existent property 'testRemoteBrowser' of module exports inside circular dependency

### ISSUE THREAD

**Issue by Zaid-maker** [louislam/uptime-kuma#4149]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

So after the merge of #3904 this error is logged in the console when i start the server, i double check the installation and  build the app as well! but still showing

![image](https://github.com/louislam/uptime-kuma/assets/53424436/e6c20287-8e4a-4045-baf9-03dd23952449)

use `--trace-warnings` flag to dig further in the error!

![image](https://github.com/louislam/uptime-kuma/assets/53424436/034b1e01-85c8-496b-8249-64903b8ce3df)

### 👟 Reproduction steps

Normally start the server with `node server/server.js` as usual

### 👀 Expected behavior

it should work as normal lol

### 😓 Actual Behavior

I pulled new changes and start the server and got this error.

### 🐻 Uptime-Kuma Version

2.0.0-dev

### 💻 Operating System and Arch

Windows 11 x64

### 🌐 Browser

Brave Browser

### 🐋 Docker Version

i dont use docker

### 🟩 NodeJS Version

18.18.2

### 📝 Relevant log output

```shell
(node:2920) Warning: Accessing non-existent property 'testRemoteBrowser' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:836:11)
    at Object.get (node:internal/modules/cjs/loader:852:5)
    at Object.<anonymous> (E:\js-projects\uptime-kuma\server\remote-browser.js:2:9)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (E:\js-projects\uptime-kuma\server\monitor-types\real-browser-monitor-type.js:11:27)
```

**Comment by chakflying** [comment]
@adamhancock I'm guessing the static function `test()` in `server\remote-browser.js` isn't actually needed?
