### ISSUE TITLE
SQLITE_READONLY App do not have access to db

### ISSUE THREAD

**Issue by smiell** [louislam/uptime-kuma#4196]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello after system restart I got error when I am trying to run app via **node server/server.js**.

I am using app through node, not docker container.

I find simmilar issue #2485, but that problem was on Windows...

Output from ls -la command in app directory:
```
[xzihen@zorin uptime-kuma]$ ls -la
total 1040
drwxr-xr-x  16 root root   4096 Dec  8 19:03 .
drwxr-xr-x   3 root root   4096 Dec  8 17:40 ..
drwxr-xr-x   2 root root   4096 Dec  8 17:42 .devcontainer
-rw-r--r--   1 root root    764 Dec  8 17:42 .dockerignore
-rw-r--r--   1 root root    308 Dec  8 17:41 .editorconfig
-rw-r--r--   1 root root   3894 Dec  8 17:42 .eslintrc.js
drwxr-xr-x   8 root root   4096 Dec  9 02:29 .git
drwxr-xr-x   5 root root   4096 Dec  8 17:42 .github
-rw-r--r--   1 root root    269 Dec  8 17:42 .gitignore
-rw-r--r--   1 root root     22 Dec  8 17:41 .npmrc
-rw-r--r--   1 root root    552 Dec  8 17:41 .stylelintrc
-rwxrwxrwx   1 root root     13 Dec  8 17:41 CNAME
-rwxrwxrwx   1 root root   5216 Dec  8 17:41 CODE_OF_CONDUCT.md
-rwxrwxrwx   1 root root  10077 Dec  8 17:42 CONTRIBUTING.md
-rwxrwxrwx   1 root root   1066 Dec  8 17:41 LICENSE
-rwxrwxrwx   1 root root   7285 Dec  8 17:42 README.md
-rwxrwxrwx   1 root root   1328 Dec  8 17:42 SECURITY.md
-rwxrwxrwx   1 root root    127 Dec  8 17:42 babel.config.js
drwxrwxrwx   2 root root   4096 Dec  8 17:42 config
drwxrwxrwx   5 root root   4096 Dec  9 03:02 data
drwxrwxrwx   2 root root   4096 Dec  8 17:42 db
drwxrwxrwx   3 root root   4096 Dec  8 18:38 dist
drwxrwxrwx   3 root root   4096 Dec  8 17:42 docker
-rwxrwxrwx   1 root root    109 Dec  8 17:41 ecosystem.config.js
drwxrwxrwx   5 root root   4096 Dec  8 17:42 extra
-rwxrwxrwx   1 root root   1102 Dec  8 17:41 index.html
-rwxrwxrwx   1 root root   7149 Dec  8 17:42 install.sh
drwxrwxrwx 485 root root  32768 Dec  8 18:36 node_modules
-rwxrwxrwx   1 root root 858112 Dec  8 17:42 package-lock.json
-rwxrwxrwx   1 root root  12553 Dec  8 17:42 package.json
drwxrwxrwx   2 root root   4096 Dec  8 17:41 public
drwxrwxrwx   9 root root   4096 Dec  8 17:42 server
drwxrwxrwx   9 root root   4096 Dec  8 17:42 src
drwxrwxrwx   4 root root   4096 Dec  8 17:42 test
-rwxrwxrwx   1 root root    379 Dec  8 17:42 tsconfig.json
```

### 📝 Error Message(s) or Log

```
[xzihen@zorin uptime-kuma]$ node server/server.js
Welcome to Uptime Kuma
Your Node.js version: 21.4.0
2023-12-09T03:01:57Z [SERVER] INFO: Welcome to Uptime Kuma
2023-12-09T03:01:58Z [SERVER] INFO: Node Env: production
2023-12-09T03:01:58Z [SERVER] INFO: Inside Container: false
2023-12-09T03:01:58Z [SERVER] INFO: Importing Node libraries
2023-12-09T03:01:58Z [SERVER] INFO: Importing 3rd-party libraries
2023-12-09T03:02:40Z [SERVER] INFO: Creating express and socket.io instance
2023-12-09T03:02:40Z [SERVER] INFO: Server Type: HTTP
2023-12-09T03:02:40Z [SERVER] INFO: Importing this project modules
2023-12-09T03:02:45Z [NOTIFICATION] INFO: Prepare Notification Providers
2023-12-09T03:02:45Z [SERVER] INFO: Version: 1.23.8
2023-12-09T03:02:47Z [DB] INFO: Data Dir: ./data/
2023-12-09T03:02:47Z [SERVER] INFO: Connecting to the Database
(node:1669) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2023-12-09T03:02:49Z [DB] INFO: SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
2023-12-09T03:02:49Z [DB] INFO: SQLite Version: 3.41.1
2023-12-09T03:02:49Z [SERVER] INFO: Connected
2023-12-09T03:02:49Z [DB] INFO: Your database version: 10
2023-12-09T03:02:49Z [DB] INFO: Latest database version: 10
2023-12-09T03:02:49Z [DB] INFO: Database patch not needed
2023-12-09T03:02:49Z [DB] INFO: Database Patch 2.0 Process
Trace: [Error: update `setting` set `key` = 'databasePatchedFiles', `value` = '{"patch-setting-value-type.sql":true,"patch-improve-performance.sql":true,"patch-2fa.sql":true,"patch-add-retry-interval-monitor.sql":true,"patch-incident-table.sql":true,"patch-group-table.sql":true,"patch-monitor-push_token.sql":true,"patch-http-monitor-method-body-and-headers.sql":true,"patch-2fa-invalidate-used-token.sql":true,"patch-notification_sent_history.sql":true,"patch-monitor-basic-auth.sql":true,"patch-add-docker-columns.sql":true,"patch-status-page.sql":true,"patch-proxy.sql":true,"patch-monitor-expiry-notification.sql":true,"patch-status-page-footer-css.sql":true,"patch-added-mqtt-monitor.sql":true,"patch-add-clickable-status-page-link.sql":true,"patch-add-sqlserver-monitor.sql":true,"patch-add-other-auth.sql":true,"patch-grpc-monitor.sql":true,"patch-add-radius-monitor.sql":true,"patch-monitor-add-resend-interval.sql":true,"patch-ping-packet-size.sql":true,"patch-maintenance-table2.sql":true,"patch-add-gamedig-monitor.sql":true,"patch-add-google-analytics-status-page-tag.sql":true,"patch-http-body-encoding.sql":true,"patch-add-description-monitor.sql":true,"patch-api-key-table.sql":true,"patch-monitor-tls.sql":true,"patch-maintenance-cron.sql":true,"patch-add-parent-monitor.sql":true,"patch-add-invert-keyword.sql":true,"patch-added-json-query.sql":true,"patch-added-kafka-producer.sql":true,"patch-add-certificate-expiry-status-page.sql":true,"patch-monitor-oauth-cc.sql":true,"patch-add-timeout-monitor.sql":true,"patch-add-gamedig-given-port.sql":true,"patch-notification-config.sql":true,"patch-fix-kafka-producer-booleans.sql":true,"patch-timeout.sql":true}', `type` = NULL where `id` = 2 - SQLITE_READONLY: attempt to write a readonly database] {
  errno: 8,
  code: 'SQLITE_READONLY'
}
    at process.unexpectedErrorHandler (/etc/uptime-kuma/uptime-kuma/server/server.js:1895:13)
    at process.emit (node:events:519:28)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
^C2023-12-09T03:05:23Z [SERVER] INFO: Shutdown requested
2023-12-09T03:05:23Z [SERVER] INFO: Called signal: SIGINT
Trace: Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at Server.close (node:net:2219:12)
    at Object.onceWrapper (node:events:633:28)
    at Server.emit (node:events:531:35)
    at emitCloseNT (node:net:2279:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'ERR_SERVER_NOT_RUNNING'
}
    at process.unexpectedErrorHandler (/etc/uptime-kuma/uptime-kuma/server/server.js:1895:13)
    at process.emit (node:events:519:28)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
2023-12-09T03:05:24Z [SERVER] INFO: Stopping all monitors
^C2023-12-09T03:05:26Z [DB] INFO: Closing the database
^C2023-12-09T03:05:28Z [DB] INFO: SQLite closed
2023-12-09T03:05:28Z [CLOUDFLARED] INFO: Stop cloudflared
2023-12-09T03:05:28Z [SERVER] INFO: Graceful shutdown successful!

```

### 🐻 Uptime-Kuma Version

1.23.8

### 💻 Operating System and Arch

Arch linux ARM

### 🌐 Browser

Google Chrome 119.0.6045.200

### 🟩 NodeJS Version

21.4.0

**Comment by CommanderStorm** [comment]
The errror message means that the db is not writable.
Could you try writing to the disk? Is it maybe full?

**Comment by smiell** [comment]
I think it is not problem with free space on disk. I have free ~25GB space at least.

The problem was schown when I changed the ownership all files in this directory from root to uptime-kuma.

**Comment by smiell** [comment]
Okay, I solved the problem maybe a little bit, but it worked.

I cloned the repository again and copied the **/data/kuma.db** file from my old instance to the new one. The application started without a problem, so it seems that the problem was **related to the permissions of the kuma.db** file.
