### ISSUE TITLE
SQL Error upon monitor ping database insert

### ISSUE THREAD

**Issue by Zandor300** [louislam/uptime-kuma#4315]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I am running v2 on a test server and receiving the following error.

```
Trace: Error: insert into `stat_daily` (`down`, `monitor_id`, `ping`, `timestamp`, `up`) values (0, 2, DEFAULT, 1704240000, 1) - Field 'ping' doesn't have a default value
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Readable.push (node:internal/streams/readable:253:10) {
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlState: 'HY000',
  sqlMessage: "Field 'ping' doesn't have a default value",
  sql: 'insert into `stat_daily` (`down`, `monitor_id`, `ping`, `timestamp`, `up`) values (0, 2, DEFAULT, 1704240000, 1)'
}
    at safeBeat (/app/server/model/monitor.js:1002:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Frontend status of monitor is `N/a` in sidebar and detail page shows `unknown`.

<img width="2024" alt="Screenshot 2024-01-03 at 12 35 41" src="https://github.com/louislam/uptime-kuma/assets/6069593/9c6ce147-f6b4-49f3-ae32-741d0457e15b">

### 👟 Reproduction steps

Running nightly2 on Docker using image: `sha256:3718341372ae260a3c9c7d6d79abad47aa6ff1cf7e960e97508b0d78f5da7e98 `

Using following command to start:

```
docker run -d \
  --restart=always \
  -p 3001:3001 \
  -v uptime-kuma:/app/data \
  --name uptime-kuma louislam/uptime-kuma:nightly2
```

And setup a clean Uptime kuma instance using embedded MariaDB.

Then created a PING monitor pinging to a website and looked at the Docker image logs: `docker logs -f uptime-kuma`

### 👀 Expected behavior

It should insert just fine.

### 😓 Actual Behavior

Error message in Docker container output and no status is actually shown. See screenshot above.

### 🐻 Uptime-Kuma Version

v2

### 💻 Operating System and Arch

Ubuntu 22.04.2 LTS

### 🌐 Browser

Chrome 120.0.6099.71

### 🐋 Docker Version

Docker version 24.0.6, build ed223bc

### 🟩 NodeJS Version

Docker image

### 📝 Relevant log output

```shell
Trace: Error: insert into `stat_daily` (`down`, `monitor_id`, `ping`, `timestamp`, `up`) values (0, 2, DEFAULT, 1704240000, 1) - Field 'ping' doesn't have a default value
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Readable.push (node:internal/streams/readable:253:10) {
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlState: 'HY000',
  sqlMessage: "Field 'ping' doesn't have a default value",
  sql: 'insert into `stat_daily` (`down`, `monitor_id`, `ping`, `timestamp`, `up`) values (0, 2, DEFAULT, 1704240000, 1)'
}
    at safeBeat (/app/server/model/monitor.js:1002:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by felipewnp** [comment]
@Zandor300 @CommanderStorm 

I couldn't replicate this issue locally.

I've tested with `nightly2` and `2.0.0-beta.4`.

Can any of you try again to replicate this issue?

**Comment by louislam** [comment]
https://github.com/louislam/uptime-kuma/blob/023079733a2697f6544616e56225eff6de77060b/server/model/monitor.js#L979

I guess maybe the ping is not numeric, and an `NaN` (after parseFloat) passed to this function which triggered this bug.
