### ISSUE TITLE
Problems trying to monitor my company's internal website

### ISSUE THREAD

**Issue by ansleyzheth** [louislam/uptime-kuma#4610]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm having some problems trying to monitor my company's internal website

When having to monitor the website https://production.siagri.com.br/simer/auth/login

The same error occurs.

I'm using these settings

![image](https://github.com/louislam/uptime-kuma/assets/45273232/b581a120-1b1f-4c24-98ae-0a3b0ce6b08a)

![image](https://github.com/louislam/uptime-kuma/assets/45273232/aa7f8e1c-973d-4e45-9d27-1da437d7bef4)

This is my docker-compose.yaml

```
# Simple docker-compose.yml
# You can change your port or volume location

version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 30001:3001  # <Host Port>:<Container Port>
    restart: always
```
    
In Uptime Kuma's Live Demo it worked

![image](https://github.com/louislam/uptime-kuma/assets/45273232/6ff7e3ec-7e0f-41de-b2c0-461898b5f3e0)

Do I need to add a DNS?
Because I'm using the internal IP where this application is on the site's docker

### 📝 Error Message(s) or Log

I have this log file along with my docker-compose.yaml

```
/opt/uptime-kuma/uptime-kuma-data$ cat error.log
[2024-03-20 14:57:12] [Error: insert into `heartbeat` (`down_count`, `duration`, `important`, `monitor_id`, `msg`, `status`, `time`) values (0, 0, true, 17, 'page.goto: net::ERR_CERT_AUTHORITY_INVALID at https://release.siagri.com.br/simer/auth/login
=========================== logs ===========================
navigating to "https://release.siagri.com.br/simer/auth/login", waiting until "networkidle"
============================================================', 0, '2024-03-20 17:54:50.096') - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed] {
  errno: 19,
  code: 'SQLITE_CONSTRAINT'
}
[2024-03-20 17:42:18] KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:572:22)
    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:558:22)
    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:593:19)
    at async Monitor.sendAvgPing (/app/server/model/monitor.js:1203:32) {
  sql: '\n' +
    '            SELECT AVG(ping)\n' +
    '            FROM heartbeat\n' +
    "            WHERE time > DATETIME('now', ? || ' hours')\n" +
    '            AND ping IS NOT NULL\n' +
    '            AND monitor_id = ?  limit ?',
  bindings: [ -24, 7, 1 ]
}
[2024-03-20 17:42:18] KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:572:22)
    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:558:22)
    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:593:19)
    at async Monitor.sendAvgPing (/app/server/model/monitor.js:1203:32) {
  sql: '\n' +
    '            SELECT AVG(ping)\n' +
    '            FROM heartbeat\n' +
    "            WHERE time > DATETIME('now', ? || ' hours')\n" +
    '            AND ping IS NOT NULL\n' +
    '            AND monitor_id = ?  limit ?',
  bindings: [ -24, 22, 1 ]
}
[2024-03-20 17:42:18] KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.storeCore (/app/node_modules/redbean-node/dist/redbean-node.js:150:26)
    at async RedBeanNode.store (/app/node_modules/redbean-node/dist/redbean-node.js:110:20)
    at async beat (/app/server/model/monitor.js:1007:13)
    at async Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1026:17) {
  sql: undefined,
  bindings: undefined
}
[2024-03-20 17:42:18] KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async RedBeanNode.storeCore (/app/node_modules/redbean-node/dist/redbean-node.js:150:26)
    at async RedBeanNode.store (/app/node_modules/redbean-node/dist/redbean-node.js:110:20)
    at async beat (/app/server/model/monitor.js:1007:13)
    at async Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1026:17) {
  sql: undefined,
  bindings: undefined
}

```

### 🐻 Uptime-Kuma Version

Version: 1.23.11

### 💻 Operating System and Arch

Ubuntu 20.04.6 LTS

### 🌐 Browser

Brave 1.64.109

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
The `Knex: Timeout acquiring a connection` are a pretty good sign that you are running into the pefromance "limits" (~500 montirs, 1.5GB see https://github.com/louislam/uptime-kuma/issues/4500 for further detials) of v1.

Could you report the details about your `Deployment Environment` in above form?
Especially: what is your retention, how long have you run uptime kuma for?

About the link you shared:
Given that the first certificate in the chain is invalid, you need to disable certificate checking.
![image](https://github.com/louislam/uptime-kuma/assets/26258709/2e5f5890-19ae-4643-90ef-9425ae9f6d56)
