### ISSUE TITLE
how do I add my certificate to uptime-kuma

### ISSUE THREAD

**Issue by ansleyzheth** [louislam/uptime-kuma#4649]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello everyone, everything good?

![image](https://github.com/louislam/uptime-kuma/assets/45273232/a4cb2c53-ac1f-426b-8d64-589f59fe93b7)

I'm trying to add my certificate to uptime-kuma but I can't, can you help?

![image](https://github.com/louislam/uptime-kuma/assets/45273232/1afe46ef-b786-4418-bf73-a2924d64a943)

I tried using this way

<details><summary><code>docker-compose.yaml</code></summary>
<p>

```yaml
version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    environment:
      NODE_EXTRA_CA_CERTS: /opt/uptime-kuma/certificados/tls.cert.pem
    volumes:
      - /docker-vol/uptime-kuma:/app/data
      - /opt/uptime-kuma/certificados:/opt/uptime-kuma/certificados
    ports:
      - 30001:3001
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
```

</p>
</details> 

this way

<details><summary><code>docker-compose.yaml</code></summary>
<p>

```yaml
version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - ./certificados:/certificados
    ports:
      - 30001:3001
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
```

</p>
</details> 

and this way

<details><summary><code>docker-compose.yaml</code></summary>
<p>

```yaml
# teste certificado
version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - /docker-vol/uptime-kuma:/app/data
      - /opt/uptime-kuma/certificados:/certs:ro
    environment:
      - UPTIME_KUMA_SSL_KEY=/certs/key-si.pem
      - UPTIME_KUMA_SSL_CERT=/certs/tls.cert.pem
    ports:
      - 30001:3001
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
```

</p>
</details> 

<details><summary><h3>📝 Error Message(s) or Log</h3></summary>
<p>

```raw
docker logs uptime-kuma
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Your Node.js version: 18.19.0
2024-04-04T12:35:19Z [SERVER] INFO: Welcome to Uptime Kuma
2024-04-04T12:35:19Z [SERVER] INFO: Node Env: production
2024-04-04T12:35:19Z [SERVER] INFO: Inside Container: true
2024-04-04T12:35:19Z [SERVER] INFO: Importing Node libraries
2024-04-04T12:35:19Z [SERVER] INFO: Importing 3rd-party libraries
2024-04-04T12:35:21Z [SERVER] INFO: Creating express and socket.io instance
2024-04-04T12:35:21Z [SERVER] INFO: Server Type: HTTPS
node:internal/tls/secure-context:93
  context.setKey(key, passphrase);
          ^

Error: error:1C800064:Provider routines::bad decrypt
    at setKey (node:internal/tls/secure-context:93:11)
    at configSecureContext (node:internal/tls/secure-context:175:7)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1471:27)
    at Server (node:_tls_wrap:1335:8)
    at new Server (node:https:76:3)
    at Object.createServer (node:https:120:10)
    at new UptimeKumaServer (/app/server/uptime-kuma-server.js:78:37)
    at UptimeKumaServer.getInstance (/app/server/uptime-kuma-server.js:68:41)
    at Object.<anonymous> (/app/server/server.js:87:33) {
  opensslErrorStack: [
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error',
    'error:1C800064:Provider routines::bad decrypt',
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error'
  ],
  library: 'Provider routines',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_BAD_DECRYPT'
}

Node.js v18.19.0
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Your Node.js version: 18.19.0
2024-04-04T12:35:23Z [SERVER] INFO: Welcome to Uptime Kuma
2024-04-04T12:35:23Z [SERVER] INFO: Node Env: production
2024-04-04T12:35:23Z [SERVER] INFO: Inside Container: true
2024-04-04T12:35:23Z [SERVER] INFO: Importing Node libraries
2024-04-04T12:35:23Z [SERVER] INFO: Importing 3rd-party libraries
2024-04-04T12:35:25Z [SERVER] INFO: Creating express and socket.io instance
2024-04-04T12:35:25Z [SERVER] INFO: Server Type: HTTPS
node:internal/tls/secure-context:93
  context.setKey(key, passphrase);
          ^

Error: error:1C800064:Provider routines::bad decrypt
    at setKey (node:internal/tls/secure-context:93:11)
    at configSecureContext (node:internal/tls/secure-context:175:7)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1471:27)
    at Server (node:_tls_wrap:1335:8)
    at new Server (node:https:76:3)
    at Object.createServer (node:https:120:10)
    at new UptimeKumaServer (/app/server/uptime-kuma-server.js:78:37)
    at UptimeKumaServer.getInstance (/app/server/uptime-kuma-server.js:68:41)
    at Object.<anonymous> (/app/server/server.js:87:33) {
  opensslErrorStack: [
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error',
    'error:1C800064:Provider routines::bad decrypt',
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error'
  ],
  library: 'Provider routines',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_BAD_DECRYPT'
}

Node.js v18.19.0
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Your Node.js version: 18.19.0
2024-04-04T12:35:26Z [SERVER] INFO: Welcome to Uptime Kuma
2024-04-04T12:35:26Z [SERVER] INFO: Node Env: production
2024-04-04T12:35:26Z [SERVER] INFO: Inside Container: true
2024-04-04T12:35:26Z [SERVER] INFO: Importing Node libraries
2024-04-04T12:35:26Z [SERVER] INFO: Importing 3rd-party libraries
2024-04-04T12:35:28Z [SERVER] INFO: Creating express and socket.io instance
2024-04-04T12:35:28Z [SERVER] INFO: Server Type: HTTPS
node:internal/tls/secure-context:93
  context.setKey(key, passphrase);
          ^

Error: error:1C800064:Provider routines::bad decrypt
    at setKey (node:internal/tls/secure-context:93:11)
    at configSecureContext (node:internal/tls/secure-context:175:7)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1471:27)
    at Server (node:_tls_wrap:1335:8)
    at new Server (node:https:76:3)
    at Object.createServer (node:https:120:10)
    at new UptimeKumaServer (/app/server/uptime-kuma-server.js:78:37)
    at UptimeKumaServer.getInstance (/app/server/uptime-kuma-server.js:68:41)
    at Object.<anonymous> (/app/server/server.js:87:33) {
  opensslErrorStack: [
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error',
    'error:1C800064:Provider routines::bad decrypt',
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error'
  ],
  library: 'Provider routines',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_BAD_DECRYPT'
}

Node.js v18.19.0
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Your Node.js version: 18.19.0
2024-04-04T12:35:30Z [SERVER] INFO: Welcome to Uptime Kuma
2024-04-04T12:35:30Z [SERVER] INFO: Node Env: production
2024-04-04T12:35:30Z [SERVER] INFO: Inside Container: true
2024-04-04T12:35:30Z [SERVER] INFO: Importing Node libraries
2024-04-04T12:35:30Z [SERVER] INFO: Importing 3rd-party libraries
2024-04-04T12:35:32Z [SERVER] INFO: Creating express and socket.io instance
2024-04-04T12:35:32Z [SERVER] INFO: Server Type: HTTPS
node:internal/tls/secure-context:93
  context.setKey(key, passphrase);
          ^

Error: error:1C800064:Provider routines::bad decrypt
    at setKey (node:internal/tls/secure-context:93:11)
    at configSecureContext (node:internal/tls/secure-context:175:7)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1471:27)
    at Server (node:_tls_wrap:1335:8)
    at new Server (node:https:76:3)
    at Object.createServer (node:https:120:10)
    at new UptimeKumaServer (/app/server/uptime-kuma-server.js:78:37)
    at UptimeKumaServer.getInstance (/app/server/uptime-kuma-server.js:68:41)
    at Object.<anonymous> (/app/server/server.js:87:33) {
  opensslErrorStack: [
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error',
    'error:1C800064:Provider routines::bad decrypt',
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error'
  ],
  library: 'Provider routines',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_BAD_DECRYPT'
}

Node.js v18.19.0
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Your Node.js version: 18.19.0
2024-04-04T12:35:34Z [SERVER] INFO: Welcome to Uptime Kuma
2024-04-04T12:35:34Z [SERVER] INFO: Node Env: production
2024-04-04T12:35:34Z [SERVER] INFO: Inside Container: true
2024-04-04T12:35:34Z [SERVER] INFO: Importing Node libraries
2024-04-04T12:35:34Z [SERVER] INFO: Importing 3rd-party libraries
2024-04-04T12:35:36Z [SERVER] INFO: Creating express and socket.io instance
2024-04-04T12:35:36Z [SERVER] INFO: Server Type: HTTPS
node:internal/tls/secure-context:93
  context.setKey(key, passphrase);
          ^

Error: error:1C800064:Provider routines::bad decrypt
    at setKey (node:internal/tls/secure-context:93:11)
    at configSecureContext (node:internal/tls/secure-context:175:7)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1471:27)
    at Server (node:_tls_wrap:1335:8)
    at new Server (node:https:76:3)
    at Object.createServer (node:https:120:10)
    at new UptimeKumaServer (/app/server/uptime-kuma-server.js:78:37)
    at UptimeKumaServer.getInstance (/app/server/uptime-kuma-server.js:68:41)
    at Object.<anonymous> (/app/server/server.js:87:33) {
  opensslErrorStack: [
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error',
    'error:1C800064:Provider routines::bad decrypt',
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error'
  ],
  library: 'Provider routines',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_BAD_DECRYPT'
}

Node.js v18.19.0
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Your Node.js version: 18.19.0
2024-04-04T12:35:39Z [SERVER] INFO: Welcome to Uptime Kuma
2024-04-04T12:35:39Z [SERVER] INFO: Node Env: production
2024-04-04T12:35:39Z [SERVER] INFO: Inside Container: true
2024-04-04T12:35:39Z [SERVER] INFO: Importing Node libraries
2024-04-04T12:35:39Z [SERVER] INFO: Importing 3rd-party libraries
2024-04-04T12:35:41Z [SERVER] INFO: Creating express and socket.io instance
2024-04-04T12:35:41Z [SERVER] INFO: Server Type: HTTPS
node:internal/tls/secure-context:93
  context.setKey(key, passphrase);
          ^

Error: error:1C800064:Provider routines::bad decrypt
    at setKey (node:internal/tls/secure-context:93:11)
    at configSecureContext (node:internal/tls/secure-context:175:7)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1471:27)
    at Server (node:_tls_wrap:1335:8)
    at new Server (node:https:76:3)
    at Object.createServer (node:https:120:10)
    at new UptimeKumaServer (/app/server/uptime-kuma-server.js:78:37)
    at UptimeKumaServer.getInstance (/app/server/uptime-kuma-server.js:68:41)
    at Object.<anonymous> (/app/server/server.js:87:33) {
  opensslErrorStack: [
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error',
    'error:1C800064:Provider routines::bad decrypt',
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error'
  ],
  library: 'Provider routines',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_BAD_DECRYPT'
}

Node.js v18.19.0
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Your Node.js version: 18.19.0
2024-04-04T12:35:45Z [SERVER] INFO: Welcome to Uptime Kuma
2024-04-04T12:35:45Z [SERVER] INFO: Node Env: production
2024-04-04T12:35:45Z [SERVER] INFO: Inside Container: true
2024-04-04T12:35:45Z [SERVER] INFO: Importing Node libraries
2024-04-04T12:35:45Z [SERVER] INFO: Importing 3rd-party libraries
2024-04-04T12:35:47Z [SERVER] INFO: Creating express and socket.io instance
2024-04-04T12:35:47Z [SERVER] INFO: Server Type: HTTPS
node:internal/tls/secure-context:93
  context.setKey(key, passphrase);
          ^

Error: error:1C800064:Provider routines::bad decrypt
    at setKey (node:internal/tls/secure-context:93:11)
    at configSecureContext (node:internal/tls/secure-context:175:7)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1471:27)
    at Server (node:_tls_wrap:1335:8)
    at new Server (node:https:76:3)
    at Object.createServer (node:https:120:10)
    at new UptimeKumaServer (/app/server/uptime-kuma-server.js:78:37)
    at UptimeKumaServer.getInstance (/app/server/uptime-kuma-server.js:68:41)
    at Object.<anonymous> (/app/server/server.js:87:33) {
  opensslErrorStack: [
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error',
    'error:1C800064:Provider routines::bad decrypt',
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error'
  ],
  library: 'Provider routines',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_BAD_DECRYPT'
}

Node.js v18.19.0
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Your Node.js version: 18.19.0
2024-04-04T12:35:55Z [SERVER] INFO: Welcome to Uptime Kuma
2024-04-04T12:35:55Z [SERVER] INFO: Node Env: production
2024-04-04T12:35:55Z [SERVER] INFO: Inside Container: true
2024-04-04T12:35:55Z [SERVER] INFO: Importing Node libraries
2024-04-04T12:35:55Z [SERVER] INFO: Importing 3rd-party libraries
2024-04-04T12:35:57Z [SERVER] INFO: Creating express and socket.io instance
2024-04-04T12:35:57Z [SERVER] INFO: Server Type: HTTPS
node:internal/tls/secure-context:93
  context.setKey(key, passphrase);
          ^

Error: error:1C800064:Provider routines::bad decrypt
    at setKey (node:internal/tls/secure-context:93:11)
    at configSecureContext (node:internal/tls/secure-context:175:7)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1471:27)
    at Server (node:_tls_wrap:1335:8)
    at new Server (node:https:76:3)
    at Object.createServer (node:https:120:10)
    at new UptimeKumaServer (/app/server/uptime-kuma-server.js:78:37)
    at UptimeKumaServer.getInstance (/app/server/uptime-kuma-server.js:68:41)
    at Object.<anonymous> (/app/server/server.js:87:33) {
  opensslErrorStack: [
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error',
    'error:1C800064:Provider routines::bad decrypt',
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error'
  ],
  library: 'Provider routines',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_BAD_DECRYPT'
}

Node.js v18.19.0
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Your Node.js version: 18.19.0
2024-04-04T12:36:11Z [SERVER] INFO: Welcome to Uptime Kuma
2024-04-04T12:36:11Z [SERVER] INFO: Node Env: production
2024-04-04T12:36:11Z [SERVER] INFO: Inside Container: true
2024-04-04T12:36:11Z [SERVER] INFO: Importing Node libraries
2024-04-04T12:36:11Z [SERVER] INFO: Importing 3rd-party libraries
2024-04-04T12:36:13Z [SERVER] INFO: Creating express and socket.io instance
2024-04-04T12:36:13Z [SERVER] INFO: Server Type: HTTPS
node:internal/tls/secure-context:93
  context.setKey(key, passphrase);
          ^

Error: error:1C800064:Provider routines::bad decrypt
    at setKey (node:internal/tls/secure-context:93:11)
    at configSecureContext (node:internal/tls/secure-context:175:7)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1471:27)
    at Server (node:_tls_wrap:1335:8)
    at new Server (node:https:76:3)
    at Object.createServer (node:https:120:10)
    at new UptimeKumaServer (/app/server/uptime-kuma-server.js:78:37)
    at UptimeKumaServer.getInstance (/app/server/uptime-kuma-server.js:68:41)
    at Object.<anonymous> (/app/server/server.js:87:33) {
  opensslErrorStack: [
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error',
    'error:1C800064:Provider routines::bad decrypt',
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error'
  ],
  library: 'Provider routines',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_BAD_DECRYPT'
}

Node.js v18.19.0
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Your Node.js version: 18.19.0
2024-04-04T12:36:40Z [SERVER] INFO: Welcome to Uptime Kuma
2024-04-04T12:36:40Z [SERVER] INFO: Node Env: production
2024-04-04T12:36:40Z [SERVER] INFO: Inside Container: true
2024-04-04T12:36:40Z [SERVER] INFO: Importing Node libraries
2024-04-04T12:36:40Z [SERVER] INFO: Importing 3rd-party libraries
2024-04-04T12:36:42Z [SERVER] INFO: Creating express and socket.io instance
2024-04-04T12:36:42Z [SERVER] INFO: Server Type: HTTPS
node:internal/tls/secure-context:93
  context.setKey(key, passphrase);
          ^

Error: error:1C800064:Provider routines::bad decrypt
    at setKey (node:internal/tls/secure-context:93:11)
    at configSecureContext (node:internal/tls/secure-context:175:7)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1471:27)
    at Server (node:_tls_wrap:1335:8)
    at new Server (node:https:76:3)
    at Object.createServer (node:https:120:10)
    at new UptimeKumaServer (/app/server/uptime-kuma-server.js:78:37)
    at UptimeKumaServer.getInstance (/app/server/uptime-kuma-server.js:68:41)
    at Object.<anonymous> (/app/server/server.js:87:33) {
  opensslErrorStack: [
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error',
    'error:1C800064:Provider routines::bad decrypt',
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error'
  ],
  library: 'Provider routines',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_BAD_DECRYPT'
}

Node.js v18.19.0
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Your Node.js version: 18.19.0
2024-04-04T12:37:34Z [SERVER] INFO: Welcome to Uptime Kuma
2024-04-04T12:37:34Z [SERVER] INFO: Node Env: production
2024-04-04T12:37:34Z [SERVER] INFO: Inside Container: true
2024-04-04T12:37:34Z [SERVER] INFO: Importing Node libraries
2024-04-04T12:37:34Z [SERVER] INFO: Importing 3rd-party libraries
2024-04-04T12:37:36Z [SERVER] INFO: Creating express and socket.io instance
2024-04-04T12:37:36Z [SERVER] INFO: Server Type: HTTPS
node:internal/tls/secure-context:93
  context.setKey(key, passphrase);
          ^

Error: error:1C800064:Provider routines::bad decrypt
    at setKey (node:internal/tls/secure-context:93:11)
    at configSecureContext (node:internal/tls/secure-context:175:7)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1471:27)
    at Server (node:_tls_wrap:1335:8)
    at new Server (node:https:76:3)
    at Object.createServer (node:https:120:10)
    at new UptimeKumaServer (/app/server/uptime-kuma-server.js:78:37)
    at UptimeKumaServer.getInstance (/app/server/uptime-kuma-server.js:68:41)
    at Object.<anonymous> (/app/server/server.js:87:33) {
  opensslErrorStack: [
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error',
    'error:1C800064:Provider routines::bad decrypt',
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error'
  ],
  library: 'Provider routines',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_BAD_DECRYPT'
}

Node.js v18.19.0
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Your Node.js version: 18.19.0
2024-04-04T12:38:37Z [SERVER] INFO: Welcome to Uptime Kuma
2024-04-04T12:38:37Z [SERVER] INFO: Node Env: production
2024-04-04T12:38:37Z [SERVER] INFO: Inside Container: true
2024-04-04T12:38:37Z [SERVER] INFO: Importing Node libraries
2024-04-04T12:38:37Z [SERVER] INFO: Importing 3rd-party libraries
2024-04-04T12:38:39Z [SERVER] INFO: Creating express and socket.io instance
2024-04-04T12:38:39Z [SERVER] INFO: Server Type: HTTPS
node:internal/tls/secure-context:93
  context.setKey(key, passphrase);
          ^

Error: error:1C800064:Provider routines::bad decrypt
    at setKey (node:internal/tls/secure-context:93:11)
    at configSecureContext (node:internal/tls/secure-context:175:7)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Server.setSecureContext (node:_tls_wrap:1471:27)
    at Server (node:_tls_wrap:1335:8)
    at new Server (node:https:76:3)
    at Object.createServer (node:https:120:10)
    at new UptimeKumaServer (/app/server/uptime-kuma-server.js:78:37)
    at UptimeKumaServer.getInstance (/app/server/uptime-kuma-server.js:68:41)
    at Object.<anonymous> (/app/server/server.js:87:33) {
  opensslErrorStack: [
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error',
    'error:1C800064:Provider routines::bad decrypt',
    'error:11800074:PKCS12 routines::pkcs12 cipherfinal error'
  ],
  library: 'Provider routines',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_BAD_DECRYPT'
}
```

</p>
</details> 

Node.js v18.19.0

### 🐻 Uptime-Kuma Version

Versão: 1.23.11

### 💻 Operating System and Arch

CentOS Linux 7 (Core)

### 🌐 Browser

Version 1.64.113 Chromium: 123.0.6312.86 

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
Okay, the middle configuration clearly does not work as it does not have any certificates configured.

The top one you added `NODE_EXTRA_CA_CERTS` and in the bottom one you added `UPTIME_KUMA_SSL_{KEY,CERT}`. You have not addded `UPTIME_KUMA_SSL_KEY_PASSPHRASE` (is a passphrase set?) for the bottom one.

I don't know which one of these the logs belongs to, but from the log it says that you have not provided a valid/decryptable cert given the key+passphrase.
Have you made sure that the cert are valid? How did you generate the certificate?

**Comment by ansleyzheth** [comment]
Hello

I removed the password from the certificate

`openssl pkcs12 -in certificate.pfx -out key.pem -nodes -passin pass:your_password
`
`openssl pkcs12 -in siagri.com2024.pfx -out cert.pem -nodes
`

and configured nginx

`sudo vi /etc/nginx/sites-available/uptime-kuma.conf
`

```
server  {
    listen 80;
    server_name    your_domain_here;
    location / {
        proxy_pass         http://localhost:8001;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host $host;
    }
}
```

`sudo ln -s /etc/nginx/sites-available/uptime-kuma.conf /etc/nginx/sites-enabled/
# Check the config file
sudo nginx -t
#reload nginx so configs to be in place
sudo systemctl reload nginx`

Create the SSL Certificate

`sudo apt install certbot python3-certbot-nginx
`
`sudo certbot --nginx -d your_domain_here
`

**Comment by ansleyzheth** [comment]
Thanks for help :D

**Comment by j796160836** [comment]
Here is my `docker-compose.yml` for your reference.

```yaml
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    restart: always
    environment:
      - NODE_EXTRA_CA_CERTS=/opt/your_ca.crt
    ports:
      - 3001:3001
    volumes:
      - ./uptime-kuma-data:/app/data
      - ./your_ca.crt:/opt/your_ca.crt:ro
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "2m"
```
