### ISSUE TITLE
`UP` notification without `DOWN` if retries > 0

### ISSUE THREAD

**Issue by geri777** [louislam/uptime-kuma#4792]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have set the "retries" option to "2". So I don't get any notification for single heartbeat failures.
But now I seem to receive "UP" notifications for single failures. 
These are my settings:

![image](https://github.com/louislam/uptime-kuma/assets/4689190/76ee0063-8286-49f7-b610-8ad67dc1413e)

This is the result from the log:

![image](https://github.com/louislam/uptime-kuma/assets/4689190/b5d51fd9-8eca-4ca9-b7c6-41c8e7d62147)
("Externe" and "All-Inkl" are Groups, I don't send notifications for those)

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu 22

### 🌐 Browser

Chrome 

### 🖥️ Deployment Environment

- Runtime:  Docker
- Database: don't know.
- Filesystem used to store the database on: don't know.
- number of monitors: 10

**Comment by geri777** [comment]
ok, thank you very much - your hint with the log file helped a lot.
The mailserver I am using and the sites which show DOWN from time to time are hosted in the same location.
It looks to me, that there are short outages which also affect the mailserver connection. This is why I don't get the DOWN emails. Need to look for a 3rd party email server.

```
[MONITOR] ERROR: Cannot send notification to SMTP mydomain.de
Error: Connection timeout
    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:798:19)
    at SMTPConnection._onError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:784:20)
    at Timeout.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:237:22)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  code: 'ETIMEDOUT',
  command: 'CONN'
}
```
