### ISSUE TITLE
Slack notifications fail when url is partially defined

### ISSUE THREAD

**Issue by Rudedog9d** [louislam/uptime-kuma#4864]
### 📑 I have found these related issues/pull requests

None found.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Slack notifications fail if a monitorJSON.url is partially defined - ex, `https://`.

The error is coming from the "visit website" button that was recently added - if the url is incomplete, Slack will not allow the message.

### 👟 Reproduction steps

1. Create a slack alert
2. Create a DNS monitor, TXT, anything valid
3. Save the monitor
4. Edit the monitor to an invalid dns record
    - NOTE: it appears that editing the monitor is what actually populates the `.url` field, so editing is important. This step also causes the alert to trigger. 
6. Observe error in logs

Note that I added a `console.log('monitor URL'...` in `slack.js` `buildActions`:

```js
    static buildActions(baseURL, monitorJSON) {
        const actions = [];

        if (baseURL) {
            actions.push({
                "type": "button",
                "text": {
                    "type": "plain_text",
                    "text": "Visit Uptime Kuma",
                },
                "value": "Uptime-Kuma",
                "url": baseURL + getMonitorRelativeURL(monitorJSON.id),
            });

        }

        console.log("Monitor URL: ", monitorJSON.url);

        if (monitorJSON.url) {
            actions.push({
                "type": "button",
                "text": {
                    "type": "plain_text",
                    "text": "Visit site",
                },
                "value": "Site",
                "url": monitorJSON.url,
            });
        }

        return actions;
    }
```

### 👀 Expected behavior

Slack alert is sent

### 😓 Actual Behavior

Alert is not sent.

### 🐻 Uptime-Kuma Version

master branch (tested on 1.23.13 to NOT be a problem)

### 💻 Operating System and Arch

PopOS

### 🌐 Browser

Version 117.0.5938.132 (Official Build) (64-bit)

### 🖥️ Deployment Environment

- Runtime: v20.11.0
- Database: sqlite
- Filesystem used to store the database on: ext4
- number of monitors: 1

### 📝 Relevant log output

```shell
Monitor URL:  https://
2024-06-18T16:45:47-04:00 [MONITOR] ERROR: Cannot send notification to My Slack Alert (1)
2024-06-18T16:45:47-04:00 [MONITOR] ERROR: Error: Error: AxiosError: Request failed with status code 400 invalid_attachments
    at Slack.throwGeneralAxiosError (/home/bdavis/Dev/uptime-kuma/server/notification-providers/notification-provider.js:69:15)
    at Slack.send (/home/bdavis/Dev/uptime-kuma/server/notification-providers/slack.js:178:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Monitor.sendNotification (/home/bdavis/Dev/uptime-kuma/server/model/monitor.js:1349:21)
    at async beat (/home/bdavis/Dev/uptime-kuma/server/model/monitor.js:937:21)
    at async safeBeat (/home/bdavis/Dev/uptime-kuma/server/model/monitor.js:1023:17)
2024-06-18T16:45:47-04:00 [MONITOR] DEBUG: [asdf] apicache clear
2024-06-18T16:45:47-04:00 [MONITOR] WARN: Monitor #4 'asdf': Failing: queryTxt ENOTFOUND _remotef_acmfe-challenge.apisec.malteksolutions.com | Interval: 60 seconds | Type: dns | Down Count: 0 | Resend Interval: 0
2024-06-18T16:45:47-04:00 [UPTIME-CALC] DEBUG: Remove old data
```

**Comment by louislam** [comment]
Since it is only happening to the master branch, it should be related to https://github.com/louislam/uptime-kuma/pull/3886.

**Comment by Rudedog9d** [comment]
That makes sense - looks like that PR went from using the monitor url to the actual site url, which can be only partially defined.

Locally, I checked if the URL was parsable with `try { new Url(...) }`, but I'm not sure if that makes sense as a long term solution. Regex is the other thing that comes to mind.

A fix could also be to validate input when handling an `editMonitor` event, but that sounds like significantly more work.

@louislam any preferences? I'll open up a PR to fix it if you give me a direction to go :smile:
