### ISSUE TITLE
Discord notifications dont work

### ISSUE THREAD

**Issue by phyzical** [louislam/uptime-kuma#4940]
### 📑 I have found these related issues/pull requests

- https://github.com/louislam/uptime-kuma/issues/2447

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

No notifications are sent, test ones work fine.

On down it complains about the payload sent

### 👟 Reproduction steps

use docker type notification see error on down

### 👀 Expected behavior

should send notification

### 😓 Actual Behavior

it breaks

### 🐻 Uptime-Kuma Version

Version: 1.23.13

### 💻 Operating System and Arch

docker

### 🌐 Browser

frifox

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors: 

### 📝 Relevant log output

```shell
2024-07-14 14:52:35.734	logstream=stderr	
2024-07-14T14:52:35+08:00 [MONITOR] WARN: Monitor #21 'todo': Failing: Container State is exited | Interval: 60 seconds | Type: docker | Down Count: 0 | Resend Interval: 1
2024-07-14 14:52:35.734	logstream=stderr	
    at async Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1032:17)
2024-07-14 14:52:35.734	logstream=stderr	
    at async beat (/app/server/model/monitor.js:986:25)
2024-07-14 14:52:35.734	logstream=stderr	
    at async Monitor.sendNotification (/app/server/model/monitor.js:1427:21)
204-07-14 14:52:35.734	logstream=stderr	
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-07-14 14:52:35.734	logstream=stderr	
    at Discord.send (/app/server/notification-providers/discord.js:117:18)
2024-07-14 14:52:35.734	logstream=stderr	
    at Discord.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:38:15)
2024-07-14 14:52:35.734	logstream=stderr	
Error: Error: AxiosError: Request failed with status code 400 {"embeds":["0"]}
```

**Comment by phyzical** [comment]
as a workaround im just replicating the discord template in a normal webhook (missing some parts but it does what i want)

```
{
 "embeds": [{
                        "title": "{% if heartbeatJSON.status == 0 %}❌ Your service {{monitorJSON.name}}  went down. ❌{% else %} ✅ Your service {{monitorJSON.name}} is up! ✅{% endif %}",
                        "color": {% if heartbeatJSON.status == 0 %}16711680{% else %}65280{% endif %},
                        "timestamp": "{{heartbeatJSON.time}}",
                        "fields": [
                            {
                                "name": "Service Name",
                                "value": "{{monitorJSON.name}}"
                            },
                            {
                                "name": "Time ({{heartbeatJSON.timezone}})",
                                "value": "{{heartbeatJSON.localDateTime}}"
                            }{% if heartbeatJSON.status == 0 %},
                            {
                                "name": "Error",
                                "value": "{{heartbeatJSON.msg}}"
                            }{% endif %}
                        ]
                    }]     
}
```

**Comment by CommanderStorm** [comment]
Discord might have changed something about how embeds are handled.

Currently, we supply this embed (code has changed a bit since the last release, but nothing relevant to this issue):

https://github.com/louislam/uptime-kuma/blob/1a5a1a6e5d019b3dc58d114327f6765da0bee5f5/server/notification-providers/discord.js#L40-L62

Given that you likely have discord set up as a notification provider and that this kind of debugging does not scale well:
Could you try reproducing which of the fields we supply is now not allowed or which we are missing?

**Comment by phyzical** [comment]
hmm thats where i got the source to supply to the generic webhook, ill give the full payload a test later in the week and get back to you

in the meantime would we expect to see `{"embeds":["0"]}` instead of the actual payload in the error?

**Comment by GrigoryLantsov** [comment]
Notifications work perfectly on my side for Docker and HTTP monitors. The same error exists only on the database side, where notifications are not being sent. Can you take a look on that implementation?

**Comment by Ionys320** [comment]
Hi there,
I can take care of it if no one already made a PR for patching this.

**Comment by CommanderStorm** [comment]
I don't think this has been worked on. Help is always appreciated
