### ISSUE TITLE
Feature: Monitor checks

### ISSUE THREAD

**Issue by bertyhell** [louislam/uptime-kuma#495]
I'm trying to add a new feature to make more in depth monitor checks possible

![image](https://user-images.githubusercontent.com/1710840/134937390-dc12e530-cf0e-45fc-9a69-fb1f41ca4e43.png)

But i'm running into an issue with fetching the monitor checks from the database.
I keep getting this error:
```
Trace: TypeError: monitorCheck.toJSON is not a function
    at getMonitorJSONList (C:\Users\Bert\Documents\repos\uptime-kuma\server\server.js:1319:53)
    at async sendMonitorList (C:\Users\Bert\Documents\repos\uptime-kuma\server\server.js:1279:16)
    at async afterLogin (C:\Users\Bert\Documents\repos\uptime-kuma\server\server.js:1288:23)
    at process.<anonymous> (C:\Users\Bert\Documents\repos\uptime-kuma\server\server.js:1448:13)
```

I've created [a toJSON function in the monitor-check model file](https://github.com/bertyhell/uptime-kuma/blob/feature/monitor-checks/server/model/monitor-check.js#L7). So I'm not sure what I'm missing?
https://github.com/bertyhell/uptime-kuma/blob/feature/monitor-checks/server/server.js#L1319

Any help would be appreciated

**Comment by louislam** [comment]
Need custom mapping, since the model name is different to the table name.

```
const User = require("./model/user");
R.modelList["user"] = User;
```

https://redbean-node.whatsticker.online/Models
