### ISSUE TITLE
"Unable to acquire a connection" after OS reboot

### ISSUE THREAD

**Issue by KMatuszak** [louislam/uptime-kuma#5060]
### 📑 I have found these related issues/pull requests

- https://github.com/louislam/uptime-kuma/issues/3478 - has been closed, mine happened after OS reboot

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

after system reboot uptime-kuma won't boot up, restarting container fixed issue, cannot be reproduced again 

### 👟 Reproduction steps

happened once after OS reboot

### 👀 Expected behavior

app should start normally

### 😓 Actual Behavior

app crashed with error

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Debain 12 x64  (running `louislam/uptime-kuma:1` container)

### 🌐 Browser

Firefox 129.0.2

### 🖥️ Deployment Environment

- Runtime: Docker version 27.1.2, build d01f264, image id e1ca7233c2fa
- Database: default sqlite
- Filesystem used to store the database on: ext4
- number of monitors: 30

### 📝 Relevant log output

```shell
Trace: Error: Unable to acquire a connection
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:303:13)
    at Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:46)
    at Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:30)
    at Target.then (/app/node_modules/knex/lib/builder-interface-augmenter.js:24:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Timeout.safeBeat (/app/server/model/monitor.js:1034:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-08-27T22:17:13+02:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
```
```

**Comment by CommanderStorm** [comment]
> cannot be reproduced again

I don't know what you are expecting us to do..
There must have been some sort of storage problem (such as in https://github.com/louislam/uptime-kuma/issues/3478#issuecomment-1678904381) which prevented sqlite to aquire a connection.
