### ISSUE TITLE
Error: Invalid label name when using non-ASCII characters in tags

### ISSUE THREAD

**Issue by candies404** [louislam/uptime-kuma#5096]
### 📑 I have found these related issues/pull requests

No correlation has been found

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When using non-ASCII characters (such as Chinese) in tag names, the system throws an "Invalid label name" error during Prometheus metrics initialization.

![image](https://github.com/user-attachments/assets/b7bba9e1-fd42-458b-8002-d5d9578bd4ed)

### 👟 Reproduction steps

1. Create a tag with a non-ASCII name (e.g., Chinese characters) in Uptime Kuma
2. Restart the Uptime Kuma service or trigger Prometheus metrics initialization

### 👀 Expected behavior

The system should handle non-ASCII tag names gracefully, either by converting them to valid Prometheus label names or by using a separate field for Prometheus-compatible names.

### 😓 Actual Behavior

The system crashes with an "Invalid label name" error when initializing Prometheus metrics.

### 🐻 Uptime-Kuma Version

2.0.0-dev

### 💻 Operating System and Arch

Ubuntu Linux

### 🌐 Browser

127.0.6533.120

### 🖥️ Deployment Environment

- Runtime: Docker
- Database: external mariadb
- Filesystem used to store the database on: btrfs
- number of monitors: 5

### 📝 Relevant log output

```shell
Error message:
Trace: Error: Invalid label name
    at new Metric (/app/node_modules/prom-client/lib/metric.js:39:10)
    at new Gauge (/app/node_modules/prom-client/lib/gauge.js:19:1)
    at Prometheus.initMetrics (/app/server/prometheus.js:61:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Prometheus.createAndInitMetrics (/app/server/prometheus.js:96:9)
    at async Proxy.start (/app/server/model/monitor.js:349:27)
    at async startMonitors (/app/server/server.js:1805:9)
    at process.unexpectedErrorHandler (/app/server/server.js:1859:13)
    at process.emit (node:events:519:28)
    at emitUnhandledRejection (node:internal/process/promises:250:13)
    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)
    at processPromiseRejections (node:internal/process/promises:470:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

**Comment by louislam** [comment]
Thanks for finding the root cause. I was experiencing this issue last week too. It should be related to this pull request:

https://github.com/louislam/uptime-kuma/pull/4704#discussion_r1738343271

**Comment by louislam** [comment]
Actually I think it is not related to non-ASCII, it the pr causes all monitors are not working, I am going to revert the pr now.
