### ISSUE TITLE
Delete Monitor 

### ISSUE THREAD

**Issue by Rohitkhapre** [louislam/uptime-kuma#5182]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am experiencing an issue with Uptime Kuma where the application becomes unresponsive when I attempt to delete a monitor from the dashboard. The deletion process does not complete, and the dashboard freezes. As a result, I am unable to perform any further actions until I restart Uptime Kuma.

Steps to Reproduce:

Access the Uptime Kuma dashboard.
Attempt to delete any monitor.
The application becomes stuck and does not delete the monitor.
I am unable to access or use the dashboard until I restart Uptime Kuma.
Expected Behavior: The monitor should be deleted successfully without causing the application to hang.

Actual Behavior: Uptime Kuma becomes unresponsive, and the monitor is not deleted. The application needs to be restarted to become accessible again.

Environment Details:

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

22.04.2 LTS aarch64

### 🌐 Browser

128.0.6613.138

### 🖥️ Deployment Environment

- Runtime:  23.0.1, build a5ee5b1
- Database: 
- Filesystem used to store the database on: 
- number of monitors: 43

**Comment by CommanderStorm** [comment]
Seems weird.
What is logged about this?
What kind of a monitor is it?

To possibly skip a next question?
Could you share some metadata about your instance like the retention you configured in the settings, the size of the database and what storage you are running it on.

**Comment by John-Bob-DIRIENZO** [comment]
I have exactly the same issue here.

**Comment by bbbenji** [comment]
Same

```
2024-12-10T09:24:22+01:00 [AUTH] INFO: Successfully logged in user benji. IP=172.23.0.1
2024-12-10T09:24:35+01:00 [MONITOR] INFO: Get Monitor Beats: 7 User ID: 1
2024-12-10T09:24:39+01:00 [MANAGE] INFO: Delete Monitor: 7 User ID: 1
2024-12-10T09:27:00+01:00 [INCREMENTALVACUUM] ERROR: Failed: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
2024-12-10T09:27:23+01:00 [MONITOR] WARN: Monitor #4 'Mamy Wydruki': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 1 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2024-12-10T09:27:24+01:00 [MONITOR] WARN: Monitor #1 'redacted.pl': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 1 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2024-12-10T09:27:24+01:00 [MONITOR] WARN: Monitor #8 'redacted.pl': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 1 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2024-12-10T09:27:24+01:00 [MONITOR] WARN: Monitor #10 'redacted.pl/cart': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 1 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2024-12-10T09:27:25+01:00 [MONITOR] WARN: Monitor #12 'redacted.pl': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 1 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2024-12-10T09:27:25+01:00 [MONITOR] WARN: Monitor #11 'redacted.pl': Pending: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Max retries: 1 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2024-12-10T09:27:40+01:00 [DB] INFO: Delete Monitor completed in : 181174 ms
2024-12-10T09:27:40+01:00 [MONITOR] WARN: Monitor #9 'REDACTED': Failing: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? | Interval: 60 seconds | Type: group | Down Count: 0 | Resend Interval: 0
2024-12-10T09:28:40+01:00 [MONITOR] WARN: Monitor #9 'REDACTED': Pending: Child inaccessible | Max retries: 0 | Retry: 0 | Retry Interval: 60 seconds | Type: group
```

**Comment by bbbenji** [comment]
Update: Deleting 3 of my notifications "email, teams, discord" and attempting to delete monitors seemed to have worked, although it take a long time and seems to hang after a while.

```
2024-12-10T09:46:51+01:00 [AUTH] INFO: Successfully logged in user benji. IP=172.23.0.1
2024-12-10T09:46:59+01:00 [MANAGE] INFO: Delete Monitor: 11 User ID: 1
2024-12-10T09:47:04+01:00 [MANAGE] INFO: Delete Monitor: 8 User ID: 1
2024-12-10T09:47:07+01:00 [MANAGE] INFO: Delete Monitor: 12 User ID: 1
2024-12-10T09:47:09+01:00 [MANAGE] INFO: Delete Monitor: 10 User ID: 1
2024-12-10T09:48:34+01:00 [DB] INFO: Delete Monitor completed in : 95170 ms
2024-12-10T09:49:24+01:00 [DB] INFO: Delete Monitor completed in : 140349 ms
```

**Comment by BennyDaBee** [comment]
Running into the same issue myself. 

`2024-12-20T13:27:48-06:00 [MANAGE] INFO: Delete Monitor: 24 User ID: 1

Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)

    at runNextTicks (node:internal/process/task_queues:60:5)

    at listOnTimeout (node:internal/timers:538:9)

    at process.processTimers (node:internal/timers:512:7)

    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)

    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)

    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:572:22)

    at async RedBeanNode.getRow (/app/node_modules/redbean-node/dist/redbean-node.js:558:22)

    at async RedBeanNode.getCell (/app/node_modules/redbean-node/dist/redbean-node.js:593:19)

    at async Monitor.sendAvgPing (/app/server/model/monitor.js:1209:32) {

  sql: '\n' +

    '            SELECT AVG(ping)\n' +

    '            FROM heartbeat\n' +

    "            WHERE time > DATETIME('now', ? || ' hours')\n" +

    '            AND ping IS NOT NULL\n' +

    '            AND monitor_id = ?  limit ?',

  bindings: [ -24, 53, 1 ]

}

    at process.unexpectedErrorHandler (/app/server/server.js:1905:13)

    at process.emit (node:events:517:28)

    at emit (node:internal/process/promises:149:20)

    at processPromiseRejections (node:internal/process/promises:283:27)

    at processTicksAndRejections (node:internal/process/task_queues:96:32)

    at runNextTicks (node:internal/process/task_queues:64:3)

    at listOnTimeout (node:internal/timers:538:9)

    at process.processTimers (node:internal/timers:512:7)

If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues

Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)

    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)

    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)

    at async RedBeanNode.storeCore (/app/node_modules/redbean-node/dist/redbean-node.js:150:26)

    at async RedBeanNode.store (/app/node_modules/redbean-node/dist/redbean-node.js:110:20)

    at async beat (/app/server/model/monitor.js:1013:13)

    at async Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1032:17) {

  sql: undefined,

  bindings: undefined

}

    at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1034:25)

2024-12-20T13:29:49-06:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues

2024-12-20T13:29:49-06:00 [MONITOR] INFO: Try to restart the monitor`

**Comment by dlmorgan999** [comment]
I just tried to delete a monitor and experienced the same thing.

**Comment by hawwwwwk** [comment]
Still happening on 1.23.16 :<

**Comment by rlowevoiply** [comment]
Same issue just happened to me as well on two instances on 1.23.16

**Comment by 2fst4u** [comment]
Do people with this issue have memory limits set in the environment they're running uptimekuma in? I had a 256MB limit on my cloud VM and increasing it to 512MB allowed the monitors to delete.

**Comment by milankarolic** [comment]
I can confirm this issue. After trying to deleting "paused" group of monitors itself or whole paused group, whole app becomes unresponsive and doesn't delete anything. Only solution is to restart server. Running directly on Windows Server 2022 Standard.

**Comment by Rohitkhapre** [comment]
🐞 Bug Report: KnexTimeoutError – SQLite Connection Pool Full on Monitor Delete

❗ Description
While attempting to delete a monitor, Uptime Kuma crashed and became unresponsive. The dashboard fails to load, and multiple errors appear in the logs referencing:

Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
This happens repeatedly on startup and during monitor polling.

📦 Environment Details
Uptime Kuma Version: latest (Docker image)
Deployment Method: Docker
Database: SQLite (default)
Docker Host OS: [Mention your OS, e.g., Ubuntu 22.04 / Debian / etc.]
Browser & OS (when applicable): [e.g., Chrome on Windows 11]
🧾 Logs (Truncated Sample)
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:287:28)
    ...
    at async UptimeKumaServer.getClientIPwithProxy (/app/server/uptime-kuma-server.js:313:13)
    at async Object.allowRequest (/app/server/uptime-kuma-server.js:122:34) {
  sql: 'SELECT `value` FROM setting WHERE `key` = ?  limit ?',
  bindings: [ 'trustProxy', 1 ]
}
Also occurring for other monitors:

[MONITOR] WARN: Monitor #35 'IDS-Admin': Pending: Knex: Timeout acquiring a connection. The pool is probably full.
📌 Steps to Reproduce
Run latest Uptime Kuma Docker image with SQLite
Attempt to delete a monitor while it is actively polling
Application crashes and logs show KnexTimeoutError
Dashboard becomes unresponsive or fails to load
💡 Additional Context
Using SQLite, which may be under pressure due to monitor activity.
Issue started immediately after deleting a monitor.
Restarting the container does not resolve the issue.
Uptime Kuma becomes unusable after this error loop.
🧪 Potential Cause
SQLite has a limited connection pool (usually 1).
Deleting or interacting with a monitor without properly closing transactions may cause pool deadlock.
Missing .transacting(trx) in relevant Knex query, or a dangling DB connection could be the issue.
🙏 Requested Fix
Improve transaction handling and connection cleanup.
Prevent app crash on pool saturation.
Option to recover gracefully or auto-retry queries.
Maybe consider queueing DB interactions in case of SQLite backpressure.

**Comment by CommanderStorm** [comment]
@Rohitkhapre we have fixed this in the beta for v2.0 by aggregating heartbeats in the db.

You can see the upgrade guide here: https://github.com/louislam/uptime-kuma/wiki/Migration-From-v1-To-v2

**Comment by raabmar** [comment]
Just mentioning I am seeing the same but not yet on the beta  for v2.0. I could delete 2 monitors. Then stopped Uptime Kuma and reboot it. After that I tried to delete a 3rd monitor and reboot again but that's not possible. 

No idea why I can delete some monitors and cannot delete other monitors (even when accepting that it crashes while doing so)

**Comment by CommanderStorm** [comment]
> I am seeing the same but not yet on the beta  for v2.0

As I mentioned, upgrading should resolve this. If you’d prefer not to upgrade, then unfortunately there’s not much more I can do to help.

**Comment by raabmar** [comment]
I am not following the development cycle but I think it's beta for many months so I was not sure if it's smart to update or wait till it's stable. So I am not avoiding upgrading, but from a user perspective it's also not really clear on which version to rely on - latest beta vs. latest stable
