### ISSUE TITLE
Notification auto disabling on clicking save.button 

### ISSUE THREAD

**Issue by ro7it** [louislam/uptime-kuma#5206]
### 📑 I have found these related issues/pull requests

Notification auto disabling on clicking save.button 

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

<img width="1614" alt="image" src="https://github.com/user-attachments/assets/08826b7d-ff95-45a4-93b4-2fe516fc7cf4">

### 👟 Reproduction steps

Try to add a monitor and then enable the notification after adding a suitable channel like Slack. When clicking on save, it gets auto-disabled.

### 👀 Expected behavior

It should be Enabled only when enabling and disabled when disabling.

### 😓 Actual Behavior

Getting auto disabled on enabling and saving the changes.

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

M1

### 🌐 Browser

Chrom and Mozilla

### 🖥️ Deployment Environment

- Runtime: default
- Database: default
- Filesystem used to store the database on: default on local
- number of monitors: 2

### 📝 Relevant log output

```shell
Nothing found in logs.
```

**Comment by CommanderStorm** [comment]
> auto disabling

They were just displayed wrong, no need to be concearned.

**Comment by ro7it** [comment]
Just took a latest pull and build and testing, seeing issue with notification.

`2024-10-16T17:53:24+05:30 [MANAGE] INFO: Resume Monitor: 1 User ID: 1
2024-10-16T17:53:24+05:30 [MONITOR] ERROR: Cannot send notification to Superman
2024-10-16T17:53:24+05:30 [MONITOR] ERROR: Error: Error: TypeError: this.extractAddress is not a function 
    at Slack.throwGeneralAxiosError (/Users/rohitti/Downloads/demo-app/server/notification-providers/notification-provider.js:69:15)
    at Slack.send (/Users/rohitti/Downloads/demo-app/server/notification-providers/slack.js:167:18)
    at async Monitor.sendNotification (/Users/rohitti/Downloads/demo-app/server/model/monitor.js:1340:21)
    at async beat (/Users/rohitti/Downloads/demo-app/server/model/monitor.js:922:21)
    at async safeBeat (/Users/rohitti/Downloads/demo-app/server/model/monitor.js:1007:17)`

**Comment by CommanderStorm** [comment]
Thanks for testing ^^
That was fixed in https://github.com/louislam/uptime-kuma/pull/5209
