### ISSUE TITLE
Out of memory: cannot allocte Wasm memory for new instance

### ISSUE THREAD

**Issue by BeholdIsLost** [louislam/uptime-kuma#5266]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Out of memory: cannot allocte Wasm memory for new instance

### 📝 Error Message(s) or Log

```
2024-10-28T19:11:56-05:00 [SERVER] INFO: Connecting to the Database
Trace: RangeError: WebAssembly.instantiate(): Out of memory: Cannot allocate Wasm memory for new instance
    at lazyllhttp (/home/renatemc/uptime-kuma/node_modules/cheerio/node_modules/undici/lib/dispatcher/client-h1.js:79:28)
    at process.unexpectedErrorHandler (/home/renatemc/uptime-kuma/server/server.js:1905:13)
    at process.emit (node:events:519:28)
    at emitUnhandledRejection (node:internal/process/promises:250:13)
    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)
    at processPromiseRejections (node:internal/process/promises:470:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
```

### 🐻 Uptime-Kuma Version

1.23.14

### 💻 Operating System and Arch

Linux

### 🌐 Browser

Brave

### 🖥️ Deployment Environment

- Runtime:  Node 20.17.0
- Database: sqlite? havent configurated that
- Filesystem used to store the database on: I aint sure 100%
- number of monitors: 0

**Comment by CommanderStorm** [comment]
> Out of memory

How much memory do you have?

**Comment by BeholdIsLost** [comment]
cPanel told, that 2G as shared hosting provider, but everything else unlimited as I use sparked host

**Comment by CommanderStorm** [comment]
> as shared hosting provider

So how much were the other services using?
Shared means that you might have noisy neighbors that steal RAM/CPU/IO..
=> What is your guaranteed minimum RAM?

> I use sparked host

The hosting provider you are using does seem pretty sketchy.
They don't have any guarantees whatsoever in terms of IOPS/RAM size/hosts per system, except quite vague terms like that they "supply service" in the SLA.
I would reccomend a more reputable vendor or contacting their support

**Comment by BeholdIsLost** [comment]
I do see the server information and stuff on cPanel

![image](https://github.com/user-attachments/assets/88134eed-4aaa-4acf-b2de-ebd24705f720)

![image](https://github.com/user-attachments/assets/fe41fc82-8c40-4fe4-adf4-4010ac9892c2)
