### ISSUE TITLE
v2 nightly test upgrade docker

### ISSUE THREAD

**Issue by thehammy** [louislam/uptime-kuma#5275]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,

Been testing the v2 dev nightly for a couple of months.
Attempted to upgrade to the latest nightly version and also v2 beta but getting database access denied everytime.
Reverting back to existing nightly v2 image works fine.

2024-10-29T15:38:49Z [SERVER] ERROR: Failed to prepare your database: Access denied for user 'node'@'localhost'

Is there a way around this with embedded MariaDB?

### 📝 Error Message(s) or Log

2024-10-29T15:38:46Z [MARIADB] INFO: Embedded MariaDB started
2024-10-29T15:38:46Z [SERVER] ERROR: Failed to prepare your database: Access denied for user 'node'@'localhost'
Welcome to Uptime Kuma
Your Node.js version: 20.18.0
2024-10-29T15:38:47Z [SERVER] INFO: Env: production
2024-10-29T15:38:47Z [SERVER] INFO: Uptime Kuma Version: 2.0.0-dev-nightly-20241029113308
2024-10-29T15:38:47Z [SERVER] INFO: Loading modules
2024-10-29T15:38:48Z [SERVER] INFO: Creating express and socket.io instance
2024-10-29T15:38:48Z [SERVER] INFO: Server Type: HTTP
2024-10-29T15:38:48Z [SERVER] INFO: Data Dir: ./data/
2024-10-29T15:38:48Z [DB] INFO: Database Type: embedded-mariadb
2024-10-29T15:38:48Z [MARIADB] INFO: Starting Embedded MariaDB
2024-10-29T15:38:48Z [MARIADB] INFO: Embedded MariaDB is ready for connections
Trace: Error: Access denied for user 'node'@'localhost'
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:738:17)
    at ClientHandshake.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_ACCESS_DENIED_NO_PASSWORD_ERROR',
  errno: 1698,
  sqlState: '28000',
  sqlMessage: "Access denied for user 'node'@'localhost'",
  sql: undefined,
  fatal: true
}
    at process.unexpectedErrorHandler (/app/server/server.js:1872:13)
    at process.emit (node:events:519:28)
    at process._fatalException (node:internal/process/execution:188:25)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
2024-10-29T15:38:49Z [MARIADB] INFO: Embedded MariaDB started
2024-10-29T15:38:49Z [SERVER] ERROR: Failed to prepare your database: Access denied for user 'node'@'localhost'

### 🐻 Uptime-Kuma Version

V2

### 💻 Operating System and Arch

Centos 7.9

### 🌐 Browser

Google Chrome 130.0.6723.70

### 🖥️ Deployment Environment

- Runtime: Docker 20.10.21
- Database: MariaDB Embedded
- Filesystem used to store the database on: xfs (SSD)
- number of monitors: 20

**Comment by louislam** [comment]
Since it try to log in with `node` user. I think you used rootless image. You should use the `beta` tag.

**Comment by thehammy** [comment]
thanks @louislam, attempted the rootless beta image and it's working now :)
