### ISSUE TITLE
`SQLITE_CORRUPT: database disk image is malformed` Migration Error from 1.23.15 to 2.0.0-beta

### ISSUE THREAD

**Issue by corasaniti** [louislam/uptime-kuma#5281]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Migration Error 

### 📝 Error Message(s) or Log

```
2024-10-29T22:13:44Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-08 [81.83%][45/45]
2024-10-29T22:13:44Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-09 [81.85%][45/45]
2024-10-29T22:13:44Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-10 [81.87%][45/45]
2024-10-29T22:13:44Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-11 [81.89%][45/45]
2024-10-29T22:13:45Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-12 [81.91%][45/45]
2024-10-29T22:13:45Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-13 [81.93%][45/45]
2024-10-29T22:13:45Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-14 [81.95%][45/45]
2024-10-29T22:13:46Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-15 [81.97%][45/45]
2024-10-29T22:13:46Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-16 [81.99%][45/45]
2024-10-29T22:13:46Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-17 [82.01%][45/45]
2024-10-29T22:13:46Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-18 [82.03%][45/45]
2024-10-29T22:13:47Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-19 [82.05%][45/45]
2024-10-29T22:13:47Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-20 [82.07%][45/45]
2024-10-29T22:13:47Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-21 [82.09%][45/45]
2024-10-29T22:13:47Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-22 [82.11%][45/45]
2024-10-29T22:13:48Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-23 [82.13%][45/45]
2024-10-29T22:13:48Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-24 [82.15%][45/45]
2024-10-29T22:13:48Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-25 [82.17%][45/45]
2024-10-29T22:13:48Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-26 [82.19%][45/45]
2024-10-29T22:13:49Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-27 [82.21%][45/45]
2024-10-29T22:13:49Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-28 [82.23%][45/45]
2024-10-29T22:13:49Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-29 [82.25%][45/45]
2024-10-29T22:13:49Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-30 [82.27%][45/45]
2024-10-29T22:13:49Z [DB] INFO: Clearing non-important heartbeats
2024-10-29T22:13:49Z [DB] INFO: Deleting non-important heartbeats for monitor 18
2024-10-29T22:17:53Z [DB] INFO: Deleting non-important heartbeats for monitor 19
2024-10-29T22:21:38Z [DB] INFO: Deleting non-important heartbeats for monitor 20
2024-10-29T22:25:28Z [DB] INFO: Deleting non-important heartbeats for monitor 21
2024-10-29T22:29:14Z [DB] INFO: Deleting non-important heartbeats for monitor 22
2024-10-29T22:33:05Z [DB] INFO: Deleting non-important heartbeats for monitor 23
2024-10-29T22:33:12Z [DB] ERROR: Database migration failed
2024-10-29T22:33:12Z [SERVER] ERROR: Failed to prepare your database:
                DELETE FROM heartbeat
                WHERE monitor_id = 23
                AND important = 0
                AND time < DATETIME('now', -24 || ' hours')
                AND id NOT IN (
                    SELECT id
                    FROM heartbeat
                    WHERE monitor_id = 23
                    ORDER BY time DESC
                    LIMIT 100
                )
             - SQLITE_CORRUPT: database disk image is malformed
pi@raspi5-work:~/docker/uptime-kuma $
```

```
Welcome to Uptime Kuma
Your Node.js version: 20.18.0
2024-10-29T22:36:31Z [SERVER] INFO: Env: production
2024-10-29T22:36:32Z [SERVER] INFO: Uptime Kuma Version: 2.0.0-beta.0
2024-10-29T22:36:32Z [SERVER] INFO: Loading modules
2024-10-29T22:36:33Z [SERVER] INFO: Creating express and socket.io instance
2024-10-29T22:36:33Z [SERVER] INFO: Server Type: HTTP
2024-10-29T22:36:33Z [SERVER] INFO: Data Dir: ./data/
2024-10-29T22:36:33Z [DB] INFO: Database Type: sqlite
2024-10-29T22:36:33Z [SERVER] INFO: Connected to the database
2024-10-29T22:36:33Z [DB] WARN: Aggregate table migration is already in progress, or it was interrupted
2024-10-29T22:36:33Z [DB] ERROR: Database migration failed
2024-10-29T22:36:33Z [SERVER] ERROR: Failed to prepare your database: Aggregate table migration is already in progress
```

### 🐻 Uptime-Kuma Version

1.23.15 to 2 beta

### 💻 Operating System and Arch

RaspianOS Bookworm based

### 🌐 Browser

Chrome and Opera

### 🖥️ Deployment Environment

- Runtime: Docker version 27.3.1
- Database: sqllite
- Filesystem used to store the database on: 
- number of monitors: 44

**Comment by louislam** [comment]
Try to start again using your backup

**Comment by corasaniti** [comment]
@louislam 
No the backup is a local folder. If I restore the backup and use the tag 1.23.15 everything works fine.
Thanks in advance

**Comment by corasaniti** [comment]
@louislam 
Have you news? Are you bilded another beta, so can I retry?
Thanks

**Comment by CommanderStorm** [comment]
What louis was trying to ask for is if there are any things that might cause your DB to become corrupted (using 2 simultaneous instances, network drives, ...)

This is somewhat unlikely to be a bug in v2, at least I would not know how we would corrupt the db in the code path you were executing at the time..

=> could you just retry again?

**Comment by corasaniti** [comment]
> What louis was trying to ask for is if there are any things that might cause your DB to become corrupted (using 2 simultaneous instances, network drives, ...)
**I have replied in prev post. No no network drive but only local folder, no multi istances**
> 
> This is somewhat unlikely to be a bug in v2, at least I would not know how we would corrupt the db in the code path you were executing at the time..
> 
> => could you just retry again?
**I try again this evening**

Thanks

**Comment by by-cx** [comment]
I encountered similar problem. Also using local folder. No network drives.

```
web-1  | 2024-11-01T09:27:16Z [DB] INFO: [DON'T STOP] Migrating monitor data 2 - 2024-10-28 [7.78%][2/28]
web-1  | 2024-11-01T09:27:18Z [DB] INFO: [DON'T STOP] Migrating monitor data 2 - 2024-10-29 [7.80%][2/28]
web-1  | 2024-11-01T09:27:19Z [DB] INFO: [DON'T STOP] Migrating monitor data 2 - 2024-10-30 [7.82%][2/28]
web-1  | 2024-11-01T09:27:21Z [DB] INFO: [DON'T STOP] Migrating monitor data 2 - 2024-10-31 [7.84%][2/28]
web-1  | 2024-11-01T09:27:23Z [DB] INFO: [DON'T STOP] Migrating monitor data 2 - 2024-11-01 [7.86%][2/28]
web-1  | 2024-11-01T09:27:24Z [DB] ERROR: Database migration failed
web-1  | 2024-11-01T09:27:24Z [SERVER] ERROR: Failed to prepare your database: 
web-1  |                     SELECT status, ping, time
web-1  |                     FROM heartbeat
web-1  |                     WHERE monitor_id = 3
web-1  |                     AND DATE(time) = '2023-10-18'
web-1  |                     ORDER BY time ASC
web-1  |                  - SQLITE_CORRUPT: database disk image is malformed
web-1  | Welcome to Uptime Kuma
web-1  | Your Node.js version: 20.18.0

```

**Comment by corasaniti** [comment]
@louislam 
I tried again and got the same error.
So it's a bug. For now I will no longer test the beta version
Thank you

```
2024-11-01T09:47:25Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-23 [82.13%][45/45]
2024-11-01T09:47:25Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-24 [82.15%][45/45]
2024-11-01T09:47:25Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-25 [82.17%][45/45]
2024-11-01T09:47:26Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-26 [82.19%][45/45]
2024-11-01T09:47:26Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-27 [82.21%][45/45]
2024-11-01T09:47:26Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-28 [82.23%][45/45]
2024-11-01T09:47:26Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-29 [82.25%][45/45]
2024-11-01T09:47:27Z [DB] INFO: [DON'T STOP] Migrating monitor data 67 - 2024-09-30 [82.27%][45/45]
2024-11-01T09:47:27Z [DB] INFO: Clearing non-important heartbeats
2024-11-01T09:47:27Z [DB] INFO: Deleting non-important heartbeats for monitor 18
2024-11-01T09:51:16Z [DB] INFO: Deleting non-important heartbeats for monitor 19
2024-11-01T09:55:08Z [DB] INFO: Deleting non-important heartbeats for monitor 20
2024-11-01T09:58:59Z [DB] INFO: Deleting non-important heartbeats for monitor 21
2024-11-01T10:02:48Z [DB] INFO: Deleting non-important heartbeats for monitor 22
2024-11-01T10:06:37Z [DB] INFO: Deleting non-important heartbeats for monitor 23
2024-11-01T10:06:46Z [DB] ERROR: Database migration failed
2024-11-01T10:06:46Z [SERVER] ERROR: Failed to prepare your database: 
                DELETE FROM heartbeat
                WHERE monitor_id = 23
                AND important = 0
                AND time < DATETIME('now', -24 || ' hours')
                AND id NOT IN (
                    SELECT id
                    FROM heartbeat
                    WHERE monitor_id = 23
                    ORDER BY time DESC
                    LIMIT 100
                )
             - SQLITE_CORRUPT: database disk image is malformed
pi@raspi5-work:~ $ 
```

**Comment by by-cx** [comment]
I tried again:

```
web-1  | 2024-11-01T10:00:39Z [DB] INFO: [DON'T STOP] Migrating monitor data 2 - 2024-10-24 [7.70%][2/28]
web-1  | 2024-11-01T10:00:41Z [DB] INFO: [DON'T STOP] Migrating monitor data 2 - 2024-10-25 [7.72%][2/28]
web-1  | 2024-11-01T10:00:42Z [DB] INFO: [DON'T STOP] Migrating monitor data 2 - 2024-10-26 [7.74%][2/28]
web-1  | 2024-11-01T10:00:44Z [DB] INFO: [DON'T STOP] Migrating monitor data 2 - 2024-10-27 [7.76%][2/28]
web-1  | 2024-11-01T10:00:45Z [DB] INFO: [DON'T STOP] Migrating monitor data 2 - 2024-10-28 [7.78%][2/28]
web-1  | 2024-11-01T10:00:47Z [DB] INFO: [DON'T STOP] Migrating monitor data 2 - 2024-10-29 [7.80%][2/28]
web-1  | 2024-11-01T10:00:48Z [DB] INFO: [DON'T STOP] Migrating monitor data 2 - 2024-10-30 [7.82%][2/28]
web-1  | 2024-11-01T10:00:50Z [DB] INFO: [DON'T STOP] Migrating monitor data 2 - 2024-10-31 [7.84%][2/28]
web-1  | 2024-11-01T10:00:52Z [DB] INFO: [DON'T STOP] Migrating monitor data 2 - 2024-11-01 [7.86%][2/28]
web-1  | 2024-11-01T10:00:54Z [DB] ERROR: Database migration failed
web-1  | 2024-11-01T10:00:54Z [SERVER] ERROR: Failed to prepare your database: 
web-1  |                     SELECT status, ping, time
web-1  |                     FROM heartbeat
web-1  |                     WHERE monitor_id = 3
web-1  |                     AND DATE(time) = '2023-10-18'
web-1  |                     ORDER BY time ASC
web-1  |                  - SQLITE_CORRUPT: database disk image is malformed
```

And both runs crashed at the same point, when the migration tool reached today of "monitor data 2".

**Comment by corasaniti** [comment]
@by-cx 
your interruption happens very early at 7,86% I am able to get to 82,27%
In my opinion they are two different problems

**Comment by corasaniti** [comment]
@louislam 
in version 2 beta, can I expose 3306 port of Maria DB Embedded, so I can reache it, from outside container?
Thanks

**Comment by louislam** [comment]
I believe that you guys' SQLite was corrupted.

You can try to repair the SQLite database first.
https://stackoverflow.com/questions/5274202/sqlite3-database-or-disk-is-full-the-database-disk-image-is-malformed


PS: $DB_NAME = kuma.db

**Comment by corasaniti** [comment]
@louislam 
where is DATABASE_LOCATION?
Thanks

**Comment by by-cx** [comment]
@louislam It worked, thank you.

For future generations, I did this:

```
echo '.dump' | sqlite3 kuma.db | sqlite3 kuma.repaired.db
mv kuma.repaired.db kuma.db
```

**Comment by pax0707** [comment]
```
2024-11-09T00:10:27+01:00 [DB] INFO: [DON'T STOP] Migrating monitor data 4 - 2024-10-31 [11.55%][4/49]

2024-11-09T00:10:28+01:00 [DB] INFO: [DON'T STOP] Migrating monitor data 4 - 2024-11-01 [11.56%][4/49]

2024-11-09T00:10:29+01:00 [DB] INFO: [DON'T STOP] Migrating monitor data 4 - 2024-11-02 [11.57%][4/49]

2024-11-09T00:10:29+01:00 [DB] INFO: [DON'T STOP] Migrating monitor data 4 - 2024-11-03 [11.58%][4/49]

2024-11-09T00:10:30+01:00 [DB] INFO: [DON'T STOP] Migrating monitor data 4 - 2024-11-04 [11.59%][4/49]

2024-11-09T00:10:30+01:00 [DB] INFO: [DON'T STOP] Migrating monitor data 4 - 2024-11-05 [11.60%][4/49]

2024-11-09T00:10:31+01:00 [DB] INFO: [DON'T STOP] Migrating monitor data 4 - 2024-11-06 [11.61%][4/49]

2024-11-09T00:10:32+01:00 [DB] INFO: [DON'T STOP] Migrating monitor data 4 - 2024-11-07 [11.62%][4/49]

2024-11-09T00:10:32+01:00 [DB] INFO: [DON'T STOP] Migrating monitor data 4 - 2024-11-08 [11.63%][4/49]

2024-11-09T00:10:33+01:00 [DB] ERROR: Database migration failed

2024-11-09T00:10:33+01:00 [SERVER] ERROR: Failed to prepare your database: 

                SELECT DISTINCT DATE(time) AS date

                FROM heartbeat

                WHERE monitor_id = 5

                ORDER BY date ASC

             - SQLITE_CORRUPT: database disk image is malformed
```

When I try to dump I get a 0 size file
When I try to recover I get "sql error: SQL logic error (1)"
When I try to dump to sql and read into a new db I get a 0 size file

![image](https://github.com/user-attachments/assets/a04bf7e6-2ad9-43eb-b0bc-2a9cf21bf14a)

**Comment by PikuZheng** [comment]
same issue with last version here, reopen issue request
```
Welcome to Uptime Kuma
Your Node.js version: 20.18.0
2025-02-11T07:09:55Z [SERVER] INFO: Env: production
2025-02-11T07:09:56Z [SERVER] INFO: Uptime Kuma Version: 2.0.0-beta.1
2025-02-11T07:09:56Z [SERVER] INFO: Loading modules
2025-02-11T07:09:57Z [SERVER] INFO: Creating express and socket.io instance
2025-02-11T07:09:57Z [SERVER] INFO: Server Type: HTTP
2025-02-11T07:09:57Z [SERVER] INFO: Data Dir: ./data/
2025-02-11T07:09:57Z [DB] INFO: Database Type: sqlite
2025-02-11T07:09:57Z [SERVER] INFO: Connected to the database
2025-02-11T07:09:57Z [DB] WARN: Aggregate table migration is already in progress, or it was interrupted
2025-02-11T07:09:57Z [DB] ERROR: Database migration failed
2025-02-11T07:09:57Z [SERVER] ERROR: Failed to prepare your database: Aggregate table migration is already in progress
```

**Comment by eendeego** [comment]
@PikuZheng You can overcome that by setting `SET_MIGRATE_AGGREGATE_TABLE_TO_TRUE` to `1` and starting the server once. e.g

```
export SET_MIGRATE_AGGREGATE_TABLE_TO_TRUE=1
server/server.js
```

The server will start. You can stop it with Ctrl-C.

Next time you want to restart, you don't need `SET_MIGRATE_AGGREGATE_TABLE_TO_TRUE` set anymore.

**Comment by a10kiloham** [comment]
Happening to me now on a plain vanilla installation. Sucks! Aggregate table migration already in progress and because docker no way to run the command above :(

**Comment by by-cx** [comment]
@a10kiloham Try something like this:  `docker run --rm -e SET_MIGRATE_AGGREGATE_TABLE_TO_TRUE=1 -v ... IMAGE server/server.js`

**Comment by a10kiloham** [comment]
I got it to load with that as an env parameter in the docker compose file. Oddly the first time it ran for about ten minutes then started erroring on a database error. I went back and re-dumped the original, then left the env parameter in and it's all good. Although I'm cautious can I ever remove the env if it corrupts the database when removed? is there some way to tidy the database and ensure the migration failure is totally resolved?
thanks

**Comment by Fvbor** [comment]
> I believe that you guys' SQLite was corrupted.
> 
> You can try to repair the SQLite database first. https://stackoverflow.com/questions/5274202/sqlite3-database-or-disk-is-full-the-database-disk-image-is-malformed
> 
> PS: $DB_NAME = kuma.db
> 
> Again, don't forget to backup.

Thanks!
Worked for me while Upgrading from v1 to v2

@louislam Maybe add this in the Troubleshooting Wiki?
https://github.com/louislam/uptime-kuma/wiki/Troubleshooting

**Comment by louislam** [comment]
Google search result is pointing to this issue, I think it is OK.

However, I am sometimes concerning, whether SQLite is not stable, or I misused this. `SQLITE_CORRUPT` is not uncommon in this repo. But a lot of Android apps are using SQLite, which seems to be more stable (or most users don't know how to check the log on Android?)

**Comment by EpicLPer** [comment]
I've just migrated from Home Assistant's Uptime Kuma addon to a standalone Docker (due to DNS weirdness they refuse to improve on) and I'm getting similar errors. The service starts up and seems to be able to ping everything, but I'm still getting the following log spammed constantly:

```
Trace: [Error: insert into `heartbeat` (`down_count`, `duration`, `important`, `monitor_id`, `msg`, `ping`, `status`, `time`) values (0, 544, false, 6, '', 0.522, 1, '2025-10-22 22:18:49.008') - SQLITE_CORRUPT: database disk image is malformed] {
  errno: 11,
  code: 'SQLITE_CORRUPT'
}
    at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1034:25)
2025-10-23T00:18:49+02:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
2025-10-23T00:18:49+02:00 [MONITOR] INFO: Try to restart the monitor
Trace: [Error: select * from `heartbeat` where  monitor_id = 8 ORDER BY time DESC limit 1 - SQLITE_CORRUPT: database disk image is malformed] {
  errno: 11,
  code: 'SQLITE_CORRUPT'
}
    at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1034:25)
2025-10-23T00:18:53+02:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
2025-10-23T00:18:53+02:00 [MONITOR] INFO: Try to restart the monitor
Trace: [Error: select * from `heartbeat` where  monitor_id = 17 ORDER BY time DESC limit 1 - SQLITE_CORRUPT: database disk image is malformed] {
  errno: 11,
  code: 'SQLITE_CORRUPT'
}
    at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1034:25)
2025-10-23T00:18:54+02:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
2025-10-23T00:18:54+02:00 [MONITOR] INFO: Try to restart the monitor
Trace: [Error: insert into `heartbeat` (`down_count`, `duration`, `important`, `monitor_id`, `msg`, `ping`, `status`, `time`) values (0, 596, false, 18, '', 1, 1, '2025-10-22 22:18:54.840') - SQLITE_CORRUPT: database disk image is malformed] {
  errno: 11,
  code: 'SQLITE_CORRUPT'
}
    at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1034:25)
```

**Comment by PikuZheng** [comment]
> I've just migrated from Home Assistant's Uptime Kuma addon to a standalone Docker (due to DNS weirdness they refuse to improve on) and I'm getting similar errors. The service starts up and seems to be able to ping everything, but I'm still getting the following log spammed constantly:

Maybe it is a write permission problem.

**Comment by EpicLPer** [comment]
> > I've just migrated from Home Assistant's Uptime Kuma addon to a standalone Docker (due to DNS weirdness they refuse to improve on) and I'm getting similar errors. The service starts up and seems to be able to ping everything, but I'm still getting the following log spammed constantly:
> 
> Maybe it is a write permission problem.

Don't think so, it's able to write to the .log file without issues, also the "kuma.db-shm" and "-wal" get created just fine. The database file also shows a last edit-date of right now when starting the container, to me it doesn't look like a permission error.

**Comment by a10kiloham** [comment]
did you dump it to SQL format then reload as a new database? that solved these errors for me (although there still was a migration error which was separately a pain)

**Comment by EpicLPer** [comment]
Seems like I may have copied the files too quick after shutting down the Uptime Kuma AddOn on Home Assistant and accidentally copied an unfinished write of the database.  
Repeated my steps, now it works completely fine. :)

**Comment by nicfab** [comment]
## ✅ Solution Found - Successfully Fixed Migration Lock

I encountered the exact same issue after upgrading from **2.0.1 to 2.0.2** (non-Docker, PM2 installation).

### Error Messages
```
[DB] WARN: Aggregate table migration is already in progress, or it was interrupted
[DB] ERROR: Database migration failed
[SERVER] ERROR: Failed to prepare your database: Aggregate table migration is already in progress
```

The application was stuck in an infinite crash loop (700+ restarts in PM2).

### Root Cause
The migration flag `migrateAggregateTableState` was stuck in the `setting` table with value `"migrating"`, preventing the migration from restarting.

### Solution Steps

**1. Stop the application**
```bash
pm2 stop uptime-kuma  # or docker stop if using Docker
```

**2. Backup your database first** (IMPORTANT!)
```bash
cd /opt/uptime-kuma/data
cp kuma.db kuma.db.backup-$(date +%Y%m%d-%H%M%S)
```

**3. Reset the migration flag**
```bash
sqlite3 /opt/uptime-kuma/data/kuma.db "DELETE FROM setting WHERE key = 'migrateAggregateTableState';"
```

**4. Verify the flag was removed**
```bash
sqlite3 /opt/uptime-kuma/data/kuma.db "SELECT key, value FROM setting WHERE key = 'migrateAggregateTableState';"
# Should return empty
```

**5. Restart the application**
```bash
pm2 start uptime-kuma  # or docker start
```

### Result
✅ Application started successfully  
✅ Migration completed automatically  
✅ Service fully operational  
✅ No data loss

The migration process resumed from where it was interrupted and completed successfully.

### Environment
- **Version**: 2.0.1 → 2.0.2
- **OS**: Debian 12
- **Database**: SQLite (558MB)
- **Installation**: Non-Docker (PM2)
- **Node.js**: 22.19.0

Hope this helps others experiencing the same issue! 🚀

**Comment by EpicLPer** [comment]
Thanks for the solution @nicfab but this really didn't require AI to generate a report for you like this...

**Comment by nicfab** [comment]
> Thanks for the solution [@nicfab](https://github.com/nicfab) but this really didn't require AI to generate a report for you like this...

The spirit of open source is also to provide support to the community.
It's not a problem if the AI system saves time when writing a text.
