### ISSUE TITLE
2.0 Beta - Receiving a trace error: insert into `stat_hourly` - Duplicate entry '43-1731949200' for key 'stat_hourly_monitor_id_timestamp_unique'

### ISSUE THREAD

**Issue by undaunt** [louislam/uptime-kuma#5357]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm seeing a trace error of duplicate entry for a given monitor stat. I'm not sure why, but I can provide the logs.

### 📝 Error Message(s) or Log

```

Trace: Error: insert into `stat_hourly` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (0, 43, 94.4, 102, 87, 1731949200, 5) - Duplicate entry '43-1731949200' for key 'stat_hourly_monitor_id_timestamp_unique'
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:738:17)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  sqlMessage: "Duplicate entry '43-1731949200' for key 'stat_hourly_monitor_id_timestamp_unique'",
  sql: 'insert into `stat_hourly` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (0, 43, 94.4, 102, 87, 1731949200, 5)'
}
    at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1012:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-11-18T09:59:16-08:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
2024-11-18T09:59:16-08:00 [MONITOR] INFO: Try to restart the monitor
```

### 🐻 Uptime-Kuma Version

2.0.0-beta.0

### 💻 Operating System and Arch

TrueNAS Scale Electric Eel 24.10.0

### 🌐 Browser

N/A

### 🖥️ Deployment Environment

- Runtime: Docker 27.1.1
- Database: External MariaDB
- Filesystem used to store the database on: ZFS on nvme
- number of monitors: 16

**Comment by zaanposni** [comment]
We are also seeing this error for `stat_daily`. This is preventing our push monitors to come back online again.

Running: `louislam/uptime-kuma:nightly2`

```
Trace: Error: insert into `stat_daily` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (219, 14, 0, 0, 0, 1733270400, 580) - Duplicate entry '14-1733270400' for key 'stat_daily_monitor_id_timestamp_unique'
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:738:17)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  sqlMessage: "Duplicate entry '14-1733270400' for key 'stat_daily_monitor_id_timestamp_unique'",
  sql: 'insert into `stat_daily` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (219, 14, 0, 0, 0, 1733270400, 580)'
}
    at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1012:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-12-04T08:32:56+01:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
2024-12-04T08:32:56+01:00 [MONITOR] INFO: Try to restart the monitor
```

Not sure what the desired behaviour is and what the stat tables are for. 
But if someone could point us in the right direction, we might be able to contribute a PR.

**Comment by tahasonmez** [comment]
Same issue here.

`404 - "{\"ok\":false,\"msg\":\"insert into 'stat_daily' ('down', 'monitor_id', 'ping', 'ping_max', 'ping_min', 'timestamp', 'up') values (7, '54', 0, 0, 0, 1734048000, 258) - Duplicate entry '54-1734048000' for key 'stat_daily_monitor_id_timestamp_unique'\"}"`

**Comment by AMeadBC** [comment]
I still need to investigate properly, but initial evidence indicates this behavior may be triggered by Uptime Kuma running in a memory constrained environment. We provided it with more memory and most of these errors seem to have gone away.

**Comment by undaunt** [comment]
@AMeadBC Can you clarify what you mean by constrained? In my case I'm running on an external db now as opposed to sqlite to prevent concurrency issues and have a 64 GB system, of which around 8GB is used on ZFS buffer, 28GB 'in use', and the rest roughly is marked as 'cache/buffers' via Beszel. Does the memory need to be explicitly free?

**Comment by AMeadBC** [comment]
@undaunt I'm not sure in your case. It sounds quite different, and I haven't fully reproduced mine yet. It may be different causes with similar symptoms, or something else. More investigation to do as time is available.

My instance is running with the embedded SQLite and less than 1 GB total memory for the app and database. I think it's running around 256 MB total.

**Comment by DanielOaks** [comment]
Same on my side – it causes the push monitors to be very bouncy (as sometimes the requests work and sometimes they don't)

**Comment by AMeadBC** [comment]
The increased memory seems to have helped reduce the number of errors. But it didn't fix it. We are also seeing a lot of `TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?` errors, Which seem correlated and may be related.

**Comment by louislam** [comment]
Want to fix it, but I need some help to accurately reproduce the issue.

**Comment by undaunt** [comment]
I can get this almost immediately when starting up with 400+ containers created by Autokuma. So far so good on the test fork release I made, hence the PR.

**Comment by Ionys320** [comment]
@louislam PR #5933 shows it a Redbean issue. A change should be made in your repo/package (adding an option "upsert" or something like that), no? Or should we use knew upsert feature instead of Redbean? I wonder what would you prefer.

**Comment by Ionys320** [comment]
Hi @louislam ! Sorry to disturb you but this is a release blocker for v2. Just to know what would you prefer!

**Comment by JordyEGNL** [comment]
I got a similar error for one of my push monitors
```
"insert into `stat_daily` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (3, 50, 0, 0, 0, 1755043200, 11) - SQLITE_CONSTRAINT: UNIQUE constraint failed: stat_daily.monitor_id, stat_daily.timestamp"
```

**Comment by Adavidebaba** [comment]
{"ok":false,"msg":"insert into `stat_hourly` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (5, 1, 0, 0, 0, 1762531200, 45) - Duplicate entry '1-1762531200' for key 'stat_hourly_monitor_id_timestamp_unique'"}

**Comment by scampostula88** [comment]
Hello, Same error in Version 2.0.2

Only on push notifications at the moment. After a while, it accepts them again.
It was on a clean install, not a migration from version 1.

{"ok":false,"msg":"insert into `stat_daily` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (19, 29, 0, 0, 0, 1764892800, 1028) - Duplicate entry '29-1764892800' for key 'stat_daily_monitor_id_timestamp_unique'"}

**Comment by alexgex** [comment]
Hi, I got the similar error for push monitor (v2.0.2)
```json
{
"ok": false,
"msg": "insert into `stat_daily` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (4, '169', 0, 0, 0, 1764720000, 177) - SQLITE_CONSTRAINT: UNIQUE constraint failed: stat_daily.monitor_id, stat_daily.timestamp"
}
```
Other push monitors are working fine - the issue was isolated to this specific monitor ID

**Environment Info**:
Uptime Kuma Version: 2.0.2
OS: Ubuntu 22.04 LTS (Host), Docker Container
Database: SQLite (Default)
Deployment: Docker (official image louislam/uptime-kuma:2)

**Comment by wischi-chr** [comment]
I just saw the same error

```
kuma-1 | Trace: [Error: insert into `stat_minutely` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (0, 8, 12, 14, 10, 1764966420, 2) - SQLITE_CONSTRAINT: UNIQUE constraint failed: stat_minutely.monitor_id, stat_minutely.timestamp] {
kuma-1 |   errno: 19,
kuma-1 |   code: 'SQLITE_CONSTRAINT'
kuma-1 | }
kuma-1 |     at safeBeat (/app/server/model/monitor.js:1021:25)
```

Also likely for a monitor created with AutoKuma (same as @undaunt). It happened right around the time where I deleted a monitor that AutoKuma created because I wanted to test how it reacts and if the monitor is re-created by AutoKuma.

**wild guess:**
So maybe that is the issue? We have a monitor running, that already inserted the "current" `stat_minutely` value. I delete it (via the web interface), AutoKuma immediately recreates it (with the same monitor_id?) `uptime-kuma` triggers the request for the "new" monitor and runs into the constraint issue on INSERT because a few seconds ago a deleted monitor already inserted the point into `stat_minutely` - I haven't looked at the code at all, so this might be completely wrong.

## UPDATE:
I played around a bit and I can pretty reliably reproduce it.
- (I have sqlite but likely doesn't matter the constrait should fail on all DBs)
- Setup AutoKuma to create a monitor in uptime-kuma (one monitor is enough) - I used a http monitor 20 second interval
- To to the webinterface and delete the monitor AutoKuma created
- AutoKuma will recreate the monitor and that reliably triggers the issue (not every time - seem to depend on some timing) but roughly 50% of cases where I delete that monitor I get the constraint error.

**Comment by webees** [comment]
Same error in Version 2.0.2

**Comment by ownerer** [comment]
Getting this as well on push monitors, version 2.0.2

**Comment by Xav-Pe** [comment]
Confirming on 2.02:

`curl -s "https://mykuma/api/push/xxxxx?status=up&msg=up&ping="`

```
{"ok":false,"msg":"insert into `stat_daily` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (5, '23', 0, 0, 0, 1766188800, 8) - SQLITE_CONSTRAINT: UNIQUE constraint failed: stat_daily.monitor_id, stat_daily.timestamp"}
```

**Comment by dehlen** [comment]
Also seeing this issue on my push monitors using v2.0.2. I do not use Autokuma but a push monitor of mine which is pushed to as part of a ci schedule gets this issue regularly.

**Comment by MathiasBuus** [comment]
Same issue here with insert into 'stat_daily'. It seems rather random which days it occurs, but when it first occurs on a day - it keeps on failing the whole day. The day after everything is alright again - until some day it happens again.

**Comment by Thomas-Ganter** [comment]
I had the same issue on one monitor yesterday at midnight  --  vanished after a `docker restart ...` -- and reappeared today at midnight, again immediately fixed upon `docker restart ...`. 

Two observations: 

1) The `DOWN` message is pushed out immediately like clockwork every time a push is missed ... 

2) ... yet there was not any `UP` notification after the push monitor again accepted the status. 

I'll be vigilant to see whether it again happens this upcoming midnight. 
But, other than this being a nuissance, I guess it points to another issue in the code somewhere.

**Comment by markdesilva** [comment]
Had this happen to all my push monitors today for over an hour. After that, everything went back to normal.

Using docker, version 2.0.2, no autokuma monitors, just push monitors run by my scripts on crontab. Cron runs the script(s) every minute.

**Comment by ilexpl01** [comment]
Any update ? Got the same issue. Container v 2.0.2 restart was not helpful.

**Comment by dmorda** [comment]
I'm also experiencing the same issue with several of my push monitors. In my case, it's the push monitors that have a 24 hour heartbeat interval (86400 seconds). It seems to work for a while, then all of the sudden it fails for a day or two then works again.

```
{"ok":false,"msg":"insert into `stat_daily` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (3, 49, 0, 0, 0, 1769731200, 2) - SQLITE_CONSTRAINT: UNIQUE constraint failed: stat_daily.monitor_id, stat_daily.timestamp"}
```

I have cron jobs that run and send a curl to the push monitor once a day. 

**Environment Info:**
Uptime Kuma Version: 2.0.2
OS: Proxmox Virtual Environment
Database: SQLite (Default)
Deployment: LXC (Debian 13)

**Comment by thiagoor-cpu** [comment]
`2026-03-14T00:06:04-03:00 [MONITOR] WARN: Monitor #3 'NFS (Staff) / SMB / CUPS IC': Failing: No heartbeat in the time window | Interval: 360 seconds | Type: push | Down Count: 0 | Resend Interval: 0
Trace: Error: insert into `stat_minutely` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (2, '3', 0, 0, 0, 1773457560, 0) - Duplicate entry '3-1773457560' for key 'stat_minutely_monitor_id_timestamp_unique'
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:740:17)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/base/connection.js:475:34)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/base/connection.js:93:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/base/connection.js:100:25)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  sqlMessage: "Duplicate entry '3-1773457560' for key 'stat_minutely_monitor_id_timestamp_unique'",
  sql: "insert into `stat_minutely` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (2, '3', 0, 0, 0, 1773457560, 0)"
}
    at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1130:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2026-03-14T00:06:04-03:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
`
Also happening with me , Push monitor, Version: 2.2.0 , around mignight in some days...

**Comment by patillacode** [comment]
My two cents on this issue,

**Root cause analysis** for anyone trying to fix this (traced in `server/uptime-calculator.js`):

### Bug 1, Race condition on new period boundary

`getHourlyStatBean()` (and identical `getDailyStatBean` / `getMinutelyStatBean`) use a non-atomic **read-then-write** pattern:

```js
async getHourlyStatBean(timestamp) {
    if (this.lastHourlyStatBean && this.lastHourlyStatBean.timestamp === timestamp) {
        return this.lastHourlyStatBean;  // ← see Bug #2
    }

    let bean = await R.findOne("stat_hourly", " monitor_id = ? AND timestamp = ?",
        [this.monitorID, timestamp]);
    //  ^^^ async, yields the event loop here

    if (!bean) {
        bean = R.dispense("stat_hourly");   // new bean, no ID yet
        bean.monitor_id = this.monitorID;
        bean.timestamp = timestamp;
    }

    this.lastHourlyStatBean = bean;
    return this.lastHourlyStatBean;
}
```

At the start of a new hour, two concurrent `beat()` calls both reach the `await R.findOne(...)` before either executes `R.store()`. Both get `null`, both dispense a new bean, both try to INSERT:

```
Coroutine A:  findOne() → null → dispense (no ID) → cache → ...
Coroutine B:  findOne() → null → dispense (no ID) → cache → ...
Coroutine A:  R.store()  → INSERT ✓
Coroutine B:  R.store()  → INSERT ✗  SQLITE_CONSTRAINT: UNIQUE constraint failed
```

This matches the observation that it fires reliably at hour/day boundaries and on startup (migration catch-up + live beats overlap).

### Bug 2, Persistent failures after the first conflict

After coroutine B's INSERT fails, `this.lastHourlyStatBean` holds a bean **with no database ID**. On every subsequent `beat()`:

1. Cache check hits (`timestamp` matches), returns the ID-less bean
2. `R.store()` sees no ID, tries INSERT again, hits UNIQUE constraint again

This is why the error repeats on every beat until the container is restarted, not just once at the boundary.

### Fix

The cleanest fix is an atomic SQL upsert (as proposed in #5933):

```sql
INSERT INTO stat_hourly (monitor_id, timestamp, up, down, ping, ping_min, ping_max)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(monitor_id, timestamp) DO UPDATE SET
    up = excluded.up, down = excluded.down,
    ping = excluded.ping, ping_min = excluded.ping_min, ping_max = excluded.ping_max
```

SQLite supports this since 3.24 (2018); MariaDB equivalent is `ON DUPLICATE KEY UPDATE`.

A simpler short-term fix: in the cache check, also verify `this.lastHourlyStatBean.id` is set, so a failed INSERT doesn't poison the cache for subsequent beats.

**Comment by sysdump** [comment]
Example for daily, but should work for hourly and minutely as well.

### Bug 1:

We think we could use merge from knex:

```diff
-        await R.store(dailyStatBean);
+        await R.knex('stat_daily').insert(dailyStatBean).onConflict(['monitor_id','timestamp']).merge();
```

It seems to be supported for MySQL and SQLite in knex: [insert(..).onConflict(..).merge()](https://knexjs.org/guide/query-builder.html#onconflict)

For SQLite we specify the columns to check in `onConflict(['monitor_id','timestamp']`. 

For MySQL we use the already existing unique index `stat_daily_monitor_id_timestamp_unique`

Notes on MySQL unique index usage:
https://github.com/knex/knex/issues/5286#issuecomment-3445915669
https://dev.mysql.com/doc/refman/8.4/en/insert-on-duplicate.html

### Bug 2:
We could wait with caching until we have the matching stat bean stored to the database, We would find it on the next run like this:
```diff
    async getDailyStatBean(timestamp) {
        if (this.lastDailyStatBean && this.lastDailyStatBean.timestamp === timestamp) {
            return this.lastDailyStatBean;
        }

        let bean = await R.findOne("stat_daily", " monitor_id = ? AND timestamp = ?", [this.monitorID, timestamp]);

-        if (!bean) {
+        if (bean) {
+            this.lastDailyStatBean = bean;
+        } else {
            bean = R.dispense("stat_daily");
            bean.monitor_id = this.monitorID;
            bean.timestamp = timestamp;
        }

-        this.lastDailyStatBean = bean;
        return this.lastDailyStatBean;
    }
```

I should mention that I am not a JavaScript/Node.js programmer, so please be kind if the above is totally wrong :)

**Comment by freiit** [comment]
Hit this today on 2.3.2 / SQLite. The race at the day rollover is only half of it — the other half is the persistent loop it leaves behind.

In `UptimeCalculator.getDailyStatBean` (and the hourly/minutely twins):

```js
if (!bean) {
    bean = R.dispense("stat_daily");
    ...
}
this.lastDailyStatBean = bean;   // cached BEFORE store()
return this.lastDailyStatBean;
```

When push + watcher fire concurrently at midnight UTC, both `findOne`s miss, both dispense, both INSERT. One wins, one gets `SQLITE_CONSTRAINT`. The loser's **id-less** bean is now cached. Every subsequent update for that monitor that day hits the timestamp cache, gets the id-less bean back, `R.store()` sees no id → INSERT → same constraint error. Stuck until the day key rolls over or the container restarts. Restart is the only recovery.

Fingerprint of a stuck row: the existing `stat_daily` row has `up=1, down=1` (both threads' in-memory increments landed before either store completed).

Two small, independent fixes — either is sufficient:

1. **Self-heal on conflict.** In `update()`, catch the unique-constraint error from `R.store(dailyStatBean)`, set `this.lastDailyStatBean = null`, re-call `getDailyStatBean()` (which now hydrates the existing row with its id), re-apply the counters, retry the store. Turns a "broken until midnight UTC" into a single logged warning.
2. **Upsert at the DB layer.** Use knex `.onConflict(["monitor_id", "timestamp"]).merge()` on the stat inserts. SQLite 3.24+, MySQL and MariaDB all support it. Removes the race itself instead of recovering from it.

Doing both is belt-and-suspenders.

**Comment by Wohlstand** [comment]
Hello!
With the current release I receive the similar error:
```
мая 25 14:25:02 schawerma.wohlnet.ru uptime-kuma[164550]: 2026-05-25T14:25:02+03:00 [MONITOR] WARN: Monitor #48 'Nginx': Pending: No heartbeat in the time window | Max retries: 1 | Retry: 1 | Retry Interval: 300 seconds | Type: push
мая 25 14:25:02 schawerma.wohlnet.ru uptime-kuma[164550]: Trace: [Error: insert into `stat_minutely` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (1, 48, 0, 0, 0, 1779708300, 1) - SQLITE_CONSTRAINT: UNIQUE constraint failed: stat_minutely.monitor_id, stat_minutely.timestamp] {
мая 25 14:25:02 schawerma.wohlnet.ru uptime-kuma[164550]:   errno: 19,
мая 25 14:25:02 schawerma.wohlnet.ru uptime-kuma[164550]:   code: 'SQLITE_CONSTRAINT'
мая 25 14:25:02 schawerma.wohlnet.ru uptime-kuma[164550]: }
мая 25 14:25:02 schawerma.wohlnet.ru uptime-kuma[164550]:     at Timeout.safeBeat [as _onTimeout] (/opt/uptime-kuma/server/model/monitor.js:1130:25)
```
And that often leads false "no heartbeat" at the tracking daemons via "Push" method. I saw some messages from above about possible fix, let me try out some if that works or not...

Additionally! This bug causes the push itself receive an error message with the SQL query as a reply at the message text field (I ran CURL manually to see does hook works or not).

**Comment by Wohlstand** [comment]
Appending: my webhook pushes often return this:
```
{"ok":false,"msg":"insert into `stat_hourly` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (2, 47, 0, 0, 0, 1780045200, 3) - SQLITE_CONSTRAINT: UNIQUE constraint failed: stat_hourly.monitor_id, stat_hourly.timestamp"}
```
And it's pretty annoying that this happens, especially this causes my SMS sender to send me more false report SMS due to this case, and basically waste my money. Annoying! It should report REAL troubles, not just this failure.

The main reason to use SQLite here instead of heavy database servers like MySQL/MariaDB/PostgreSQL to just run a pretty simple and minimal thing, and easy-to-set-up. And it's suitable to set up the heavy database server if the high load is required, or it's already been installed for other needs.

**Comment by bb8** [comment]
I'm getting the same problem as @Wohlstand above on my push monitors, on a new installation. I tried a workaround, which seems to work: no errors for the past couple of days. YMMV.

- Deleted all heartbeats/events relating to the push monitor
- Changed my crontabs to all fire on a different second (none on the minute border), i.e.
`*/1 * * * *    sleep 11; wget ...`

**Comment by Wohlstand** [comment]
In my case there are different servers, but seems an interesting advice, I should try to set different cront time across my servers...

**Comment by Wohlstand** [comment]
I did some different tweak:

- At first server I left as-is:
```cron
*/5 * * * *    curl ...
```


- At the second I do the one minute shift:
```cron
1-59/5 * * * *    curl ...
```

Actually, my case is useful if you have longer heartbeat delay (for my needs I configured heartbeat per minute). But if you want to send queries with few seconds offset, then a sleep workaround should work.

**Comment by christian-schauer** [comment]
Data point that this is not limited to push monitors: on 2.5.4 (Docker, SQLite) we hit the same `stat_daily` wedge on a **json-query** monitor right after it was created through the socket API by AutoKuma.

Kuma log, all within 12 ms: `Resume Monitor: 226`, `Added Monitor: 226`, `Resume Monitor: 226` — then the first `UNIQUE constraint failed: stat_daily.monitor_id, stat_daily.timestamp` 30 ms later, repeating on every beat until the UTC day rolled over (5 lost beats, the monitor never turned red).

As far as we can tell from the code: the `add` handler already starts the monitor, and the client's follow-up `resumeMonitor` starts it a second time. `stop()` only clears the timer, so the first beat of the first start is still in flight and two first beats race on the same empty bucket — the same `findOne` → `dispense` → `store` race as with concurrent pushes.

Over 47 days: 4 day-level wedges (all in the creation second of a new monitor), plus 18 hour/minute-level collisions, also all in the creation second. None of 27 container restarts caused one; a restart actually clears the wedge, since the broken bean only lives in the in-memory cache.

Since #7554 makes `update()` an idempotent upsert regardless of the caller, it should cover this creation path as well — +1 for getting it merged.
