### ISSUE TITLE
[BUG] Error adding new monitor over API in v2: NOT NULL constraint failed: monitor.conditions 

### ISSUE THREAD

**Issue by fp-big5** [louislam/uptime-kuma#5360]
### 📑 I have found these related issues/pull requests

None

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I've built a python script to read all ingress objects in a kubernetes cluster and update/add them into uptime-kuma.

It is working in kuma:v1, besides having to change the timeout in the python API to over 90 seconds (you know, because it's slow at v1)

So, last week I saw the v2 beta and I'm trying it out.

So far, it's working as expected, BUT..

My script doesn't work anymore, apparently because a new "conditions" field are required:

```
python3 script.py

Monitor 'api-1' updated successfully.

Traceback (most recent call last):
  File "/home/fp/folder/script.py", line 94, in <module>
    api.add_monitor(**monitor_data)
  File "/home/fp/folder/venv/lib/python3.12/site-packages/uptime_kuma_api/api.py", line 1472, in add_monitor
    return self._call('add', data)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fp/folder/venv/lib/python3.12/site-packages/uptime_kuma_api/api.py", line 550, in _call
    raise UptimeKumaException(r.get("msg"))
uptime_kuma_api.exceptions.UptimeKumaException: 

insert into `monitor` (`accepted_statuscodes_json`, `auth_method`, `body`, `conditions`, `database_connection_string`, `description`, `dns_resolve_server`, `dns_resolve_type`, `expiry_notification`, `headers`, `hostname`, `http_body_encoding`, `ignore_tls`, `interval`, `kafka_producer_brokers`, `kafka_producer_sasl_options`, `maxredirects`, `maxretries`, `method`, `mqtt_password`, `mqtt_success_message`, `mqtt_topic`, `mqtt_username`, `name`, `packet_size`, `parent`, `port`, `proxy_id`, `rabbitmq_nodes`, `resend_interval`, `retry_interval`, `timeout`, `type`, `upside_down`, `url`, `user_id`) 

values ('["200-299"]', '', NULL, NULL, NULL, NULL, '1.1.1.1', 'A', 'True', NULL, NULL, 'json', false, 60, NULL, NULL, 10, 10, 'GET', '', '', '', '', 'api-2', 56, 145, NULL, NULL, NULL, 3600, 60, 29, 'http', false, 'https://api-2.company.com/healthcheck', 1) - 

SQLITE_CONSTRAINT: NOT NULL constraint failed: monitor.conditions
```

But it seems that this field is not yet implemented in the API, since it throws this error when I try to pass it:

```
python3 script.py

Monitor 'api-1' updated successfully.

Traceback (most recent call last):

  File "/home/fp/folder/script.py", line 94, in <module>
    api.add_monitor(**monitor_data)

  File "/home/fp/folder/venv/lib/python3.12/site-packages/uptime_kuma_api/api.py", line 1468, in add_monitor
    data = self._build_monitor_data(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: UptimeKumaApi._build_monitor_data() got an unexpected keyword argument 'conditions'
```

### 👟 Reproduction steps

try to add a new http monitor into uptimekuma:v2

### 👀 Expected behavior

To be able to add monitors over the API.

### 😓 Actual Behavior

The API throw this error:

SQLITE_CONSTRAINT: NOT NULL constraint failed: monitor.conditions

### 🐻 Uptime-Kuma Version

2.0.0-beta.0

### 💻 Operating System and Arch

docker

### 🌐 Browser

uptime-kuma API

### 🖥️ Deployment Environment

- Runtime: Docker version 27.2.1, build 9e34c9b
- Database: sqlite/embedded mariadb (not sure, using v2 migration default I guess)
- Filesystem used to store the database on: docker path mount
- number of monitors: 210

**Comment by felipewnp** [comment]
Hi @louislam 

Correct, I'm using the library that you mentioned.

So, just to be clear..

There is no way to manage uptime-kuma v2 programmatically?

**Comment by GrbrELO** [comment]
You can use https://github.com/exaland/uptime-kuma-api-v2 and - at least for me - it worked again. 
I leave that here, in case somebody else has this issue too.

**Comment by stokowski** [comment]
> You can use https://github.com/exaland/uptime-kuma-api-v2 and - at least for me - it worked again. I leave that here, in case somebody else has this issue too.

worked in my case, thanks
