### ISSUE TITLE
Remote Docker Connection over tcp fails

### ISSUE THREAD

**Issue by jg-development** [louislam/uptime-kuma#5386]
I followed the instructions https://docs.docker.com/engine/security/protect-access/ and https://github.com/louislam/uptime-kuma/wiki/How-to-Monitor-Docker-Containers#method-2-tcp---bridge-mode

I can connect from a client to the docker daemon without a problem:
```bash
docker --tlsverify -H=example.com:2376 --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem version

Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:41:00 2024
 OS/Arch:           linux/amd64
 Context:           default
.......
```

but when I use the connection in uptime I get the following problems:

Response:
```bash
4320[{"ok":false,"msg":"unable to verify the first certificate"}]
```
logs:
```bash
uptime-kuma  |     at AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:86:14)
uptime-kuma  |     at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:391:25)
uptime-kuma  |     at RedirectableRequest.emit (node:events:531:35)
uptime-kuma  |     at eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:49:24)
uptime-kuma  |     at ClientRequest.emit (node:events:519:28)
uptime-kuma  |     at emitErrorEvent (node:_http_client:101:11)
uptime-kuma  |     at TLSSocket.socketErrorListener (node:_http_client:504:5)
uptime-kuma  |     at TLSSocket.emit (node:events:519:28)
uptime-kuma  |     at emitErrorNT (node:internal/streams/destroy:169:8)
uptime-kuma  |     at emitErrorCloseNT (node:internal/streams/destroy:128:3) {
uptime-kuma  |   code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
.....
uptime-kuma  |       socket: [TLSSocket],
uptime-kuma  |       _header: 'GET /containers/json?all=true HTTP/1.1\r\n' +
uptime-kuma  |         'Accept: */*\r\n' +
uptime-kuma  |         'User-Agent: Uptime-Kuma/2.0.0-beta.0-nightly-20241105100611\r\n' +
uptime-kuma  |         'Host: tp-het-int-02.tp24:2376\r\n' +
uptime-kuma  |         'Connection: close\r\n' +
uptime-kuma  |         '\r\n',
uptime-kuma  |       _keepAliveTimeout: 0,
....
uptime-kuma  |     _currentUrl: 'https://tp-het-int-02.tp24:2376/containers/json?all=true',
uptime-kuma  |     _timeout: null,
uptime-kuma  |     [Symbol(shapeMode)]: true,
uptime-kuma  |     [Symbol(kCapture)]: false
uptime-kuma  |   },
uptime-kuma  |   cause: Error: unable to verify the first certificate
uptime-kuma  |       at TLSSocket.onConnectSecure (node:_tls_wrap:1677:34)
uptime-kuma  |       at TLSSocket.emit (node:events:519:28)
uptime-kuma  |       at TLSSocket._finishInit (node:_tls_wrap:1076:8)
uptime-kuma  |       at ssl.onhandshakedone (node:_tls_wrap:862:12) {
uptime-kuma  |     code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
uptime-kuma  |   }

```

Maybe intermediate cert is missing? Can somebody reproduce and provide a workaround? thx

**Comment by mityamityaamitya** [comment]
I have such problems

**Comment by joeknock90** [comment]
Same

**Comment by pguinet** [comment]
Hi @jg-development ,
Your working connexion is with _example.com:2376_ and error log shows _texample.com:2376_. 
Another problem I had was with server name casing. Better to have everything lowercase (folder for certificates and url).

**Comment by joeknock90** [comment]
I am using certs signed directly by the root CA in my case. I've generated certs from a FreeIPA ca via Certbot. They work for everything, but uptime-kuma always returns the following. 

```
server-1  | 2025-06-03T07:49:53-04:00 [DOCKER] ERROR: AxiosError: unable to verify the first certificate
server-1  |     at AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:86:14)
server-1  |     at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:391:25)
server-1  |     at RedirectableRequest.emit (node:events:531:35)
server-1  |     at eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:49:24)
server-1  |     at ClientRequest.emit (node:events:519:28)
server-1  |     at emitErrorEvent (node:_http_client:101:11)
server-1  |     at TLSSocket.socketErrorListener (node:_http_client:504:5)
server-1  |     at TLSSocket.emit (node:events:519:28)
server-1  |     at emitErrorNT (node:internal/streams/destroy:169:8)
server-1  |     at emitErrorCloseNT (node:internal/streams/destroy:128:3) {
server-1  |   code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
server-1  |   config: {
server-1  |     transitional: {
server-1  |       silentJSONParsing: true,
server-1  |       forcedJSONParsing: true,
server-1  |       clarifyTimeoutError: false
server-1  |     },
server-1  |     adapter: [Function: httpAdapter],
server-1  |     transformRequest: [ [Function: transformRequest] ],
server-1  |     transformResponse: [ [Function: transformResponse] ],
server-1  |     timeout: 5000,
server-1  |     xsrfCookieName: 'XSRF-TOKEN',
server-1  |     xsrfHeaderName: 'X-XSRF-TOKEN',
server-1  |     maxContentLength: -1,
server-1  |     maxBodyLength: -1,
server-1  |     env: { FormData: [Function [FormData]], Blob: [class Blob] },
server-1  |     validateStatus: [Function: validateStatus],
server-1  |     headers: { Accept: '*/*', 'User-Agent': 'Uptime-Kuma/2.0.0-beta.2' },
server-1  |     url: '/containers/json?all=true',
server-1  |     signal: AbortSignal { aborted: false },
server-1  |     baseURL: 'https://docker-host.example.com:2376',
server-1  |     httpsAgent: Agent {
server-1  |       _events: [Object: null prototype],
server-1  |       _eventsCount: 2,
server-1  |       _maxListeners: undefined,
server-1  |       defaultPort: 443,
server-1  |       protocol: 'https:',
server-1  |       options: [Object: null prototype],
server-1  |       requests: [Object: null prototype] {},
server-1  |       sockets: [Object: null prototype],
server-1  |       freeSockets: [Object: null prototype] {},
server-1  |       keepAliveMsecs: 1000,
server-1  |       keepAlive: false,
server-1  |       maxSockets: Infinity,
server-1  |       maxFreeSockets: 256,
server-1  |       scheduling: 'lifo',
server-1  |       maxTotalSockets: Infinity,
server-1  |       totalSocketCount: 1,
server-1  |       maxCachedSessions: 0,
server-1  |       _sessionCache: [Object],
server-1  |       [Symbol(shapeMode)]: false,
server-1  |       [Symbol(kCapture)]: false
server-1  |     },
server-1  |     method: 'get',
server-1  |     data: undefined
server-1  |   },
server-1  |   request: <ref *1> Writable {
server-1  |     _events: {
server-1  |       close: undefined,
server-1  |       error: [Function: handleRequestError],
server-1  |       prefinish: undefined,
server-1  |       finish: undefined,
server-1  |       drain: undefined,
server-1  |       response: [Function: handleResponse],
server-1  |       socket: [Array],
server-1  |       timeout: undefined,
server-1  |       abort: undefined
server-1  |     },
server-1  |     _writableState: WritableState {
server-1  |       highWaterMark: 16384,
server-1  |       length: 0,
server-1  |       corked: 0,
server-1  |       onwrite: [Function: bound onwrite],
server-1  |       writelen: 0,
server-1  |       bufferedIndex: 0,
server-1  |       pendingcb: 0,
server-1  |       [Symbol(kState)]: 17580812,
server-1  |       [Symbol(kBufferedValue)]: null
server-1  |     },
server-1  |     _maxListeners: undefined,
server-1  |     _options: {
server-1  |       maxRedirects: 21,
server-1  |       maxBodyLength: Infinity,
server-1  |       protocol: 'https:',
server-1  |       path: '/containers/json?all=true',
server-1  |       method: 'GET',
server-1  |       headers: [Object],
server-1  |       agents: [Object],
server-1  |       auth: undefined,
server-1  |       beforeRedirect: [Function: dispatchBeforeRedirect],
server-1  |       beforeRedirects: [Object],
server-1  |       hostname: 'docker-host.example.com',
server-1  |       port: '2376',
server-1  |       agent: [Agent],
server-1  |       nativeProtocols: [Object],
server-1  |       pathname: '/containers/json',
server-1  |       search: '?all=true'
server-1  |     },
server-1  |     _ended: true,
server-1  |     _ending: true,
server-1  |     _redirectCount: 0,
server-1  |     _redirects: [],
server-1  |     _requestBodyLength: 0,
server-1  |     _requestBodyBuffers: [],
server-1  |     _eventsCount: 3,
server-1  |     _onNativeResponse: [Function (anonymous)],
server-1  |     _currentRequest: ClientRequest {
server-1  |       _events: [Object: null prototype],
server-1  |       _eventsCount: 7,
server-1  |       _maxListeners: undefined,
server-1  |       outputData: [],
server-1  |       outputSize: 0,
server-1  |       writable: true,
server-1  |       destroyed: false,
server-1  |       _last: true,
server-1  |       chunkedEncoding: false,
server-1  |       shouldKeepAlive: false,
server-1  |       maxRequestsOnConnectionReached: false,
server-1  |       _defaultKeepAlive: true,
server-1  |       useChunkedEncodingByDefault: false,
server-1  |       sendDate: false,
server-1  |       _removedConnection: false,
server-1  |       _removedContLen: false,
server-1  |       _removedTE: false,
server-1  |       strictContentLength: false,
server-1  |       _contentLength: 0,
server-1  |       _hasBody: true,
server-1  |       _trailer: '',
server-1  |       finished: true,
server-1  |       _headerSent: true,
server-1  |       _closed: false,
server-1  |       socket: [TLSSocket],
server-1  |       _header: 'GET /containers/json?all=true HTTP/1.1\r\n' +
server-1  |         'Accept: */*\r\n' +
server-1  |         'User-Agent: Uptime-Kuma/2.0.0-beta.2\r\n' +
server-1  |         'Host: docker-host.example.com:2376\r\n' +
server-1  |         'Connection: close\r\n' +
server-1  |         '\r\n',
server-1  |       _keepAliveTimeout: 0,
server-1  |       _onPendingData: [Function: nop],
server-1  |       agent: [Agent],
server-1  |       socketPath: undefined,
server-1  |       method: 'GET',
server-1  |       maxHeaderSize: undefined,
server-1  |       insecureHTTPParser: undefined,
server-1  |       joinDuplicateHeaders: undefined,
server-1  |       path: '/containers/json?all=true',
server-1  |       _ended: false,
server-1  |       res: null,
server-1  |       aborted: false,
server-1  |       timeoutCb: null,
server-1  |       upgradeOrConnect: false,
server-1  |       parser: null,
server-1  |       maxHeadersCount: null,
server-1  |       reusedSocket: false,
server-1  |       host: 'docker-host.example.com',
server-1  |       protocol: 'https:',
server-1  |       _redirectable: [Circular *1],
server-1  |       [Symbol(shapeMode)]: false,
server-1  |       [Symbol(kCapture)]: false,
server-1  |       [Symbol(kBytesWritten)]: 0,
server-1  |       [Symbol(kNeedDrain)]: false,
server-1  |       [Symbol(corked)]: 0,
server-1  |       [Symbol(kOutHeaders)]: [Object: null prototype],
server-1  |       [Symbol(errored)]: null,
server-1  |       [Symbol(kHighWaterMark)]: 16384,
server-1  |       [Symbol(kRejectNonStandardBodyWrites)]: false,
server-1  |       [Symbol(kUniqueHeaders)]: null
server-1  |     },
server-1  |     _currentUrl: 'https://docker-host.example.com:2376/containers/json?all=true',
server-1  |     _timeout: null,
server-1  |     [Symbol(shapeMode)]: true,
server-1  |     [Symbol(kCapture)]: false
server-1  |   },
server-1  |   cause: Error: unable to verify the first certificate
server-1  |       at TLSSocket.onConnectSecure (node:_tls_wrap:1677:34)
server-1  |       at TLSSocket.emit (node:events:519:28)
server-1  |       at TLSSocket._finishInit (node:_tls_wrap:1076:8)
server-1  |       at ssl.onhandshakedone (node:_tls_wrap:862:12) {
server-1  |     code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
server-1  |   }
server-1  | }

```
