### ISSUE TITLE
Unable to start 2.0.0-beta.0 inside podman container

### ISSUE THREAD

**Issue by thimomulder** [louislam/uptime-kuma#5406]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Unable to start the beta version of Uptime-Kuma using the following command: `sudo podman run -d --replace --restart=always -p 3001:3001 -v ~/uptime-kuma-beta/data:/app/data --name uptime-kuma-beta louislam/uptime-kuma:beta
`

### 📝 Error Message(s) or Log

Welcome to Uptime Kuma
Your Node.js version: 20.18.0
2024-12-04T13:42:28Z [SERVER] INFO: Env: production
2024-12-04T13:42:29Z [SERVER] INFO: Uptime Kuma Version: 2.0.0-beta.0
2024-12-04T13:42:29Z [SERVER] INFO: Loading modules
2024-12-04T13:42:29Z [SERVER] INFO: Creating express and socket.io instance
2024-12-04T13:42:29Z [SERVER] INFO: Server Type: HTTP
Trace: Error: EACCES: permission denied, mkdir 'data/upload/'
    at Object.mkdirSync (node:fs:1371:26)
    at Database.initDataDir (/app/server/database.js:146:16)
    at /app/server/server.js:173:14
    at Object.<anonymous> (/app/server/server.js:1624:3)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: 'data/upload/'
}
    at process.unexpectedErrorHandler (/app/server/server.js:1872:13)
    at process.emit (node:events:519:28)
    at emitUnhandledRejection (node:internal/process/promises:250:13)
    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)
    at processPromiseRejections (node:internal/process/promises:470:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues

### 🐻 Uptime-Kuma Version

v2.0.0.0-beta.0

### 💻 Operating System and Arch

RHEL 9

### 🌐 Browser

not used

### 🖥️ Deployment Environment

not used

**Comment by CommanderStorm** [comment]
> Trace: Error: EACCES: permission denied, mkdir 'data/upload/'

What are the permissions of `data/upload`

**Comment by thimomulder** [comment]
The folder `data/upload/` doesn't excist. The folder `data` is created by me with `0755` rights.

**Comment by thimomulder** [comment]
> > Trace: Error: EACCES: permission denied, mkdir 'data/upload/'
> 
> What are the permissions of `data/upload`

The folder `data/upload/` doesn't excist. The folder `data` is created by me with the permissions set at `0755`

**Comment by thimomulder** [comment]
@almereyda Adding the `:z`/`:Z` flag fixed the problem thanks!
