### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by douxltechnologies** [louislam/uptime-kuma#5436]
### 📑 I have found these related issues/pull requests

- https://github.com/louislam/uptime-kuma/issues/5010
- https://github.com/louislam/uptime-kuma/issues/5011

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

randomly get above error in docker logs

### 👟 Reproduction steps

i happens randomly

### 👀 Expected behavior

no such error should be there

### 😓 Actual Behavior

there re errors but not sure if it affects any services

### 🐻 Uptime-Kuma Version

1.0

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime: Docker 27.3.1
- Database: embedded
- Filesystem used to store the database on: EXT4/SSD
- number of monitors: 37

### 📝 Relevant log output

```shell
Trace: TypeError: callback is not a function
    at Socket.<anonymous> [90m(/app/[39mserver/server.js:915:17[90m)[39m
    at process.unexpectedErrorHandler (/app/server/server.js:1905:13)
    at process.emit (node:events:517:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
```

**Comment by CommanderStorm** [comment]
We never could reproduce this in
- https://github.com/louislam/uptime-kuma/issues/5010#issuecomment-2283550401

Please consider upgrading to v2

**Comment by douxltechnologies** [comment]
but its beta release, is it ok to upgrade it to beta version?

**Comment by CommanderStorm** [comment]
You can upgrade to the beta version via this guide: https://github.com/louislam/uptime-kuma/wiki/Migration-From-v1-To-v2
