### ISSUE TITLE
Bug in monitor push

### ISSUE THREAD

**Issue by atpascal07** [louislam/uptime-kuma#5486]
### 📑 I have found these related issues/pull requests

no

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

If I create a push monitor it works but it doesn't work see picture
![screenshot-2024-12-31-15-27-30](https://github.com/user-attachments/assets/d4291d67-3ade-4c41-92c1-10257f814b7f)

### 👟 Reproduction steps

I only created a push monitor

### 👀 Expected behavior

That when you go to the url it turns green on the status page

### 😓 Actual Behavior

I have created a push monitor when I click on the link an error message appears which I can also see in the screenshot below 
![screenshot-2024-12-31-15-32-19](https://github.com/user-attachments/assets/6bd27378-2622-49d7-9b51-3e57e151757d)

### 🐻 Uptime-Kuma Version

2.0.0-beta.1

### 💻 Operating System and Arch

Ubuntu 24.04 (pelican Panel )

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by louislam** [comment]
Cannot reproduce. May need more info.

**Comment by c0nstructer** [comment]
similar issues #5357 , #4315 
seems that [2023-08-16-0000-create-uptime.js](https://github.com/louislam/uptime-kuma/blob/be2faf64ce8973d49d6c4b29dacdedbffc57855e/db/knex_migrations/2023-08-16-0000-create-uptime.js#L17) has constraint of unique timestamp value.

Either remove constraint on timestamp, or set in knex from integer value to knex.timestamp as proper value.

**Comment by undaunt** [comment]
I am using Autokuma to create these monitors and receiving the linked error in https://github.com/louislam/uptime-kuma/issues/5357. Here is another sample:

Docker compose
```
services:
  uptime-kuma:
    image: louislam/uptime-kuma:beta-slim
    container_name: uptime-kuma
    restart: unless-stopped
    profiles: ["all", "kuma"]
    networks:
      - ${PROXY_NETWORK}
      - ${APP_NETWORK}
      - ${SOCKET_NETWORK}
      - ${GLUETUN_NETWORK}
    depends_on:
      - uptime-kuma-db
    volumes:
      - ${APPDATA_DIR}/uptime-kuma/data:/app/data
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    labels:
      ## Logging
      logging.promtail: true
      ## Traefik
      traefik.enable: true
      traefik.docker.network: ${PROXY_NETWORK} # For containers on multiple bridge networks, force the correct proxy network
      traefik.external.cname: true # For services that need a public cname, not only private access
      traefik.http.routers.uptime-kuma.entrypoints: https
      traefik.http.routers.uptime-kuma.rule: Host(`${SUB_UPTIME_KUMA}.${DOMAINNAME}`)
      traefik.http.routers.uptime-kuma.priority: 1 # Only needed if using more than one router per service
      traefik.http.routers.uptime-kuma.middlewares: chain-auth@file # Change to chain-no-auth if using OIDC in most cases
      traefik.http.routers.uptime-kuma.service: uptime-kuma # Not required if only one service is being defined - https://doc.traefik.io/traefik/routing/providers/docker/#service-definition
      traefik.http.routers.uptime-kuma-api.entrypoints: https
      traefik.http.routers.uptime-kuma-api.rule: Host(`${SUB_UPTIME_KUMA}.${DOMAINNAME}`) && PathPrefix(`/status`)
      traefik.http.routers.uptime-kuma-api.priority: 25 # Only needed if using more than one router per service
      traefik.http.routers.uptime-kuma-api.middlewares: chain-no-auth@file
      traefik.http.routers.uptime-kuma-api.service: uptime-kuma # Not required if only one service is being defined - https://doc.traefik.io/traefik/routing/providers/docker/#service-definition
      traefik.http.services.uptime-kuma.loadbalancer.server.port: 3001 # May not be required if only one port is exposed by default - https://doc.traefik.io/traefik/providers/docker/#port-detection
      ## Unraid
      net.unraid.docker.managed: composeman
      net.unraid.docker.webui: https://${SUB_UPTIME_KUMA}.${DOMAINNAME}
      net.unraid.docker.icon: 
      ## Autokuma
      kuma.__app: '{ "name": "Uptime-Kuma", "type": "web-group", "url": "https://${SUB_UPTIME_KUMA}.${DOMAINNAME}", "internal_port": "3001" }'
  
  uptime-kuma-db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: uptime-kuma-db
    restart: always
    profiles: ["all", "kuma"]
    networks:
      - ${APP_NETWORK}
    volumes:
      - ${APPDATA_DIR}/uptime-kuma/db:/config
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      MYSQL_ROOT_PASSWORD: ${UPTIME_KUMA_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${UPTIME_KUMA_MYSQL_DB}
      MYSQL_USER: ${UPTIME_KUMA_MYSQL_USER}
      MYSQL_PASSWORD: ${UPTIME_KUMA_MYSQL_PASSWORD}
    labels:
      ## Logging
      logging.promtail: true
      ## Unraid
      net.unraid.docker.managed: composeman
      net.unraid.docker.icon: 
      ## Autokuma
      kuma.__app: '{ "name": "Uptime-Kuma MySQL", "type": "mysql", "service": "Uptime-Kuma", "db_url": "mysql://${UPTIME_KUMA_MYSQL_USER}:${UPTIME_KUMA_MYSQL_PASSWORD}@uptime-kuma-db:3306" }'
  
  autokuma:
    image: ghcr.io/bigboot/autokuma:master
    container_name: autokuma
    restart: unless-stopped
    profiles: ["all", "kuma"]
    networks:
      - ${SOCKET_NETWORK}
    depends_on:
      - uptime-kuma
    environment:
      AUTOKUMA__KUMA__URL: http://uptime-kuma:3001
      AUTOKUMA__KUMA__USERNAME: ${KUMA_USER}
      AUTOKUMA__KUMA__PASSWORD: ${KUMA_PASSWORD}
      AUTOKUMA__SYNC_INTERVAL: 30
      AUTOKUMA__TAG_NAME: AutoKuma
      AUTOKUMA__DEFAULT_SETTINGS: |-
        *.notification_id_list: { "1": true }
      AUTOKUMA__ON_DELETE: delete
      AUTOKUMA__SNIPPETS__APP: |-
        {# Assign the first snippet arg for readability #}
        {% set args = args[0] %}

        {# Generate IDs with slugify #}
        {% set id = args.name | slugify %}
        {% if args.service %}
          {% set service_id = args.service | slugify %}
        {% endif %}

        {# Define the top level services/app naming conventions #}
        {% if args.type == "web" %}
          {{ id }}-group.group.name: {{ args.name }}
        {% elif args.type == "web-group" %}
          {{ id }}-group.group.name: {{ args.name }}
          {{ id }}-svc-group.group.parent_name: {{ id }}-group
          {{ id }}-svc-group.group.name: {{ args.name }} App
        {% elif service_id is defined and args.type in ["redis", "mysql", "postgres", "web-support"] %}
          {{ id }}-svc-group.group.parent_name: {{ service_id }}-group
          {{ id }}-svc-group.group.name: {{ args.name }}{% if args.type == "web-support" %} App{% endif %}
        {% endif %}

        {# Web containers get http & https checks #}
        {% if args.type in ["web-group", "web", "web-support"] %}
          {% if args.type == "web" %}
            {% set parent = id ~ "-group" %}
          {% else %}
            {% set parent = id ~ "-svc-group" %}
          {% endif %}
          {{ id }}-https.http.parent_name: {{ parent }}
          {{ id }}-https.http.name: {{ args.name }} (Web)
          {{ id }}-https.http.url: {{ args.url }}
          {{ id }}-http.http.parent_name: {{ parent }}
          {{ id }}-http.http.name: {{ args.name }} (Internal)
          {% if args.network and args.network == "host" %}
            {{ id }}-http.http.url: http://10.0.20.15:{{ args.internal_port }}
          {% elif args.network and args.network == "vpn" %}
            {{ id }}-http.http.url: http://{{ container_name }}-vpn:{{ args.internal_port }}
          {% else %}
            {{ id }}-http.http.url: http://{{ container_name }}:{{ args.internal_port }}
          {% endif %}
          {# Check for authentication and set basic auth details #}
          {% if args.auth and args.auth == "basic" %}
            {{ id }}-http.http.authMethod: {{ args.auth }}
            {{ id }}-http.http.basic_auth_user: {{ args.auth_user }}
            {{ id }}-http.http.basic_auth_pass: {{ args.auth_pass }}
            {{ id }}-https.http.authMethod: {{ args.auth }}
            {{ id }}-https.http.basic_auth_user: {{ args.auth_user }}
            {{ id }}-https.http.basic_auth_pass: {{ args.auth_pass }}
          {% endif %}
        {% endif %}

        {# Database containers get db specific checks #}
        {% if args.type in ["redis", "mysql", "postgres"] %}
          {{ id }}-db.{{ args.type }}.name: {{ args.name }} (DB)
          {{ id }}-db.{{ args.type }}.parent_name: {{ id }}-svc-group
          {{ id }}-db.{{ args.type }}.database_connection_string: {{ args.db_url }}
        {% endif %}

        {# All containers get a container check #}
        {% if args.type == "web" %}
          {% set parent_name = id ~ "-group" %}
          {{ id }}-container.docker.parent_name: {{ parent_name }}
        {% elif args.type not in ["solo", "support"] %}
          {% set parent_name = id ~ "-svc-group" %}
          {{ id }}-container.docker.parent_name: {{ parent_name }}
        {% endif %}
        {% if args.type == "support" %}
          {{ id }}-container.docker.parent_name: {{ service_id }}-group
        {% endif %}
        {% if args.type in ["solo", "support"] %}
          {{ id }}-container.docker.name: {{ args.name }}
        {% else %}
          {{ id }}-container.docker.name: {{ args.name }} (Container)
        {% endif %}
        {{ id }}-container.docker.docker_container: {{ container_name }}
        {{ id }}-container.docker.docker_host: 1
      DOCKER_HOST: http://socket-proxy:2375
    labels:
      ## Logging
      logging.promtail: true
      ## Unraid
      net.unraid.docker.managed: composeman
      net.unraid.docker.icon: 
      ## Autokuma
      kuma.__app: '{ "name": "AutoKuma", "type": "support", "service": "Uptime-Kuma" }'

```

Docker logs
<details>
```
2025-01-23T17:21:23.611551784Z 2025-01-23T09:21:23-08:00 [MONITOR] INFO: Try to restart the monitor
2025-01-23T17:21:23.787189881Z Trace: Error: insert into `stat_hourly` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (0, 383, 114.5, 148, 79, 1737651600, 4) - Duplicate entry '383-1737651600' for key 'stat_hourly_monitor_id_timestamp_unique'
2025-01-23T17:21:23.787220389Z     at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:740:17)
2025-01-23T17:21:23.787227688Z     at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
2025-01-23T17:21:23.787232444Z     at Connection.handlePacket (/app/node_modules/mysql2/lib/base/connection.js:475:34)
2025-01-23T17:21:23.787239228Z     at PacketParser.onPacket (/app/node_modules/mysql2/lib/base/connection.js:93:12)
2025-01-23T17:21:23.787243947Z     at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
2025-01-23T17:21:23.787248563Z     at Socket.<anonymous> (/app/node_modules/mysql2/lib/base/connection.js:100:25)
2025-01-23T17:21:23.787253787Z     at Socket.emit (node:events:519:28)
2025-01-23T17:21:23.787258643Z     at addChunk (node:internal/streams/readable:559:12)
2025-01-23T17:21:23.787301091Z     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
2025-01-23T17:21:23.787382017Z     at Readable.push (node:internal/streams/readable:390:5) {
2025-01-23T17:21:23.787416671Z   code: 'ER_DUP_ENTRY',
2025-01-23T17:21:23.787429073Z   errno: 1062,
2025-01-23T17:21:23.787434424Z   sqlState: '23000',
2025-01-23T17:21:23.787439937Z   sqlMessage: "Duplicate entry '383-1737651600' for key 'stat_hourly_monitor_id_timestamp_unique'",
2025-01-23T17:21:23.787445569Z   sql: 'insert into `stat_hourly` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (0, 383, 114.5, 148, 79, 1737651600, 4)'
2025-01-23T17:21:23.787451565Z }
2025-01-23T17:21:23.787456641Z     at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1012:25)
2025-01-23T17:21:23.787463914Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-23T17:21:23.787537872Z 2025-01-23T09:21:23-08:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
2025-01-23T17:21:23.787711924Z 2025-01-23T09:21:23-08:00 [MONITOR] INFO: Try to restart the monitor
2025-01-23T17:21:24.392477267Z Trace: Error: insert into `stat_hourly` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (0, 397, 17.25, 27, 12, 1737651600, 4) - Duplicate entry '397-1737651600' for key 'stat_hourly_monitor_id_timestamp_unique'
2025-01-23T17:21:24.392509675Z     at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:740:17)
2025-01-23T17:21:24.392517013Z     at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
2025-01-23T17:21:24.392522545Z     at Connection.handlePacket (/app/node_modules/mysql2/lib/base/connection.js:475:34)
2025-01-23T17:21:24.392528357Z     at PacketParser.onPacket (/app/node_modules/mysql2/lib/base/connection.js:93:12)
2025-01-23T17:21:24.392533668Z     at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
2025-01-23T17:21:24.392538672Z     at Socket.<anonymous> (/app/node_modules/mysql2/lib/base/connection.js:100:25)
2025-01-23T17:21:24.392585763Z     at Socket.emit (node:events:519:28)
2025-01-23T17:21:24.392637412Z     at addChunk (node:internal/streams/readable:559:12)
2025-01-23T17:21:24.392663737Z     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
2025-01-23T17:21:24.392683375Z     at Readable.push (node:internal/streams/readable:390:5) {
2025-01-23T17:21:24.392713916Z   code: 'ER_DUP_ENTRY',
2025-01-23T17:21:24.392728985Z   errno: 1062,
2025-01-23T17:21:24.392734711Z   sqlState: '23000',
2025-01-23T17:21:24.392739487Z   sqlMessage: "Duplicate entry '397-1737651600' for key 'stat_hourly_monitor_id_timestamp_unique'",
2025-01-23T17:21:24.392744301Z   sql: 'insert into `stat_hourly` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (0, 397, 17.25, 27, 12, 1737651600, 4)'
2025-01-23T17:21:24.392751163Z }
2025-01-23T17:21:24.392755835Z     at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1012:25)
2025-01-23T17:21:24.392760608Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-23T17:21:24.392794632Z 2025-01-23T09:21:24-08:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
2025-01-23T17:21:24.392896869Z 2025-01-23T09:21:24-08:00 [MONITOR] INFO: Try to restart the monitor
2025-01-23T17:21:24.721968022Z Trace: Error: insert into `stat_hourly` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (0, 399, 97.75, 116, 81, 1737651600, 4) - Duplicate entry '399-1737651600' for key 'stat_hourly_monitor_id_timestamp_unique'
2025-01-23T17:21:24.721990205Z     at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:740:17)
2025-01-23T17:21:24.721994786Z     at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
2025-01-23T17:21:24.721998148Z     at Connection.handlePacket (/app/node_modules/mysql2/lib/base/connection.js:475:34)
2025-01-23T17:21:24.722001281Z     at PacketParser.onPacket (/app/node_modules/mysql2/lib/base/connection.js:93:12)
2025-01-23T17:21:24.722006068Z     at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
2025-01-23T17:21:24.722010151Z     at Socket.<anonymous> (/app/node_modules/mysql2/lib/base/connection.js:100:25)
2025-01-23T17:21:24.722013711Z     at Socket.emit (node:events:519:28)
2025-01-23T17:21:24.722016922Z     at addChunk (node:internal/streams/readable:559:12)
2025-01-23T17:21:24.722019997Z     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
2025-01-23T17:21:24.722023024Z     at Readable.push (node:internal/streams/readable:390:5) {
2025-01-23T17:21:24.722026041Z   code: 'ER_DUP_ENTRY',
2025-01-23T17:21:24.722029016Z   errno: 1062,
2025-01-23T17:21:24.722032485Z   sqlState: '23000',
2025-01-23T17:21:24.722037386Z   sqlMessage: "Duplicate entry '399-1737651600' for key 'stat_hourly_monitor_id_timestamp_unique'",
2025-01-23T17:21:24.722042320Z   sql: 'insert into `stat_hourly` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (0, 399, 97.75, 116, 81, 1737651600, 4)'
2025-01-23T17:21:24.722046206Z }
2025-01-23T17:21:24.722050138Z     at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1012:25)
2025-01-23T17:21:24.722053183Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-23T17:21:24.722193757Z 2025-01-23T09:21:24-08:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
2025-01-23T17:21:24.722433178Z 2025-01-23T09:21:24-08:00 [MONITOR] INFO: Try to restart the monitor
2025-01-23T17:21:24.784462588Z Trace: Error: insert into `stat_daily` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (0, 405, 16.25, 27, 10, 1737590400, 4) - Duplicate entry '405-1737590400' for key 'stat_daily_monitor_id_timestamp_unique'
2025-01-23T17:21:24.784486391Z     at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:740:17)
2025-01-23T17:21:24.784491063Z     at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
2025-01-23T17:21:24.784494486Z     at Connection.handlePacket (/app/node_modules/mysql2/lib/base/connection.js:475:34)
2025-01-23T17:21:24.784498761Z     at PacketParser.onPacket (/app/node_modules/mysql2/lib/base/connection.js:93:12)
2025-01-23T17:21:24.784502372Z     at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
2025-01-23T17:21:24.784505856Z     at Socket.<anonymous> (/app/node_modules/mysql2/lib/base/connection.js:100:25)
2025-01-23T17:21:24.784509237Z     at Socket.emit (node:events:519:28)
2025-01-23T17:21:24.784512320Z     at addChunk (node:internal/streams/readable:559:12)
2025-01-23T17:21:24.784515573Z     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
2025-01-23T17:21:24.784519413Z     at Readable.push (node:internal/streams/readable:390:5) {
2025-01-23T17:21:24.784522685Z   code: 'ER_DUP_ENTRY',
2025-01-23T17:21:24.784526324Z   errno: 1062,
2025-01-23T17:21:24.784529399Z   sqlState: '23000',
2025-01-23T17:21:24.784532524Z   sqlMessage: "Duplicate entry '405-1737590400' for key 'stat_daily_monitor_id_timestamp_unique'",
2025-01-23T17:21:24.784536569Z   sql: 'insert into `stat_daily` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (0, 405, 16.25, 27, 10, 1737590400, 4)'
2025-01-23T17:21:24.784539874Z }
2025-01-23T17:21:24.784544418Z     at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1012:25)
2025-01-23T17:21:24.784548589Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-23T17:21:24.784661939Z 2025-01-23T09:21:24-08:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
2025-01-23T17:21:24.784811694Z 2025-01-23T09:21:24-08:00 [MONITOR] INFO: Try to restart the monitor
2025-01-23T17:21:24.897219363Z Trace: Error: insert into `stat_hourly` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (0, 407, 16.25, 27, 10, 1737651600, 4) - Duplicate entry '407-1737651600' for key 'stat_hourly_monitor_id_timestamp_unique'
2025-01-23T17:21:24.897250988Z     at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:740:17)
2025-01-23T17:21:24.897258161Z     at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
2025-01-23T17:21:24.897263144Z     at Connection.handlePacket (/app/node_modules/mysql2/lib/base/connection.js:475:34)
2025-01-23T17:21:24.897269206Z     at PacketParser.onPacket (/app/node_modules/mysql2/lib/base/connection.js:93:12)
2025-01-23T17:21:24.897273679Z     at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
2025-01-23T17:21:24.897278531Z     at Socket.<anonymous> (/app/node_modules/mysql2/lib/base/connection.js:100:25)
2025-01-23T17:21:24.897283262Z     at Socket.emit (node:events:519:28)
2025-01-23T17:21:24.897288747Z     at addChunk (node:internal/streams/readable:559:12)
2025-01-23T17:21:24.897293005Z     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
2025-01-23T17:21:24.897297944Z     at Readable.push (node:internal/streams/readable:390:5) {
2025-01-23T17:21:24.897302820Z   code: 'ER_DUP_ENTRY',
2025-01-23T17:21:24.897307816Z   errno: 1062,
2025-01-23T17:21:24.897314024Z   sqlState: '23000',
2025-01-23T17:21:24.897319924Z   sqlMessage: "Duplicate entry '407-1737651600' for key 'stat_hourly_monitor_id_timestamp_unique'",
2025-01-23T17:21:24.897325595Z   sql: 'insert into `stat_hourly` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (0, 407, 16.25, 27, 10, 1737651600, 4)'
2025-01-23T17:21:24.897330587Z }
2025-01-23T17:21:24.897335066Z     at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1012:25)
2025-01-23T17:21:24.897339416Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-23T17:21:24.897403833Z 2025-01-23T09:21:24-08:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
2025-01-23T17:21:24.897540501Z 2025-01-23T09:21:24-08:00 [MONITOR] INFO: Try to restart the monitor
2025-01-23T17:21:25.197326916Z 2025-01-23T09:21:25-08:00 [MONITOR] WARN: Monitor #415 'qBittorrent (Music) App': Failing: Child inaccessible | Interval: 60 seconds | Type: group | Down Count: 0 | Resend Interval: 0
2025-01-23T17:21:25.538686587Z Trace: Error: insert into `stat_hourly` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (0, 419, 97.25, 115, 80, 1737651600, 4) - Duplicate entry '419-1737651600' for key 'stat_hourly_monitor_id_timestamp_unique'
2025-01-23T17:21:25.538720056Z     at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:740:17)
2025-01-23T17:21:25.538724905Z     at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
2025-01-23T17:21:25.538728241Z     at Connection.handlePacket (/app/node_modules/mysql2/lib/base/connection.js:475:34)
2025-01-23T17:21:25.538731486Z     at PacketParser.onPacket (/app/node_modules/mysql2/lib/base/connection.js:93:12)
2025-01-23T17:21:25.538734833Z     at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
2025-01-23T17:21:25.538738804Z     at Socket.<anonymous> (/app/node_modules/mysql2/lib/base/connection.js:100:25)
2025-01-23T17:21:25.538742823Z     at Socket.emit (node:events:519:28)
2025-01-23T17:21:25.538746266Z     at addChunk (node:internal/streams/readable:559:12)
2025-01-23T17:21:25.538749999Z     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
2025-01-23T17:21:25.538753150Z     at Readable.push (node:internal/streams/readable:390:5) {
2025-01-23T17:21:25.538756240Z   code: 'ER_DUP_ENTRY',
2025-01-23T17:21:25.538759378Z   errno: 1062,
2025-01-23T17:21:25.538762493Z   sqlState: '23000',
2025-01-23T17:21:25.538767252Z   sqlMessage: "Duplicate entry '419-1737651600' for key 'stat_hourly_monitor_id_timestamp_unique'",
2025-01-23T17:21:25.538771091Z   sql: 'insert into `stat_hourly` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (0, 419, 97.25, 115, 80, 1737651600, 4)'
2025-01-23T17:21:25.538774742Z }
2025-01-23T17:21:25.538778249Z     at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1012:25)
2025-01-23T17:21:25.538781386Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-23T17:21:25.539011944Z 2025-01-23T09:21:25-08:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
2025-01-23T17:21:25.539245351Z 2025-01-23T09:21:25-08:00 [MONITOR] INFO: Try to restart the monitor
2025-01-23T17:21:25.674471871Z Trace: Error: insert into `stat_hourly` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (0, 424, 27.25, 42, 15, 1737651600, 4) - Duplicate entry '424-1737651600' for key 'stat_hourly_monitor_id_timestamp_unique'
2025-01-23T17:21:25.674504752Z     at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:740:17)
2025-01-23T17:21:25.674509555Z     at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
2025-01-23T17:21:25.674514415Z     at Connection.handlePacket (/app/node_modules/mysql2/lib/base/connection.js:475:34)
2025-01-23T17:21:25.674519267Z     at PacketParser.onPacket (/app/node_modules/mysql2/lib/base/connection.js:93:12)
2025-01-23T17:21:25.674527562Z     at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
2025-01-23T17:21:25.674532648Z     at Socket.<anonymous> (/app/node_modules/mysql2/lib/base/connection.js:100:25)
2025-01-23T17:21:25.674536771Z     at Socket.emit (node:events:519:28)
2025-01-23T17:21:25.674540851Z     at addChunk (node:internal/streams/readable:559:12)
2025-01-23T17:21:25.674544547Z     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
2025-01-23T17:21:25.674548247Z     at Readable.push (node:internal/streams/readable:390:5) {
2025-01-23T17:21:25.674551781Z   code: 'ER_DUP_ENTRY',
2025-01-23T17:21:25.674555178Z   errno: 1062,
2025-01-23T17:21:25.674560472Z   sqlState: '23000',
2025-01-23T17:21:25.674564250Z   sqlMessage: "Duplicate entry '424-1737651600' for key 'stat_hourly_monitor_id_timestamp_unique'",
2025-01-23T17:21:25.674568026Z   sql: 'insert into `stat_hourly` (`down`, `monitor_id`, `ping`, `ping_max`, `ping_min`, `timestamp`, `up`) values (0, 424, 27.25, 42, 15, 1737651600, 4)'
2025-01-23T17:21:25.674571545Z }
2025-01-23T17:21:25.674575069Z     at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1012:25)
2025-01-23T17:21:25.674579584Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-23T17:21:25.674911003Z 2025-01-23T09:21:25-08:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
2025-01-23T17:21:25.675157980Z 2025-01-23T09:21:25-08:00 [MONITOR] INFO: Try to restart the monitor
```
</details>

**Comment by CommanderStorm** [comment]
Fair enough, lets consolidate this in
- https://github.com/louislam/uptime-kuma/issues/5357

From my mind, the quiue key is not the problem, but the code inserting should likely do a on duplicate update or will need looking into how this can even happen.
