### ISSUE TITLE
Webhooks Fail

### ISSUE THREAD

**Issue by chriskuchin** [louislam/uptime-kuma#569]
**Is it a duplicate question?**
Searched for webhook and couldn't find any results

**Describe the bug**
Setting up a webhook notification fails to trigger when tested or when triggered by failing test.

**To Reproduce**

**Expected behavior**
Webhooks should trigger when tested or when a test fails

**Info**
Uptime Kuma Version: :1
Using Docker?: Yes
Docker Version: 
Browser: Firefox

**Error Log**
```TypeError: callback is not a function
    at Socket.<anonymous> (/app/server/server.js:544:17)
Trace: TypeError: callback is not a function
    at Socket.<anonymous> (/app/server/server.js:549:17)
    at process.<anonymous> (/app/server/server.js:1411:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues```

**Comment by louislam** [comment]
The wehbook should be working, the error is not relevant.
https://webhook.site/


https://github.com/louislam/uptime-kuma/commit/3394e1f148efc1c3280a4cea78fafce02a553ac4
