### ISSUE TITLE
arm64 building need chromium binary (puppeteer dep).

### ISSUE THREAD

**Issue by martadinata666** [louislam/uptime-kuma#586]
**Info**
Uptime Kuma Version: latest git
Using Docker?: Yes
Docker Version: 20.10.8
Node.js Version (Without Docker only): 14
OS: arm64 manjaro
Browser: Firefox, chromium installed

Building arm64 throw error:
```
#19 [linux/arm64 fetcher 5/5] RUN npm install --legacy-peer-deps &&     npm run build &&     npm prune --production
#19 165.2 
#19 165.2 > @louislam/sqlite3@5.0.6 install /home/debian/uptime-kuma/node_modules/@louislam/sqlite3
#19 165.2 > node-pre-gyp install --fallback-to-build
#19 165.2 
#19 168.7 [@louislam/sqlite3] Success: "/home/debian/uptime-kuma/node_modules/@louislam/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node" is installed via remote
#19 168.8 
#19 168.8 > puppeteer@10.4.0 install /home/debian/uptime-kuma/node_modules/puppeteer
#19 168.8 > node install.js
#19 168.8 
#19 170.8 The chromium binary is not available for arm64.
#19 170.8 If you are on Ubuntu, you can install with: 
#19 170.8 
#19 170.8  sudo apt install chromium
#19 170.8 
#19 170.8 
#19 170.8  sudo apt install chromium-browser
#19 170.8 
#19 170.8 /home/debian/uptime-kuma/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:115
#19 170.8                     throw new Error();
#19 170.8                     ^
#19 170.8 
#19 170.8 Error
#19 170.8     at /home/debian/uptime-kuma/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:115:27
#19 170.8     at FSReqCallback.oncomplete (fs.js:191:21)
#19 175.3 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
#19 175.3 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#19 175.3 
#19 175.4 npm ERR! code ELIFECYCLE
#19 175.4 npm ERR! errno 1
#19 175.5 npm ERR! puppeteer@10.4.0 install: `node install.js`
#19 175.5 npm ERR! Exit status 1
#19 175.5 npm ERR! 
#19 175.5 npm ERR! Failed at the puppeteer@10.4.0 install script.
#19 175.5 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#19 175.7 
#19 175.7 npm ERR! A complete log of this run can be found in:
#19 175.7 npm ERR!     /home/debian/.npm/_logs/2021-10-07T02_35_46_150Z-debug.log
#19 ERROR: process "/bin/sh -c npm install --legacy-peer-deps &&     npm run build &&     npm prune --production" did not complete successfully: exit code: 1
------
```

Build fine on amd64 due availability chromium binary.
```
#16 42.11 
#16 42.11 > puppeteer@10.4.0 install /home/debian/uptime-kuma/node_modules/puppeteer
#16 42.11 > node install.js
#16 42.11 
#16 110.8 
#16 114.2 Chromium (901912) downloaded to /home/debian/uptime-kuma/node_modules/puppeteer/.local-chromium/linux-901912
#16 114.2 
#16 114.2 > @fortawesome/fontawesome-common-types@0.2.36 postinstall /home/debian/uptime-kuma/node_modules/@fortawesome/fontawesome-common-types
#16 114.2 > node attribution.js
#16 114.2 
```

**Comment by martadinata666** [comment]
Ah ok, got it. Thanks for the help. Build correctly now.

```
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
```
