### ISSUE TITLE
Unable to start: SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by Cyneric** [louislam/uptime-kuma#931]
⚠️ Please verify that this bug has NOT been raised before.
 I checked and didn't find similar issue
🛡️ Security Policy
 I agree to have read this project Security Policy
📝 Describe your problem
root@kuma:/opt/uptime-kuma# node server/server.js
Welcome to Uptime Kuma
Node Env: production
Importing Node libraries
Importing 3rd-party libraries
Importing this project modules
/opt/uptime-kuma/server/model/monitor.js:172
                    if (this.getUrl()?.protocol === "https:") {
                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/uptime-kuma/server/server.js:42:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

🐻 Uptime-Kuma Version
1.10.2

💻 Operating System and Arch
Ubuntu 21.04 Server / Kernel: x86_64 Linux 5.11.22-5-pve

🌐 Browser
Brave Version 1.31.91 Chromium: 95.0.4638.69

🐋 Docker Version
-

🟩 NodeJS Version
Node v12.21.0 / Node.js v17.1.0

**Comment by Cyneric** [comment]
System: Ubuntu 21.04 Server
Kernel: x86_64 Linux 5.11.22-5-pve
