### ISSUE TITLE
Setup on ubuntu 20.04 on Google Cloud

### ISSUE THREAD

**Issue by CezaDark** [louislam/uptime-kuma#974]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

can you give me tutorial?
Because i'm trying to setup but the error on Cannot listen: listen EADDRINUSE: address already in use :::3001 And Trace: Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at new NodeError (internal/errors.js:322:7)
    at Server.close (net.js:1624:12)
    at Object.onceWrapper (events.js:519:28)
    at Server.emit (events.js:412:35)
    at emitCloseNT (net.js:1677:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ERR_SERVER_NOT_RUNNING'
}
    at process.<anonymous> (/opt/uptime-kuma/uptime-kuma/server/server.js:1540:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Ubuntu 20.04 x86_64

### 🌐 Browser

i'm using trial

### 🟩 NodeJS Version

14.18.1

**Comment by louislam** [comment]
You should check what is using 3001.

**Comment by DevGhosti** [comment]
`pkill 3001`
rerun command

**Comment by trogper** [comment]
Just a side question, since you are running it on Google Cloud:
Have you considered running just the container in Cloud Run instead of a VM?
